### ISSUE TITLE
Bug in {}-form of MOLD

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1004]
When molding a string containing ", the {} form is used:
`print mold "^""=> {"}`.

The bug appears if the string contains unbalanced { }:
`print mold "^"}" => {"^}`
`print mold "^"}{" => {"^^}`

**Comment by hostilefork** [comment]
Sorry this trivial-to-fix bug took two weeks to look into (!) but it's been a very busy two weeks...trying to get my bearings in Philadelphia, and get local people interested in the conference!

Should be fixed...:

https://github.com/metaeducation/ren-c/commit/f7ae0e35f35b174a84bb318d98eea0e1821b7834#diff-3a98d76d3d02a4faa42685e978088e86R854
