### ISSUE TITLE
REPL broken after incorrect js-native

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#1018]
Wrong javascript code will break the console, e.g.

    f: js-native[]{a = 10x}

after running this, the console does no longer react to input, the javascriptconsole shows the following error:

    VM251:1 Uncaught SyntaxError: Invalid or unexpected token
    at ASM_CONSTS (libr3-762961b.js:901)
    at _emscripten_receive_on_main_thread_js (libr3-762961b.js:1706)
    at /media/shared/replpad-js/wasm-function[1063]:209
    at /media/shared/replpad-js/wasm-function[1065]:164
    at /media/shared/replpad-js/wasm-function[789]:8
    at Module._emscripten_main_thread_process_queued_calls (libr3-762961b.js:3205)
    at Worker.worker.onmessage (libr3-762961b.js:1396)

Now, if I have started the editor before breaking the console, it still can DO Rebol code, so the interpreter must still be responsive, it's just the REPL itself, which no longer reacts.

    do https://raw.githubusercontent.com/IngoHohmann/rebol-web-scripts/master/editor.r
    ; add rebol code, click on "DO"

**Comment by hostilefork** [comment]
Believed to be resolved (for the time being) by:

https://github.com/metaeducation/ren-c/commit/a6960f2368687c5521d0c764a389f79607e788d9
