### ISSUE TITLE
PARSE performance

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1019]
I noticed a dramatic loss of performance when parsing a large not-ASCII text, apparently due to GC.
The workaround I found is parsing as binary, but it isn't always possible

**Comment by hostilefork** [comment]
Thanks, I will look into it...

**Comment by hostilefork** [comment]
It seems the UTF-8 Everywhere caching strategy was fairly broken.  I added more instrumentation to it, and it seems to be somewhat better:

https://github.com/metaeducation/ren-c/commit/8f0dd1347b38958c0dff5c8e36256148eaf3de15

Let me know if that helps enough for your purposes.

**Comment by giuliolunati** [comment]
Very good!!

Tests on my phone:

500k xml file:
- parsing as text, before: 39s / now: 1.2s
- parsing as binary: 1.16s

2M xml file, now (before I gave up!)
- as text: 4.2s
- as binary: 3.9s
