### ISSUE TITLE
AUGMENT of READ with /BINARY as a no-op complains

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#1021]
Adding arguments and refinements with AUGMENT should not add any new behaviors, but simply ignore the refinement:

    >> add: augment 'lib/add [/binary]
    == make action! [[value1 value2 /binary] [...]]

    >> add/binary 1 2
    == 3

But it seems trying to add /BINARY onto READ causes a complaint:

    >> read: augment 'lib/read [/binary] 
    == make action! [[source /part /seek /string /lines /binary] [...]]

    >> read/binary http://rebol.com
    ** Script Error: incompatible or duplicate refinement: binary

This impedes creation of a compatibility READ in Redbol.

**Comment by gchiu** [comment]
`>> call: augment 'lib/call [/wait]

** Script Error: duplicate variable specified: wait
** Where: _ do _ augment console
** Near: []`

**Comment by hostilefork** [comment]
The CALL issue is different: https://github.com/metaeducation/ren-c/issues/1023

However I believe the issue affecting the /BINARY is solved here:

https://github.com/metaeducation/ren-c/commit/6395178b6661104d0464e061a652656f1ea9bf6b
