### ISSUE TITLE
NEW-LINE/ALL doesn't set tail pos

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1033]
new-line/all [1 2] true
== [
  1
  2]

I expected:

== [
  1
  2
]

That's intentional?

**Comment by hostilefork** [comment]
> That's intentional?

Nope.  Your expectation seems reasonable to me...

Changed here:

https://github.com/metaeducation/ren-c/commit/9166dff4ba74ded7024d001980af480b593cf91d
