### ISSUE TITLE
BIND/NEW fails inside FUNCTION body

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1035]
`f: function [] [
  a: 0
  bind/new 'b 'a
] f`
=>
`** Internal Error: locked series expansion`
(Obviously enough, `func` works well.)

**Comment by hostilefork** [comment]
> (Obviously enough, func works well.)

Unfortunately, it's not necessarily obvious!

Currently BIND is a mutating operation, on the code you run it on.   That means if you are to rebind a function body, you will be rebinding it for all calls to that function.  I don't like this (at least most of the time, it's not what you want).

This is why I've spoken about "virtual binding" so much.  I had suggested maybe IN would be non-mutating (hence allowed on const/locked arrays) while BIND would be mutating (not allowed on const/locked arrays).

Thinking about what are the rules of the Rebol game is hard, I do not know if you read this:

https://forum.rebol.info/t/compatibility-map-each-and-problems-therewith/1192

Binding needs a lot of thought... I'm thinking on it (!)

**Comment by hostilefork** [comment]
Pure Virtual Binding II solves all this and more!!

  https://forum.rebol.info/t/rebol-and-scopes-well-why-not/1751/9?u=hostilefork

(hope all is well...lots of activity going on right now on the Ren-C forum...many things are being resolved!)
