### ISSUE TITLE
handle not rebReleased(), not legal ATM

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#1044]
```
>> read http://localhost:8081
(i) Info: use WHY for error information
** Access Error: protocol error: "Timeout"
** Where: fail if while sync-op else _ read console
** Near: [
    fail make-http-error "Timeout" ~~]
** Line: 1321

>> q
handle not rebReleased(), not legal ATM
C Source File ../src/core/m-gc.c, Line 533, Pointer 00000000033DB648
At evaluator tick: 288251
managed series was likely created during evaluator tick: 283332
C Source File ../src/core/m-series.c, Line 492, Pointer 00000000007E2A08
At evaluator tick: 288251
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:


Executable not built with DEBUG_SERIES_ORIGINS, no more info

```

using: /r3-4ad92eb-debug.exe

**Comment by hostilefork** [comment]
I tried a naive attempt to reproduce this, with this code as the server:

    do https://raw.githubusercontent.com/metaeducation/rebol-httpd/master/httpd.reb
  
    wait srv: open [scheme: 'httpd 8081 [wait 1000]]

However I do not get the message you get.  It quits successfully.

**Comment by gchiu** [comment]
I saw this error a lot. It happened when the server crashed and left the client in an odd state that meant it could no longer do a read. So it must be some state in the prot-http.r

**Comment by hostilefork** [comment]
Believed solved here:

https://github.com/metaeducation/ren-c/commit/4c310b0d602d8564d1cb06da8c1e366a479c0893
