### ISSUE TITLE
remove is now acting as `clear

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#1053]
```
>> remove a: {abcd}
== ""

>> head a
== ""
```

**Comment by hostilefork** [comment]
This is something that happened in UTF-8 Everywhere and there was no test to catch it.

The best fix may be to turn REMOVE into a specialization of CHANGE (e.g. "change this range of the data to NULL").  That will take some work, so this just does the easy fix for now:

https://github.com/metaeducation/ren-c/commit/1e3c475e4220b77686eaf26ba0df8b35c040e511
