### ISSUE TITLE
Setting vector component with ME aborts

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1072]
`a: [1] a/1: me / 3` 
aborts with
`../src/include/sys-bind.h:96: REBSPC *VAL_SPECIFIER(const struct Reb_Value *): assertion "ANY_ARRAY_KIND(CELL_KIND(v))" failed`

**Comment by hostilefork** [comment]
This is one of what are likely going to be a lot of issues arising from `/` being a PATH! and a WORD! at the same time.

There will need to be a more systemic approach to it, but here's a patch for this particular one:

https://github.com/metaeducation/ren-c/commit/ce99c5be095f0fdc0e4b30ea7c347f77f71da7d1
