### ISSUE TITLE
address boundary error on char? test for multicharacter issue

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#1083]
Well, it's easier shown then written:

````
>> char? #a
== #[true]

>> char? #ab
fish: “r3” terminated by signal SIGSEGV (Address boundary error)
````

**Comment by hostilefork** [comment]
Thanks for testing!... addressing this required making a change that made it seem fairly obvious to add a SIZE reflector, so you can get the UTF-8 encoding **size of** strings or issues without converting them to binary now:

https://github.com/metaeducation/ren-c/blob/6eb0ae5f5330aa81fa306d89cd0e1facff31b902/tests/datatypes/char.test.reb#L11
