### ISSUE TITLE
Can't load YYYY-MM-DD/HH:MM:SS.SS

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1097]
`load "2020-1-1/0:00:00"` 
=> 1-Jan-2020/0:00

But:

`load "2020-1-1/0:00:00.5"`
=> Error: #{00} bytes illegal in ANY-STRING!, use BINARY!

**Comment by hostilefork** [comment]
Sorry to miss this, didn't get the notification.  Shouldn't be hard to fix...

**Comment by hostilefork** [comment]
Believed fixed here:

https://github.com/metaeducation/ren-c/commit/ef168cfeac2d13cc0070a1cce0aa945782599c27

**Comment by giuliolunati** [comment]
Yes, now it works, thank you!
(But see #1098 please)
