### ISSUE TITLE
Date comparison is wrong

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1098]
`2020-11-24 > 2020-11-25` => true
`2020-11-24 < 2020-11-25` => false

**Comment by hostilefork** [comment]
Oops.  :-(  Date comparison with > and < was broken in a shakeup to try and get comparison to make more sense.  Unfortunately, there apparently wasn't any testing to catch that.

Addressed here: https://github.com/metaeducation/ren-c/commit/8226e50707d0de0e4a00c2ccb08606a9dac31b2c

It's easier to see what's going on with comparisons now than it was.  But I don't really know what direction comparison semantics should go in.  Here are some general thoughts if you missed them:

https://forum.rebol.info/t/comparison-semantics/1318

Notice in particular the bullet points at the bottom.

> *I have an uneasy feeling about building comparison operators on top of method code that carries along a boolean "strict" argument. It seems like a kind of arbitrary and poorly-defined wart. I'm not sure what the alternatives are, however, if the current abilities are to be preserved.*
>
> *My intuition is that it's probably better to build "downwards in formality" from the typeclasses of Haskell/Rust, as opposed to trying to build "upwards in formality" from something like Python's approach, just because I am skeptical of the organic comparisons that can so easily become inconsistent...e.g. by prioritizing the left side's answer in a comparison over the right.*
