### ISSUE TITLE
IMPORT 'module-name is broken

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1100]
`import 'module-name`
=>
** Error: FILE! pathing replaced by %% and MAKE-FILE, see: https://forum.rebol.info/t/1398
** Where: applique for-each case import do catch either else _ do console
** Near: [source: path/(:file)
...

**Comment by hostilefork** [comment]
Hopefully fixed here:

https://github.com/metaeducation/ren-c/commit/dc391fe8fe860ba0131d86fb6b226c62bd930406

**Comment by giuliolunati** [comment]
Yes, it's solved, thx!
