### ISSUE TITLE
crash on `help "any"`

### ISSUE THREAD

**Issue by MarkoSchuetz** [metaeducation/ren-c#1106]
Entering `help "any"` at the REPL crashes
>> help "any"
r3: ../src/core/f-stubs.c:217: Datatype_From_Kind: Assertion `IS_DATATYPE(type)' failed.
[1]    1671301 abort (core dumped)  ./build/r3

**Comment by hostilefork** [comment]
A fitting crash to hit, considering it deals with the corners of the broken TYPESET! system...

A textual search for "any" hit a number of the ANY-XXX! typeset definitions, and forced some bad ones to render.  Mitigated here, but the real mitigation is to rethink the approach entirely...

https://github.com/metaeducation/ren-c/commit/808c70d79ab142ac624b8185b686e37e7ce3de3f
