### ISSUE TITLE
Linux: PANIC ACTION! is being triggered from a usermode call

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#1121]
On A r3 binary compiled from c3ff0c0b6 I get the following error on startup

PANIC ACTION! is being triggered from a usermode call

r3 does close afterwards.

Compiled with standard ./make.sh

**Comment by andrewarchi** [comment]
I'm getting that as well on macOS. The first bad commit appears to be 214957d3 via `git bisect`.

**Comment by giuliolunati** [comment]
Also for Android build

Il sab 22 mag 2021, 12:08 Andrew Archibald ***@***.***> ha
scritto:

**Comment by hostilefork** [comment]
Sorry about this...I was getting everything off a laptop to hand it off, before heading out the door for some traveling.  In a rush, I pushed some code without testing it on POSIX, apparently.  Then I was traveling so did not see this issue. :-/

Believed fixed here:

https://github.com/metaeducation/ren-c/commit/e040c1f6bd45ad4a8b8aba78c29541c2a8990cbc

Thanks for doing the bisect, @andrewarchi ... please feel free to introduce yourself and your interests here:

https://forum.rebol.info/c/introductions/46
