### ISSUE TITLE
Error in SOURCE UPARSE, SOURCE PARSE

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1123]
`>> source uparse`
=>
** Script Error: keep requires value argument to not be null
** Where: _ reeval collect* collect spec-of unspaced source console
** Near: [*** select meta 'description **
    types: ensure [<opt> fr...
** File: -tmp-boot-

Same with `source parse`

(tested with OS 0.13.2, 92171dcf, nodebug)

**Comment by hostilefork** [comment]
Bug, and it's a consequence of this, which I know is inconvenient to absorb but I believe it is converging on the right answer:

https://forum.rebol.info/t/the-long-awaited-death-of-only/1607

Sorry there's so much to learn, but I'm trying to get things *right*!  :-)

**Comment by hostilefork** [comment]
Here's a bit of a fix:

https://github.com/metaeducation/ren-c/commit/6dfe294be4c5663f9d5de0e2dd87d678f30ba529

Though bear in mind that SOURCE has never really been retooled for ADAPTs, ENCLOSEs, SPECIALIZEs etc.

So it really is best to go to the place in the source where things are defined.  I'd like us to make it easier to get at that information (file/line #) which we actually do have (!)
