### ISSUE TITLE
ODBC connection fails on Windows

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#1138]
>> dbase: open odbc://foo
** Script Error: Failure on bad value (no additional info): henv
** Where: poke open-connection  open console
** Near: [*** make object! [
    henv: '
    hdbc: '
    statements: ...
** Line: 92

**Comment by hostilefork** [comment]
Resolved by: https://github.com/metaeducation/ren-c/commit/a623c12b1b3b41fff6db36409f082f433cc17f25
