### ISSUE TITLE
Print Binary converts high byte values to UTF-8 encoded characters

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#118]
Per issue #115, Ren/C can now print binary. However when printing a binary with high values, each value is printed as a Unicode character corresponding to that bytes value encoded as UTF-8.

For example, the outcome of:

    print #{C3}  ; 169

is:

    #{C2A2}  ; UTF-8 "©"

Expected result would be:

    #{C3}

Extra weirdness ensues:

    >> print #{DECAFBAD 0A}
    ÞÊû­
    >> print to string! #{DECAFBAD 0A}
    ߊ�­

    >>

**Comment by hostilefork** [comment]
Why aren't simple things ever simple?  Darn it.

Thank you for trying the feature concept.  I will look at it.

**Comment by hostilefork** [comment]
Should have looked to see what Prin_OS_String did with single bytes... duh, it encodes them.  :-)  See if this takes care of the problem:

https://github.com/metaeducation/ren-c/commit/553150fc7902733bbbbb0082dd414af6b2e0b3b8

**Comment by rgchris** [comment]
Seems to do the trick!
