### ISSUE TITLE
Getting/Setting File Permissions

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#119]
Rebol 2 permitted fine-grained manipulation using **set-modes %some-file [owner-read: group-read: ...]** and slightly less precise control with **write/allow**. Rebol 3 [nominally has **write/allow** in the box](http://www.rebol.com/r3/docs/concepts/ports-permissions.html) but seems to lack efficacy.

While the **write/allow** argument is a somewhat blank box that could include a file permissions dialect, changing permissions is not always tied to a write. What would be the natural way to introduce file permissions control?

**Comment by rgchris** [comment]
[Getting/Setting File Permissions in Rebol 3](http://stackoverflow.com/questions/17039743/getting-setting-file-permissions-from-rebol)

**Comment by hostilefork** [comment]
Hey, I see what you did there.

This isn't Ren/C specific is it?  :-)

**Comment by rgchris** [comment]
I suppose not : (
Will hit CureCode in anticipation of the migration...

**Comment by hostilefork** [comment]
Might not want to do that... if the scrape is done and they don't want to scrape again!  Just saying after all the work and wait, it would be silly to give up and make these Ren/C issues!

Give it a few more days, I think it will happen...  :-)
