### ISSUE TITLE
Unbalanced Stack Trap with unpaired set-word! in header

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-c#156]
with the code:

    load "Rebol [a:]"

The following error occurs:

    ** PROBE_MSG("UNBALANCED STACK TRAP!!!") ../src/core/c-do.c:585
    [:hdr system/standard/header]

with a popup:

	---------------------------
	Rebol Internal Error
	---------------------------
	If you need to file a bug in the issue tracker, please give thorough
	details on how to reproduce the problem:

	    http://github.com/rebol/rebol-issues/issues

	Include the following information in the report:

	C Source File ../src/core/c-do.c, Line 586
	** Internal error: RE_MISC error (if actually happens, add to %errors.r) 
    ** Where: construct attempt not case load-header either set case load ** Near: :hdr system/standard/header

**Comment by hostilefork** [comment]
Sorry to have missed this issue.  I don't know why I didn't see it come in.

Trivial to fix, done!

https://github.com/metaeducation/ren-c/commit/ec36cbe626dc4f00d0353b09475f089a79b39934

**Comment by kealist** [comment]
No worries.  We talked about it in chat at the time I saw it, but thanks for fixing it.  I will try to not run unfinished old scripts with weird headers in the future though.
