### ISSUE TITLE
clean-path system/options/script

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#183]
system/options/script gives path of script *relative to system/options/path* but clean-path expand it *relative to system/options/current-path*. If I run `./r3 ../src/tests/test.r`, and test.r contains `print clean-path system/options/script`, I get `<...>ren-c/src/src/tests/test.r`, different from true path of script

**Comment by hostilefork** [comment]
Confirmed... do you have an idea of what to do about it?

**Comment by giuliolunati** [comment]
atm system/options contains 3 paths: home (where r3 executable is), path (from where r3 is launched), current-path (where script is). IMHO need renaming, and all files must refer to same path (I prefer system/options/path, aka cwd)

**Comment by hostilefork** [comment]
No pressure on this, but I'm trying to make sure we move to where the issues in Ren-C (at least) are kept cleaned out... (we only need one giant heap of perpetual issues, maximum!)

So I'm hoping we can decide what to do with this.  Is this a "new to Ren-C issue" or is it also a R3-Alpha issue?  You don't have to fix or resolve it, but if it's not on the "fix soon" radar I'd like it to go over to the Rebol issues where other people will (perhaps) get motivated to start looking through and tagging and worrying about things...

Your decision is thus if you have a good and correct plan, and it's important, and you want to do it... or if you want to raise it as a question in [rebol-issues](https://github.com/rebol/rebol-issues/issues) and leave it at that for now...

**Comment by hostilefork** [comment]
Migrated to rebol-issues:

https://github.com/rebol/rebol-issues/issues/2266
