### ISSUE TITLE
write command returns a port

### ISSUE THREAD

**Issue by gregit** [metaeducation/ren-c#188]
This is not a major issue, but not sure this is an expected behavior:
```
>> write %foo.txt "writing a text file"
== make port! [
    spec: make object! [
        title: "File Access"
        scheme: 'file
        ref: %foo.txt
        path: none
    ]
    scheme: make object! [
        name: 'file
        title: "File Access"
        spec: none
        info: make object! [
            name: none
            size: none
            date: none
            type: none
        ]
        actor: make native! [[port!]]
        awake: none
        init: make function! [[port /local path return:][
            comment {b...

>>
```

```
>> ? write
USAGE:
        WRITE destination data /part limit /seek index /append /allow access /lines

DESCRIPTION:
        Writes to a file, URL, or port - auto-converts text strings.
        WRITE is an action value.
```

**Comment by hostilefork** [comment]
It's not a new behavior, merely a "noisier" response in the console... in R3-Alpha:

    >> type? write %foo.txt "writing a text file"
    == port!

For things like ports and function definitions, the R3-Alpha console assumed you didn't want to see them.  Ren-C assumes you do.  There's probably a happy medium of showing you a small summary and then being able to query the last result for more information if you like.

In fact, I was just thinking about such a historical mechanism:

    >> history [buffer 5]

    >> 1 + 2
    == 3

    >> 4 + 5
    == 9

    >> history 2
    == 4 + 5

    >> history/result 2
    == 9

Something along those lines.  It might even be interesting to get it more fine-grained to where it wasn't just remembering command lines, but you could track individual evaluations.

    >> history [evals 100]

    >> 1 + 2 3 + 4 print history/eval 1 print history/eval 4
    7
    3

Or however many evaluations it all adds up to.  :-)

**Comment by gregit** [comment]
Thanks for the detailed explanation.
