### ISSUE TITLE
HELP on user-defined function crashes (asserts)

### ISSUE THREAD

**Issue by earl** [metaeducation/ren-c#191]
```
>> foo: func [] []
== make function! ...

>> help foo
USAGE:
	FOO 
r3: ../src/core/n-data.c:1251: VAL_TYPE_Debug: Assertion `((v)->header.all % 2 == 1)' failed.
Aborted (core dumped)
```

**Comment by hostilefork** [comment]
Looks like it couldn't hurt to have a HELP test that at least tests that help doesn't crash (though it would print output which I guess the tests currently don't do...!)  Perhaps you have an opinion on that.

There will be these popping up for a while given that END! is no longer a type, but code almost always rewrites better to obey the change.  As in this case:

https://github.com/metaeducation/ren-c/commit/70d11e258eebf25848f3cf98f2f619865e9f1e9c

Ever-open questions like *"should it be copying the sequence at the head, or at the same offset as the stored value, or should the stored value have chopped off any leading offset..."* deliberately not messed with in this modificaiton.
