### ISSUE TITLE
parse "" [to undefined-word]

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#201]
src/core/u-parse.c:658: Parse_To: assertion "FALSE" failed

**Comment by hostilefork** [comment]
Proof that the asserts are good things!  That was a case I looked at which [didn't look right to me](https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/u-parse.c#L513) at some point and threw in an assert to follow up on it later.  I guess later is now...

In R3-Alpha:

    >> parse "" [undefined-word] 
    ** Script error: PARSE - invalid rule or usage of rule: undefined-word

    >> parse "" [to undefined-word]
    == false

    >> parse "" [to append]
    == false

What is happening is that PARSE uses [a routine called Get_Parse_Value()](https://github.com/metaeducation/ren-c/blob/d764a00b6973187c89ddfa8b83c63501e9ff1c1f/src/core/u-parse.c#L141) to fetch a word...then it passes that to Parse_To.  It so happens that `undefined-word` does exist, in a GET_VAR sense.  It is bound into the user context, and it is unset.

A word must be bound somewhere to be read or written.  The REPL will bind everything into the user context.  So what causes the error when you try to read undefined word is not that it isn't bound, it's that the evaluator doesn't like unsets when it fetches a word:

    >> bind? second [to undefined-word]
    == make object! [
        system: make object! [
            ...
    ]

But this is PARSE and not the evaluator, so the error-on-unset isn't there.  Fix is to put an error on retrieving unset into `Get_Parse_Value()`:

https://github.com/metaeducation/ren-c/commit/d16f1eddb1e99e0fb09e4b465bcab6de54ef57b0

Then that still leaves problems for cases like `parse "" [to $20]`, which should complain in some way (but not assert).  That error is added here:

https://github.com/metaeducation/ren-c/commit/bcc2cd985f6c587f9b29c89ab8037004a930a9eb

Hopefully we can get in there and do a big cleanup of %u-parse.c at some point!  There are new features to be added, and it has gotten much easier to work safely with the fundamental constructs (I believe!)
