### ISSUE TITLE
assert on ren-c startup on 64 bit Linux -> SIGABRT

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#208]
I get the following assert failure on a freshly compiled ren-c on 64 bit Linux (manjaro).

% r3
r3: ../src/core/m-stacks.c:269: Push_Ended_Trash_Chunk: Assertion `(((!((&chunk->values[num_values])->header.all & 0x02) || ((((&chunk->values[num_values])->header.all & 0xFC) >> 2) != REB_TRASH || ((((&chunk->values[num_values]))->header.all & (1 << ((EXT_TRASH_SAFE) + 16))) ? TRUE : FALSE) )) ? (void) (0) : __assert_fail ("!((&chunk->values[num_values])->header.all & 0x02) || ((((&chunk->values[num_values])->header.all & 0xFC) >> 2) != REB_TRASH || ((((&chunk->values[num_values]))->header.all & (1 << ((EXT_TRASH_SAFE) + 16))) ? TRUE : FALSE) )", "../src/core/m-stacks.c", 269, __PRETTY_FUNCTION__)), (&chunk->values[num_values])->header.all % 2 == 0)' failed.
fish: “r3” terminated by signal SIGABRT (Abort)

**Comment by hostilefork** [comment]
That's... unfortunate. :-/

What the assertion relates to is the implicit termination trick (a new trick) that takes advantage of the idea that "memory addresses are always even".  Or at least, that's one of the things going on there.  You see the `header.all % 2 == 0` and it relates to that--it's a sanity check on the trick.  The expectation is that the way that the structure lays out implicitly terminates an array with a pointer.

I am going to need a reproducing environment for that, because [all the builds are green here](https://travis-ci.org/metaeducation/ren-c).  There must be something different about your system.  :-(  I doubt it's that your pointers are odd, it's probably something else.  Might you run Valgrind on it and see if it gets a trip earlier than that?

**Comment by hostilefork** [comment]
Please [merge up with this commit (it's on master)](https://github.com/metaeducation/ren-c/commit/19b5c3b16172d75ac0317396a19acfb0f7cad4ea) and post the report that comes back on the issue when you get a moment. Thanks!

**Comment by rgchris** [comment]
```
CONGRATULATIONS!  You repro'd issue #208, #211
    https://github.com/metaeducation/ren-c/issues/208
    https://github.com/metaeducation/ren-c/issues/211

chunker 0x9e330dc sizeof 4
    next (nil) @ 0x9e330dc
    payload @ 0x9e330e0

chunk 0x9e330ec sizeof 4
    prev 0x9e330e0 @ 0x9e330ec
    left 1956 @ 0x9e330f0
    size 76 @ 0x9e330f4
    values @ 0x9e330f8
    values[num_values] @ 0x9e33138

next 0x9e33138 - sizeof 4
    prev 0x9e330ec @ 0x9e33138
    header.all 165884140

Trying end value write.  (Strict aliasing?  What's that?)

    prev 0xde @ 0x9e33138
    header.all 222

PLEASE SEND THIS REPORT TO THE CARTOON FORK NEAREST YOU.
```

**Comment by rgchris** [comment]
From the 32-bit version after pulling the above commit:

```
CONGRATULATIONS!  You repro'd issue #208, #211
    https://github.com/metaeducation/ren-c/issues/208
    https://github.com/metaeducation/ren-c/issues/211

chunker 0x87f30dc sizeof 4
    next (nil) @ 0x87f30dc
    payload @ 0x87f30e0

chunk 0x87f30ec sizeof 4
    prev 0x87f30e0 @ 0x87f30ec
    left 1956 @ 0x87f30f0
    size 76 @ 0x87f30f4
    values @ 0x87f30f8
    values[num_values] @ 0x87f3138

next 0x87f3138 - sizeof 4
    prev 0x87f30ec @ 0x87f3138
    header.all 142553324

Trying end value write.  (Strict aliasing?  What's that?)

    prev 0xde @ 0x87f3138
    header.all 222

PLEASE SEND THIS REPORT TO THE CARTOON FORK NEAREST YOU.
```

**Comment by hostilefork** [comment]
@IngoHohmann please try the above commit to see how it works for you.

@rgchris The debug dump [isn't in the version pushed](https://github.com/metaeducation/ren-c/commit/aee3ceb5530775d2f7cc49928583422daa33e6d0#diff-63e5c0c4f25350be6c822d83995f28caL276)... so you need to do a clean make and build.  :-/

In general if you're going to keep sync with a hand-edited makefile you'll have to find a way to automate `make prep` then `make clean` then `make`.  The actual technicalities of when you can get away with not-prepping or not-cleaning are beyond the scope of explanation here.

If you would like to see a better build system then by all means, see if you can take [build.reb](https://gist.github.com/earl/180d761ce5d27e411a6f) further and get it tested enough for use.  GNU make is *not* terribly hard to beat, and I wouldn't mind seeing it go.  I did test build.reb and had it work on Windows and Linux at one point, and I'd hoped earl would keep after it... he does talk about getting back to the make system someday, but... if anyone can make it happen sooner and better that's good by me!

**Comment by hostilefork** [comment]
@IngoHohmann There are now two corroborating reports that this has made the problem "go away"

https://github.com/metaeducation/ren-c/commit/07917fe7be717b460e9126130b5782826ecba43f

If you confirm that, we can consider it closed for now.  Be sure you're building with **-O2** in your makefile (and **make clean**, then **make**)
