### ISSUE TITLE
assertion failed in Transport_Actor with block arg

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#209]
It occurred to me that passing a block in D_ARG(2) to Transport_Actor I got an assertion failed at
https://github.com/metaeducation/ren-c/blob/045f5a7757191dd24ff21926876140e969ba49fa/src/core/p-net.c#L275 --> https://github.com/metaeducation/ren-c/blob/045f5a7757191dd24ff21926876140e969ba49fa/src/include/sys-series.h#L375
because spec is not a string.
I think better insert a clearer assertion above this point...

**Comment by hostilefork** [comment]
I was going to say this is going to be fixed in a pending commit (coming soon, I can't promise when...) but I think I will keep it open here to remind me to have you check to see how you like the "new" way.

(I think you will like it very much!)

**Comment by hostilefork** [comment]
When you get a chance, look to see if the erroring works here as you expect... 

The new [Apply_Only_Throws()](https://github.com/metaeducation/ren-c/blob/aa2f2cec26900ca5b0cc0e24f78f25c4c190b612/src/core/c-do.c#L2829) does a lot more, and the functions you see there are hopefully to be packaged up as "Ren-C" the C API...
