### ISSUE TITLE
CALL/INPUT breaks if the IN argument is empty

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#21]
CALL breaks if an empty string is passed as input:

    >> call/input "ls" ""
    ** Access error: external process failed: "Bad file descriptor"
    ** Where: call
    ** Near: call/input "ls" ""

Tested on 3.0.99.2.5

**Comment by asampal** [comment]
@rgchris, you should probably state the platform, as the behavior I get on Windows 64 bit, is different. Also, for a non-release build, it might be more precise to specify the SHA-1 of the repo at the last commit rather than the Rebol version.

**Comment by hostilefork** [comment]
In this case I know he's on mac and what he's building.  But yeah, in general... I guess we should set good examples even with implicit knowledge.

**Comment by rgchris** [comment]
I did—it's in the version number...

**Comment by hostilefork** [comment]
Believed fixed by:

https://github.com/metaeducation/ren-c/commit/b69dedf62e2ba6118c6874cb8a4cf788690a7c63
