### ISSUE TITLE
Start-up fails with assert on Windows

### ISSUE THREAD

**Issue by gregit** [metaeducation/ren-c#211]
I just built a fresh ren-c by downloading zip file from github today, compiling it using MinGW as I did earlier on a Windows 7 machine.
Start-up crashes with error:
```
Assertion failed: IS_END(&chunk->values[num_values]), file ../src/core/m-stacks.c, line 269
```

**Comment by hostilefork** [comment]
Interesting, you are now the second to report this... now on Windows (previously Linux, see #208).

The build farm is not reproducing it, and I'm not reproducing it, even though the configurations are the same.  What I'm going to do about this is that I'm going to make a diagnostic branch to spit out some more information to try and get to the bottom of it, so what you and/or ingo would do would be to pull that branch and build it and send me the report it puts out.

I'll make this branch today!

**Comment by hostilefork** [comment]
*(I should mention the temporary fix of course, "please revert to a version from an earlier date if you need to continue work"...)*  :-)

**Comment by gregit** [comment]
Sure, I will compile/run the diagnosis branch once available.

**Comment by kealist** [comment]
I think it was me who got this before because I had accidentally updated to 64 bit mingw when I had used 32 bit previously.    Not at my computer today so I can't confirm but that may be part of it iirc

**Comment by hostilefork** [comment]
Please [merge up with this commit (it's on master)](https://github.com/metaeducation/ren-c/commit/19b5c3b16172d75ac0317396a19acfb0f7cad4ea) and post the report that comes back on the issue when you get a moment. Thanks!

**Comment by gregit** [comment]
Tested OK, this solves the issue for me.

**Comment by gregit** [comment]
Just learn that nothing was fixed, only debug added. Closing this issue for now and will re-open it if necessary.

**Comment by gregit** [comment]
CONGRATULATIONS!  You repro'd issue #208, #211
    https://github.com/metaeducation/ren-c/issues/208
    https://github.com/metaeducation/ren-c/issues/211

chunker 024AC364 sizeof 4
    next 00000000 @ 024AC364
    payload @ 024AC368

chunk 024AC3A0 sizeof 4
    prev 000000DE @ 024AC3A0
    left 1944 @ 024AC3A4
    size 44 @ 024AC3A8
    values @ 024AC3AC
    values[num_values] @ 024AC3CC

next 024AC3CC - sizeof 4
    prev 024AC3A0 @ 024AC3CC
    header.all 38454176

Trying end value write.  (Strict aliasing?  What's that?)

    prev 000000DE @ 024AC3CC
    header.all 222

PLEASE SEND THIS REPORT TO THE CARTOON FORK NEAREST YOU.

**Comment by rgchris** [comment]
```
CONGRATULATIONS!  You repro'd issue #208, #211
    https://github.com/metaeducation/ren-c/issues/208
    https://github.com/metaeducation/ren-c/issues/211

chunker 0x9e330dc sizeof 4
    next (nil) @ 0x9e330dc
    payload @ 0x9e330e0

chunk 0x9e330ec sizeof 4
    prev 0x9e330e0 @ 0x9e330ec
    left 1956 @ 0x9e330f0
    size 76 @ 0x9e330f4
    values @ 0x9e330f8
    values[num_values] @ 0x9e33138

next 0x9e33138 - sizeof 4
    prev 0x9e330ec @ 0x9e33138
    header.all 165884140

Trying end value write.  (Strict aliasing?  What's that?)

    prev 0xde @ 0x9e33138
    header.all 222

PLEASE SEND THIS REPORT TO THE CARTOON FORK NEAREST YOU.
```

**Comment by hostilefork** [comment]
Ok @gregit... here's a try at a fix:

https://github.com/metaeducation/ren-c/commit/aee3ceb5530775d2f7cc49928583422daa33e6d0

Let me know if you notice any problems!

**Comment by gregit** [comment]
I patched with the 5 files listed, compiled, run, and still get the crash:
Assertion failed: IS_END(&chunk->values[num_values]), file ../src/core/m-stacks.c, line 281

**Comment by hostilefork** [comment]
Hm?  Which 5 lines to which do you refer?  (There are slightly more than 5 lines in the materially relevant part of the commit)  You mean to say that you moved fields in the structure, changed their types, changed the assignments to size both in the initialization and the push chunk, etc...?

**Comment by gregit** [comment]
5 files, not 5 lines. I followed the link above and found there are 5 files there, so I took those 5 (.h + .c).

**Comment by hostilefork** [comment]
Ah sorry.  It was an assert report... "file", "line", lots of numbers... small screen. :-)

Well, let's see what this patch does.  It writes the value both ways:

https://github.com/metaeducation/ren-c/commit/07917fe7be717b460e9126130b5782826ecba43f

**Comment by gregit** [comment]
I added this patch on top of the prior 5 files patches.
I don't reproduce the problem anymore, it doesn't crash.
Now, closing this issue.

**Comment by hostilefork** [comment]
If you wouldn't mind for the sake of curiosity one more test...

A question I have to keep this open, while we're here looking...is if just going by way of a proxied pure integer pointer would be enough.  I have a hard time getting my head around why it would make any difference, but here's a small diff in `%m-stacks.c`

        {
     -        REBVAL *secondary = cast(REBVAL*, &chunk->size);
     -        secondary->header.all = size;
     +       REBUPT *universal = &chunk->size;
              assert(size % 4 == 0);
     +        *universal = size;
          }
  
         {
     -        REBVAL *secondary = cast(REBVAL*, cast(REBYTE*, chunk) + size);
     -        secondary->header.all = 0;
     +       REBUPT *universal = &(cast(struct Reb_Chunk*, cast(REBYTE*, chunk) + size)->size);
     +       *universal = 0;
              assert(IS_END(&chunk->values[num_values]));
         }

**Comment by gregit** [comment]
I've only tested here with code updated as below. No crash at start-up, it works.
About the understanding, I would need more time to dive more in R3 code.
```
    {
        // !!! Test: see if writing the REBUPT through both a REBVAL* and
        // its chunk size forces read coherence.  Worst case scenario this
        // could be done at the `char` byte level and be "legitimate".  But
        // looking for something less awkward for source expedience, at
        // least for the present time..
        //
        //REBVAL *secondary = cast(REBVAL*, &chunk->size);
        //secondary->header.all = size;
	REBUPT *universal = &chunk->size;
        assert(size % 4 == 0);
        //chunk->size = size;
	*universal = size;
    }

    // Set size also in next element to 0, so it can serve as a terminator
    // for the data range of this until it gets its real size (if ever)
    {
        // !!! See note above RE: secondary
        //
        //REBVAL *secondary = cast(REBVAL*, cast(REBYTE*, chunk) + size);
        //secondary->header.all = 0;
	REBUPT *universal = &(cast(struct Reb_Chunk*, cast(REBYTE*, chunk) + size)->size);
	*universal = 0;
        //cast(struct Reb_Chunk*, cast(REBYTE*, chunk) + size)->size = 0;
        assert(IS_END(&chunk->values[num_values]));
    }
```

**Comment by hostilefork** [comment]
Okay, well I've gone ahead and gone for the lighter version that seems more based on a principle vs. brute force pushing the bits:

https://github.com/metaeducation/ren-c/commit/f9014ce2298aed45a638fa89c2a86077e0c38b17

So if that works for you let's go with it a while and hope we don't see another assert!  Thanks again...
