### ISSUE TITLE
Assertion in ../src/core/n-data.c:1444: VAL_SERIES_Ptr_Debug

### ISSUE THREAD

**Issue by earl** [metaeducation/ren-c#215]
Running [`build.reb`](https://gist.github.com/earl/180d761ce5d27e411a6f) with a vanilla Ren/C 64-bit Linux debug build from current master (d216e30639db3bbf3ea8017cc16f5904b846f857) triggers the following assertion:

> ../src/core/n-data.c:1444: VAL_SERIES_Ptr_Debug: Assertion `(VAL_TYPE_Debug((v), "../src/core/n-data.c", 1444) >= REB_BINARY && VAL_TYPE_Debug((v), "../src/core/n-data.c", 1444) <= REB_LIT_PATH) || ((VAL_TYPE_Debug((v), "../src/core/n-data.c", 1444)==REB_MAP) ? TRUE : FALSE) || ((VAL_TYPE_Debug((v), "../src/core/n-data.c", 1444)==REB_VECTOR) ? TRUE : FALSE) || ((VAL_TYPE_Debug((v), "../src/core/n-data.c", 1444)==REB_IMAGE) ? TRUE : FALSE)' failed.
> Aborted (core dumped)

**Comment by hostilefork** [comment]
Fixed here:

https://github.com/metaeducation/ren-c/commit/dd39dda0d6947ac6c44ef865b49dde627ba0d487

One of the old confusing type-unsafe things where the assumption that the "frame" series in the OBJECT! value lived at the same offset as the "series" of a SERIES! object... can't tell what's going on from the source with these, so it's a runtime check before you generally know.

Went ahead and took care of the next two small things and...!

    === BUILD SUCCEEDED!

**Comment by hostilefork** [comment]
Presuming this fixed it, let me know if not...
