### ISSUE TITLE
LS crashes

### ISSUE THREAD

**Issue by gregit** [metaeducation/ren-c#218]
Using today's fresh ren-c code, entering ls command makes it crashes:
```
>> ls
Assertion failed: s->uni_buf_len == SERIES_LEN(UNI_BUF), file ../src/core/c-error.c, line 157

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by hostilefork** [comment]
That's a mold stack issue... so I'd generally send that to Giulio :-) but... you're on Windows, and it doesn't repro on Linux...

So here's the fix:

https://github.com/metaeducation/ren-c/commit/61a11d1b3332c6f8417a26ad5bd881e1534d341e

*(Not much in the way of Windows users right now, so it's valuable for you to be using it and pointing out the things you hit!)*

**Comment by giuliolunati** [comment]
Thanks Brian!

**Comment by gregit** [comment]
It now works, this issue can be closed.
```
>> ls
makefile       makefile.boot  objs/          r3-make.exe    r3.exe
>>
```
