### ISSUE TITLE
Non-ASCII keys in maps

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#220]
m: map 8 m/("ỳ")
s-crc.c:226: Hash_Value: assertion SERIES_WIDE(((*VAL_SERIES_Ptr_Debug(val)))) == sizeof(REBYTE)" failed

**Comment by hostilefork** [comment]
This is likely very much related to what you were already looking at.  But let me know if you need any help with it...

**Comment by giuliolunati** [comment]
Solved in [that branch](https://github.com/giuliolunati/ren-c/tree/map-cased)... soon PR, then will close issue.

**Comment by hostilefork** [comment]
All solved?

**Comment by giuliolunati** [comment]
Crossing fingers,  yes.
Il 25/gen/2016 04:47, "Brian Dickens" <notifications@github.com> ha scritto:
