### ISSUE TITLE
backtrace in debugger fails with assertion on Linux (64 bit / 32 bit)

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#225]
>> for i 1 10 1 [if i = 5 [breakpoint] print i] 
1
2
3
4
** Breakpoint Hit (see BACKTRACE, DEBUG, and RESUME)

|1|>> backtrace
r3: ../src/core/n-system.c:382: Where_For_Call: Assertion `end >= start' failed.
fish: “r3” terminated by signal SIGABRT (Abort)

**Comment by hostilefork** [comment]
This is known--the debugger was broken during prefetch branch and is under repairs now.

If you want to test this feature in particular:

https://github.com/hostilefork/rebol/tree/unified-frame

However, the unified frame does not have CLOSURE! working completely, and some code will break.

**Comment by hostilefork** [comment]
Should be resolved in master now, new debug features in....
