### ISSUE TITLE
Crash when printing MAP!

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#249]
s-mold.c:877: Mold_Map: assertion "ANY_ARRAY(value)" failed

**Comment by hostilefork** [comment]
Yup... that should be a `MAP_PAIRLIST(VAL_MAP(value))`.

Fixed that and another mold-related case here:

https://github.com/metaeducation/ren-c/commit/133200bbd3d0a785a17a9ab3e10ce61b028bb51f

**Comment by giuliolunati** [comment]
Thank you HF, you're so fast! :-)
Il 31/mar/2016 01:51, "Brian Dickens" notifications@github.com ha scritto:
