### ISSUE TITLE
extern missing for OSX

### ISSUE THREAD

**Issue by mbk** [metaeducation/ren-c#26]
I.e. this commit needs a revert as temp workaround to get things compiling on OSX:

https://github.com/metaeducation/ren-c/commit/465a18079df1a3a6687e6484de371a2b4f51b99b

**Comment by hostilefork** [comment]
I put it in with a conditional and a comment.  So if you merge that it should work.  That also should give you a patch so Ren Garden works if you also pick up this commit from Ren/C++:

https://github.com/metaeducation/ren-cpp/commit/b90e3f631ea3c3b6f0c2e0ca4d911705924d750d
