### ISSUE TITLE
assertion error when copying map

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#262]
`copy map []`
gives
`t-map.c:381: Append_Map: assertion "ANY_ARRAY(any_array)" failed`

**Comment by hostilefork** [comment]
This is another one of those things where it notices VAL_ARRAY_XXX doesn't have an array, but a MAP!.  Which is good to know.  :-)

Fixed here:

https://github.com/metaeducation/ren-c/commit/5ff7098366faf14e8f7525141b5fe3de8ca9dc52

Notice that it's now ok. to do initializers to variables in the middle of code.  This puts the initialization and the declaration together.  Please do this in any new code, it makes it cleaner...

Thanks for the report!

**Comment by giuliolunati** [comment]
Thanks for fixing it! (You're so fast :-)
Il 16/giu/2016 19:29, "Brian Dickens" notifications@github.com ha scritto:
