### ISSUE TITLE
assertion error when probing map

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#263]
`a: map[] a/1: a probe a`
>> f-blocks.c:377: Find_Same_Array: assertion "ANY_ARRAY(other)" failed

**Comment by hostilefork** [comment]
This is another case of the same assert, trying to catch cases where someone isn't aware that they are calling VAL_ARRAY on something that's a map (which also makes it hard to switch out the way maps work...)  They're not too hard to fix up if you run into another one!  :-)

Fixed here:

https://github.com/metaeducation/ren-c/commit/18b169582aa8506ef2d1c820df01f3c9a3edd71f
