### ISSUE TITLE
64 Bit Linux startup problem (gcc 6.1.1)

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#281]
SER_AT_RAW asked 16 on width=0

*** Panic_Series() in ../src/include/sys-series.h at line 191
Likely freed during evaluator tick: -872415229
ASAN:DEADLYSIGNAL
=================================================================
==29322==ERROR: AddressSanitizer: SEGV on unknown address 0x000002ec (pc 0x5675a08b bp 0x1ff3ace0 sp 0xff9d6680 T0)
    #0 0x5675a08a in Panic_Series_Debug ../src/core/m-series.c:550
    #1 0x569185fe in SER_AT_RAW ../src/include/sys-series.h:191
    #2 0x569185fe in Do_Vararg_Op_Core ../src/core/t-varargs.c:181
    #3 0x56914e05 in Do_Vararg_Op_Core ../src/core/t-varargs.c:141
    #4 0x5691a99f in Do_Vararg_Op_May_Throw ../src/core/t-varargs.c:388
    #5 0x5691c617 in T_Varargs ../src/core/t-varargs.c:489
    #6 0x5669479b in Action_Dispatcher ../src/core/c-function.c:1441
    #7 0x5665eb10 in Do_Core ../src/core/c-eval.c:1050
    #8 0x566629f8 in DO_NEXT_REFETCH_MAY_THROW ../src/include/sys-do.h:547
    #9 0x566629f8 in Do_Core ../src/core/c-eval.c:817
    #10 0x567a2c5a in Do_Array_At_Core ../src/include/sys-do.h:686
    #11 0x567b1eac in Do_At_Throws ../src/include/sys-do.h:1035
    #12 0x567b1eac in DO_VAL_ARRAY_AT_THROWS ../src/include/sys-do.h:1055
    #13 0x567b1eac in N_while ../src/core/n-loop.c:1163
    #14 0x5665eb10 in Do_Core ../src/core/c-eval.c:1050
    #15 0x56682702 in Do_Array_At_Core ../src/include/sys-do.h:686
    #16 0x56682b43 in Do_At_Throws ../src/include/sys-do.h:1035
    #17 0x56682b43 in Plain_Dispatcher ../src/core/c-function.c:1462
    #18 0x5665eb10 in Do_Core ../src/core/c-eval.c:1050
    #19 0x56622777 in Do_Array_At_Core ../src/include/sys-do.h:686
    #20 0x56622777 in Do_At_Throws ../src/include/sys-do.h:1035
    #21 0x56622777 in Do_Global_Block ../src/core/b-init.c:259
    #22 0x56631384 in Init_Core ../src/core/b-init.c:1619
    #23 0x56613b9c in RL_Init ../src/core/a-lib.c:131
    #24 0x569de949 in Host_Start_Exiting ../src/os/host-main.c:465
    #25 0x56611fa0 in main ../src/os/host-main.c:1055
    #26 0xf6f30535 in __libc_start_main (/usr/lib32/libc.so.6+0x18535)
    #27 0x56612f4c  (/home/ianus/Data/_Prog/Src/_rebol/ren-c/make/r3+0x53f4c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/core/m-series.c:550 in Panic_Series_Debug
==29322==ABORTING

**Comment by hostilefork** [comment]
Presumed addressed by https://github.com/metaeducation/ren-c/commit/73ef7bd03adf7c25f7ca67bae74896d6c6352114

http://chat.stackoverflow.com/transcript/message/31692487#31692487
