### ISSUE TITLE
query %/ => blank!

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#287]
I suggest this change in p-dir.c, line 140:

        if (policy & REMOVE_TAIL_SLASH && len > 1) {

**Comment by hostilefork** [comment]
Ok, changed!

https://github.com/metaeducation/ren-c/commit/d6d17e5ea896f6576cb5641c1ab9cf3a048c36fd

_(I warned I would be slow for a while...)_ :-)
