### ISSUE TITLE
Error using list-dir

### ISSUE THREAD

**Issue by johnk-** [metaeducation/ren-c#291]
Error using `list-dir`
```rebol
>> list-dir
r3             makefile.boot  makefile       objs/          CMakeLists.txt
r3-make
** Script error: list-dir must return value (use PROC or RETURN: <opt>)
```

**Comment by hostilefork** [comment]
Should be taken care of in https://github.com/metaeducation/ren-c/commit/82c0bf6a84942b518feae037d19b3e62f59ba8cc

These are pretty easy to resolve...so really the question is whether the benefit for new users going forward is there for enforcing it as a default.  I think so, but would be good to get more opinions...
