### ISSUE TITLE
assertion error in find/last "" char

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#292]
find/last "" #"."
terminate with:

        ./src/core/s-find.c:508: Find_Str_Char: assertion "index_orig <= SER_LEN(series)" failed

**Comment by hostilefork** [comment]
Believed to be addressed by:

https://github.com/metaeducation/ren-c/commit/6ee458331521b8d8b7db325d89ed0d6a4fe8fef0
