### ISSUE TITLE
segfault in poke vector!

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#317]
doing

        a: make vector! [decimal! 32 3]
        poke a 1 0.0

causes segfault

**Comment by giuliolunati** [comment]
No segfault in debug version. Instead assertion:

```
    sys-bind.h:453: COPY_VALUE: assertion "!IS_END(src)" failed
```

**Comment by giuliolunati** [comment]
Found bug, soon PR

**Comment by hostilefork** [comment]
This should resolve the issue with VECTOR! (which just seemed over-aggressive in reporting an error) and also gets rid of the broken Pick_Path() routine, which was unnecessarily tied into the details of path processing and error reporting _(and thus, got it wrong)_:

https://github.com/metaeducation/ren-c/commit/076c6f989f2b56b6c6afdd249b57bc32b291f203
