### ISSUE TITLE
tighten fails assertion

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#324]
`a: func [x y] [lib/add x y]  |  +: enfix tighten :a | 0 + 0`

causes

`src/include/sys-frame.h:453: Underlying_Function: assertion "underlying == underlying_check" fa;iled`

**Comment by hostilefork** [comment]
Ah, darn it.  That's right.  Can't actually re-use the body directly because it needs to be re-relativized to the new identity!  :-/

Hopefully this will take care of it:

https://github.com/metaeducation/ren-c/commit/150a55f68be7cb08b584b8c5cf7608fdf7d2948c
