### ISSUE TITLE
segfault in module

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#326]
`m: module [][f: func [] [x: 1 return 1]]        m/f`

causes segmentation fault

Note: 3 factors are necessary: in module + non-existing x var + return

**Comment by hostilefork** [comment]
Gr.  I see what's going on here, don't have a super quick fix right at this moment.  But... as it's an error, hopefully it's not blocking!

**Comment by giuliolunati** [comment]
Absolutely non blocking... raised from a bug in my Rebol code, but I wanted to keep track of it.

**Comment by hostilefork** [comment]
This particular case should be resolved, in that it gives an error now (assuming that was the desired outcome):

    >> m: module [][f: func [] [x: 1 return 1]] m/f
    ** Script Error: x word is not bound to a context
    ** Where: f _
    ** Near: ... x: 1 ?? return 1
    ** File: ../src/include/sys-bind.h
    ** Line: 488
