### ISSUE TITLE
"return or exit not in function" error occured after querying documents for more than once

### ISSUE THREAD

**Issue by dram** [metaeducation/ren-c#33]
Using current HEAD (7c0cdd7), Ren/C will throw "return or exit not in function" error after querying documents for more than once. Following is full transcript:

    >> ? foo
    No information on foo
    >> ? bar
    ** Throw error: return or exit not in function
    
    ** Note: use WHY? for more error information

**Comment by hostilefork** [comment]
Thank you for your report!  Nice to see people getting it and building it.  If you'd like to join in the discussion about what we're doing, visit our [chat room on StackOverflow](http://rebolsource.net/go/chat-faq)... if you don't have the 20 points needed to chat, they're pretty simple to get.)

Issue resolved in:

https://github.com/metaeducation/ren-c/commit/e9ec64212513e950d8f3f35eb8adf53f32b8d773

**Comment by dram** [comment]
Fix confirmed, thanks.

Thank you for your effort to move Rebol forward. I'll join in the chat when I find time to earn that 20 points.

**Comment by hostilefork** [comment]
If you [ask a question](http://stackoverflow.com/questions/ask) tagged with [rebol] or [red], it will be automatically posted to the chat room.  When people are new we try to do them a favor by upvoting them to 20 *(and editing the question if necessary to ensure its StackOverflow upvote-shape.)*

So don't be afraid give it a shot, shouldn't take but a second!

**Comment by dram** [comment]
Done. Thank you for your kind invitation.

**Comment by hostilefork** [comment]
I might try and be kind, but StackOverflow is known for its mercilessness...  So the best thing to do would be to delete your question if it doesn't follow their rules, and try again with a simple question about code you don't understand or something going wrong.  I'm sure it's not hard to find!  :-)

The "what you can ask" rules actually are relatively sane.  With questions like "what is a good library for doing X in language Y" you find the recommendation-giving process is not a fit.

What can be confusing is that there are some historical questions with useful information like "what's the best book for learning C++", where they have *"historical locks"* that say *"once this question was considered okay and people liked it, but we don't allow that kind of question here any more"*.  Like asking what your favorite programming cartoon is:

http://stackoverflow.com/questions/84556/whats-your-favorite-programmer-cartoon

At one point that got someone 800+ votes, and now it would be downvoted and deleted into oblivion.  Maybe StackOverflow lost its sense of humor somewhere along the line, but it's kind of a volume problem... lots of users doing that doesn't work.  :-/

In any case, don't give up!

**Comment by dram** [comment]
OK.

I recall that I have read several tutorial and book lists in SO before, so I think this topic is OK and do not look through SO's on-topic help carefully.

Thank you for your through explanation, and now another try.
