### ISSUE TITLE
Assertion failed  in Subparse_Throws: 

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#336]
rule: [
    object! :here (change/only here body-of first here) into rule
    | into rule
    ]
    parse reduce [object []] [here: rule]

produces

    ../src/core/u-parse.c:161: Subparse_Throws: assertion "IS_END(out)" failed

NOTE: prevents altjson.r to work in Ren/C

**Comment by hostilefork** [comment]
A friendly assert to help make sure bookkeeping is good.  Addressed here:

https://github.com/metaeducation/ren-c/commit/e2f23f6e58a7f9f4aceae60a211074d49253085f

Result of the expression is now FALSE (which is the result in R3-Alpha).
