### ISSUE TITLE
assertion failed when copying map!

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#342]
`copy make map! [ ]`
fails with
`sys-array.h:281: VAL_SPECIFIER: assertion "ANY_ARRAY(v)" failed`

**Comment by hostilefork** [comment]
Hopefully this addresses that:

https://github.com/metaeducation/ren-c/commit/c3b442cec5a9a14361344090039080a03d41b048

I noticed there was a bit of code left that was still checking for BAR! and treating it specially.  We decided that you should be able to use any *value* (not a void cell, but ANY-VALUE!) as a key or as a value in a map, and that would include BAR!.  So this takes that away too, if you happened to have any uses of it:

    names: make map! [_ "blank" | "bar"]
    select names _ ;-- gives you "blank" 
    select names '| ;-- gives you "bar"

That doesn't mean there couldn't be a kind of map creator function that used bars differently, but we should think about what is legal in the "fundamental type" and make sure it has full coverage.

**Comment by giuliolunati** [comment]
Ok, thanks HF!

Il 29/nov/2016 04:42, "Brian Dickens" <notifications@github.com> ha scritto:
