### ISSUE TITLE
REMOVE breaks out of loop in parse prematurely

### ISSUE THREAD

**Issue by zsx** [metaeducation/ren-c#349]
The code below is supposed to remove all spaces in the string, however, it only removed the first one.
```
a: "a ^-0, 1" 
wsp: charset { ^-^M^/} 
parse a [some [ remove wsp | skip]] 
probe a ; gives "a^-0, 1", while expecting "a0,1"
```

The reason it does so is that REMOVE after a match [doesn't advance the input](https://github.com/metaeducation/ren-c/blob/master/src/core/u-parse.c#L2119), and it was then treated as a failure, and thus it [breaks out of the loop](https://github.com/metaeducation/ren-c/blob/master/src/core/u-parse.c#L1997)

Removing the [break](https://github.com/metaeducation/ren-c/blob/master/src/core/u-parse.c#L1997) fixes this example, but not sure if it's a correct fix.

**Comment by hostilefork** [comment]
The **some** keyword in R3-Alpha mandated progress on the input.  We gather the idea was to bias the user experience to be more PARSE failures as opposed to PARSE infinite loops:

http://stackoverflow.com/questions/14352264/difference-between-rebol-2-and-rebol-3-when-mixing-some-in-parse-with-change

 **while** picks up the slack in a way, though not a drop-in replacement for SOME semantics.

    a: "a ^-0, 1"
    wsp: charset { ^-^M^/}
    parse a [while [remove wsp | skip]]
    probe a ; gives "a0,1"

There should be some decision on whether this no progress rule is helping vs. hurting... it may have been conceived before modifying parse rules (?)  Red does not seem to have chosen to go with it.

**Comment by hostilefork** [comment]
I'm going to close this here, since we have a big database of "Rebol Issues" to ask whether something that was in R3-Alpha of this nature should be or should not be:

https://github.com/rebol/rebol-issues/issues

If you want to reopen a discussion about getting rid of it or challenging it there, then maybe people will have thoughts to throw in.
