### ISSUE TITLE
Extend is broken

### ISSUE THREAD

**Issue by mbk** [metaeducation/ren-c#35]
```
>> a: construct []
== make object! [
]

>> extend a 'b 10
== 10

>> a
== make object! [
    b: 10
]
```

Works fine on Atronix build as per ^^.

On OSX:
```
>> a: construct []
== make object! [
]

>> extend a 'b 10
== 10

>> a
== make object! [
]
```

**Comment by hostilefork** [comment]
Cannot reproduce on OS/X Ren/C master (or stable-stack branch).  Tried OS/X and Linux, and get the same result as Atronix.  So... strange.

Under the hood extend is just append.  Can you try it also with **append a [b 10]** ?

**Comment by mbk** [comment]
Just build from tip, all good. closing.
