### ISSUE TITLE
Bug in system/options/args access

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#353]
`echo b: system/options/args probe b/2 > test.reb`
`./r3 test.reb a b`
`>> _`

(expected: `"b"`)

Bug introduced in commit 23d5d5c1

**Comment by hostilefork** [comment]
I saw a problem with that already, did this fix it?

https://github.com/metaeducation/ren-c/commit/3c8e6052a092156ac886ab6cf38df3e8c4293c54

**Comment by giuliolunati** [comment]
Unfortunately not. Bug is present also in 35eda7d78c6d6

**Comment by hostilefork** [comment]
Yup, okay I looked at it, it's because the length was inconsistent with the end marker...oops!

I stuck the fix into this commit:

https://github.com/metaeducation/ren-c/commit/9add431c39993672462c9cf49f412688174acb26

**Comment by giuliolunati** [comment]
Ok, it works! Thank you :-)
