### ISSUE TITLE
Blank key in map

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#357]
>> m: make map! [_ 0] m/_
    == _

Expected 0.

**Comment by hostilefork** [comment]
What made this take a while was that it raised a philosophical question about what blanks and voids mean in path selection.

The resolution was to make voids illegal to use in path selection, as well as illegal as the value to SELECT from a collection:

https://github.com/metaeducation/ren-c/pull/368

That  built on a change which made FUNCTION! a little less special in its path dispatch:

https://github.com/metaeducation/ren-c/commit/92308f7edf18a55ec10f33a97580007b86f734a2

Will merge this shortly.
