### ISSUE TITLE
TO-REBOL-FILE fails

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#360]
TO-REBOL-FILE converts a filestring with the host OS's native file notation to a Rebol file.

I get the following response on my system (2.102.0.2.5):

    >> to-rebol-file probe get-env "HOME"          
    "/Users/Chris"
    == %/sr/hi%00%00À%0C­Ê

**Comment by hostilefork** [comment]
Small mistake in a flag that happened during a simplification.  Fixed here:

https://github.com/metaeducation/ren-c/commit/2f7b0b5c7013d4447705ab7ea7d74b408924be65
