### ISSUE TITLE
MAKE VARARGS! and evaluation

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#361]
When passing a varargs-from-block to a variadic function, I wish were respected args specifications about quoting/evaluating

**Comment by giuliolunati** [comment]
make varargs! [[1 + 2] flag]
?
Or leave make as is, and add a function that enables evaluation, after
creation:
enable-evaluation varargs-from-block
?


Il 09/gen/2017 03:13, "Brian Dickens" <notifications@github.com> ha scritto:

**Comment by hostilefork** [comment]
This change will allow a VARARGS! to inherit whatever the parameter properties are it gets passed to:

https://github.com/metaeducation/ren-c/commit/2aac4ede19289c924d13bd9317f8c5fe9522582b

    >> f: func [x [any-value! <...>]] [take x]

    >> v: make varargs! [1 + 2]                
    == make varargs! [??? <= [...]]

    >> apply 'f [x: v]                         
    == 3

I think that the idea of TAKE/EVAL vs. TAKE is interesting, but I had already started this code.  Hopefully it will suffice until that can be rethought.

**Comment by giuliolunati** [comment]
I hit this compilation error:

m-gc.c: In function 'Queue_Mark_Opt_Value_Deep':
../src/core/m-gc.c:489:29: error: 'VARARGS_FLAG_NO_FRAME' undeclared

Help me please! :-)

Il 18/gen/2017 20:09, "Brian Dickens" <notifications@github.com> ha scritto:

This change will allow a VARARGS! to inherit whatever the parameter
properties are it gets passed to:

2aac4ed
<https://github.com/metaeducation/ren-c/commit/2aac4ede19289c924d13bd9317f8c5fe9522582b>

>> f: func [x [any-value! <...>]] [take x]

>> v: make varargs! [1 + 2]
== make varargs! [??? <= [...]]

>> apply 'f [x: v]
== 3

I think that the idea of TAKE/EVAL vs. TAKE is interesting, but I had
already started this code. Hopefully it will suffice until that can be
rethought.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metaeducation/ren-c/issues/361#issuecomment-273570222>,
or mute the thread

**Comment by hostilefork** [comment]
Oops.  Looks like %m-gc.c didn't get committed.  :-(  Added, hopefully that will help.

**Comment by giuliolunati** [comment]
uhmmm... tried your example:

f: func [x [any-value! <...>]] [take x]
v: make varargs! [1 + 2]
apply 'f [x: v]

but got 1 instead of 3 -- what's wrong?

(I'm at 5a006d)


Il 18/gen/2017 20:09, "Brian Dickens" <notifications@github.com> ha scritto:

This change will allow a VARARGS! to inherit whatever the parameter
properties are it gets passed to:

2aac4ed
<https://github.com/metaeducation/ren-c/commit/2aac4ede19289c924d13bd9317f8c5fe9522582b>

>> f: func [x [any-value! <...>]] [take x]

>> v: make varargs! [1 + 2]
== make varargs! [??? <= [...]]

>> apply 'f [x: v]
== 3

I think that the idea of TAKE/EVAL vs. TAKE is interesting, but I had
already started this code. Hopefully it will suffice until that can be
rethought.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metaeducation/ren-c/issues/361#issuecomment-273570222>,
or mute the thread

**Comment by hostilefork** [comment]
Okay, that had a problem [masked by uninitialized memory](https://github.com/metaeducation/ren-c/commit/c8b6418161614237206ba19a7560999b5b6fb318#diff-b4d15e102040ad5c85beadb91bc70998R151).  :-(

Take two:

https://github.com/metaeducation/ren-c/commit/c8b6418161614237206ba19a7560999b5b6fb318

**Comment by giuliolunati** [comment]
Works fine! Enough for now, thank you.
