### ISSUE TITLE
chain + return => shutdown

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#362]
f1: func [x] [return x] ;; <= without 'return all ok
    f2: func [x] [x]
    f3: chain [:f1 :f2]
    print f3 1

Dirty shutdown instead of printing 1

**Comment by hostilefork** [comment]
Some tricky things going on there.  This should at least work past that problem!

https://github.com/metaeducation/ren-c/commit/f745cf9e667e2239f0e24f831b4ed8205e6627e9
