### ISSUE TITLE
SWITCH Panic

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#370]
`t: 1 switch t [(t)]`

=>

END marker or garbage/trash in VAL_TYPE()
Pointer found in freed tail capacity of series
Kind=0
Containing series for value pointer found, panicking it:
managed series was likely created during evaluator tick: 25988
series guard didn't trigger ASAN/Valgrin. trap: either not a REBSER, or you're not running ASAN/Valgrind

**Comment by hostilefork** [comment]
Resolved by https://github.com/metaeducation/ren-c/commit/26eb8acfe2fc13965ab688a9f89ceefec79bfe6a
