### ISSUE TITLE
undefined reference to IS_PARAMLIST

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#373]
Hit linking error:

c-context.o: In function `Expand_Context_Keylist_Core':  undefined reference to `IS_PARAMLIST'

I'm on 78cdd134 -- native build on Android

**Comment by hostilefork** [comment]
Sorry that slipped by; I really need to figure out why I'm not getting Travis failure emails when a commit screws up!  :-/

Fixed: https://github.com/metaeducation/ren-c/commit/1ee4038dacda4b1ea1791f8cffbfffe8f756a531

**Comment by giuliolunati** [comment]
Well, however I test it regularly ;-)
