### ISSUE TITLE
Free_Series() error in foreach

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#374]
`foreach [:x] [ ] [ ]`

Trying to Free_Series() on a series managed by GC.
managed series was likely created during evaluator tick: 26065
series guard didn't trigger ASAN/Valgrind trap:
either not a REBSER, or you're not running ASAN/Valgrind

**Comment by hostilefork** [comment]
What did you want it to do?  *(It was on its way to tell you it didn't know what [:x] meant, and fails while delivering the error.)*

**Comment by hostilefork** [comment]
You might think something like this could work:

    word: 'x
    for-each :word [1 2 3] compose [
        print :word ;-- can't really work
        print x ;-- could work
        print (:word) ;-- compose could work
    ]

The reason `print :word` probably couldn't work is because that would require changing the x value in word to bind it.  It seems kind of ugly to be changing the binding of that x.

**Comment by giuliolunati** [comment]
that was an error found while trying to customize for-each -- only wanted
to keep trace of it

Il 28/gen/2017 04:11, "Brian Dickens" <notifications@github.com> ha scritto:

**Comment by hostilefork** [comment]
Ok, well this fixes the error!

https://github.com/metaeducation/ren-c/commit/6866c00fd6c3e098ed0cfc70528e21e1bdcf58a0

Maybe someday later we can figure out if get-words should have a meaning.
