### ISSUE TITLE
to-file _

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#375]
`to-file _` gets `%_`
I think that's wrong.
If a script expects filename in system/options/args/1 but you pass none, then `%_` is opened. :-/

**Comment by giuliolunati** [comment]
^--- grumble,  underscore after % is eaten...

**Comment by hostilefork** [comment]
It seems to me that system/options/args should probably be strings to start with, and that  `TO-FILE _` should probably be an error.

The way we were thinking a long time ago about scripts and arguments would be that you would specify the data type of your arguments, so it would look like a function spec basically.

    module [
        Title: "my module"
        Arguments: [
            filenames [file! <...>]
            /num-times
            count [integer!]
        ]
    ]

    for-each file filenames [
         loop count [print file]
    ]

**Comment by giuliolunati** [comment]
I agree: TO-FILE _ => error

**Comment by hostilefork** [comment]
New rule I picked is that TO BLANK! of anything (including a blank) is blank, but then you can't convert a blank to anything else:

https://github.com/metaeducation/ren-c/commit/4e261b4c654d0d81831d8c600e0c48260ee734f3
