### ISSUE TITLE
END marker or garbage/trash in VAL_TYPE() in parse

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#377]
```
>> o: make object! [a: 1]
== make object! [
    [self: a]
    [
        a: 1
    ]
]

>> parse "a" [o/a: skip]     
END marker or garbage/trash in VAL_TYPE()
REBVAL init on tick #28226 at ../src/core/c-path.c:195
Kind=50
No containing series for value...panicking to make stack dump:
managed series was likely created during evaluator tick: 0
series guard didn't trigger ASAN/Valgrind trap
:
either not a REBSER, or you're not running ASAN/Valgrind
```

**Comment by hostilefork** [comment]
There was actually something confusing going on there in the original R3-Alpha source for how SET-PATH! was handled, but really what should have happened is it just goes to the next rule.  So this resolves an old "what's supposed to happen here" comment:

https://github.com/metaeducation/ren-c/commit/89f2202b0cef4487f1b4256bb84f3fc0d71c0887
