### ISSUE TITLE
Unable to print error

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#382]
whenever hit an error in script, fails to print it -- only print
`managed series was likely created during evaluator tick ....`

**Comment by giuliolunati** [comment]
@e9d11ffde8cfff

**Comment by hostilefork** [comment]
At least one case fixed here:

https://github.com/metaeducation/ren-c/commit/881389645c6d15b83fbfd5bf8ec12116b85010ef

Take note of this attempt at migration of the UI's I/O code to usermode...

**Comment by giuliolunati** [comment]
Seems working.

**Comment by giuliolunati** [comment]
Error message lacks WHERE and NEAR

**Comment by hostilefork** [comment]
You might have noticed that [FAIL is now usermode](https://github.com/metaeducation/ren-c/blob/de0829c11c6d7a39494195db06ad3e9aad0fc566/src/mezz/base-funcs.r#L974
), depending only on SET-WHERE-OF-ERROR and DO of an ERROR! to accomplish what it needs from the system.

I still am not entirely sure of what the best time to put the origin information on an error is, given that it can be overridden by SET-WHERE-OF-ERROR.  It's getting a little more formalized!

https://github.com/metaeducation/ren-c/commit/de0829c11c6d7a39494195db06ad3e9aad0fc566

**Comment by giuliolunati** [comment]
This error is back @8494e7a

**Comment by giuliolunati** [comment]
put `1a` in script, then run it
Got:
`managed series was likely created during evaluator tick ....1`
Expected:
`** Syntax error: invalid "integer" -- "1a"`

Appears first in commit 927bbb
