### ISSUE TITLE
literal strings locked only in console

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#383]
locked? "a" returns true in console, false in script

**Comment by hostilefork** [comment]
Thanks for continuing to guinea pig these new behaviors!!

Not only are they new, but I want more and more of the code to be Rebol and not C, so it should be more obvious how to change things:

https://github.com/metaeducation/ren-c/commit/5fda0a715fad1266b3f2bba33c80aca66ea3d81a

**Comment by giuliolunati** [comment]
Glad to help! You're making very great job :-)
