### ISSUE TITLE
make prep fails @43231b2

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#385]
C-Style void arguments should b. foo(void) and not foo()
http://stackoverflow.com/questions/693788/c-void-arguments
** User error: "C++ no-arg prototype used instead of C style"

**Comment by hostilefork** [comment]
Are you able to push changes like this?  I trust you to do it if you notice mistakes, so you don't even have to file a report for it!

https://github.com/metaeducation/ren-c/commit/9754fdba275af57ab7bb3107ccb493d974be66d4

**Comment by giuliolunati** [comment]
you mean PR?

Il 10/feb/2017 12:26, "Brian Dickens" <notifications@github.com> ha scritto:

**Comment by hostilefork** [comment]
Use PRs for anything controversial, but you can just commit something obvious.

You should have write access to push commits.  If you don't, I can keep looking in GitHub settings to see how to give them to you.

**Comment by giuliolunati** [comment]
Oh, well, good.

Il 10/feb/2017 13:24, "Brian Dickens" <notifications@github.com> ha scritto:
