### ISSUE TITLE
load incorrect integer leads to assertion

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#389]
```
>> trap [load "2x"]
r3: ../src/include/sys-value.h:163: VAL_TYPE_Debug: Assertion `v->header.bits & NODE_FLAG_CELL' failed.
fish: “r3” terminated by signal SIGABRT (Abort)
```

**Comment by hostilefork** [comment]
That should be a bad PAIR! error, but instead it made a corrupt pair and tried to print it.

There wasn't much uniformity in how errors were handled in the R3-Alpha scanner...didn't seem to think it needed ["to check the return value of Scan_Pair"](https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/l-scan.c#L27)..and sort of snuck the erroring condition through another way.  I've made it more uniform.

Hopefully this will help:

https://github.com/metaeducation/ren-c/commit/5e7eb8ce103afe6a8908aec58b1577fdb3e61762
