### ISSUE TITLE
WHILE [] in a parse rule has trouble responding to Ctrl-C

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#394]
The Ctrl-C handling lives in Do_Core()...but empty block short-circuits ever calling Do_Core().  Hence tight loops can't break.

This issue does not arise in R3-Alpha because UNTIL [] requires a result, as opposed to treating void results of the loop as an "opt out".

**Comment by rgchris** [comment]
Another observation:

    parse "" [while []]

Takes time to respond to Ctrl-C whereas:

    parse "" [while [()]]

Does not.

**Comment by hostilefork** [comment]
UNTIL has been changed to no longer allow null loop results, due to some rethinking.  But the PARSE issue remains, so retitled.

**Comment by hostilefork** [comment]
This actually related to a pretty deep issue...which affects debugging too.  But I've addressed it with something of a general strategy:

https://github.com/metaeducation/ren-c/commit/23e4f5b4ac3fcdc3b26eb97148855070b41cde8c
