### ISSUE TITLE
Control-C quits to shell in Windows

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#395]
At either the ren-c prompt, or while script is running, and on windows 10, ctrl-C quits the interpreter.

**Comment by hostilefork** [comment]
You didn't mention any assertions or errors, so I'm not sure if your problem is the same one as this.  But Ctrl-C was crashing out on Linux:

https://github.com/metaeducation/ren-c/commit/23a15efe58f8026936a4c62c00896c63f9217a25

**Comment by hostilefork** [comment]
This appears to have come from a change made by earl some time ago, and I guess no one noticed Ctrl-C didn't work at all after that:

https://github.com/metaeducation/ren-c/commit/8a48efb32c85202ab79b6e9fea627bd79b87bccf

The test he is doing here seems nice in spirit, but in practice it really is more appropriate to have this controlled at a high-level by the host app...which has more knowledge than a somewhat kludgey test (which was broken) inside of a "device" for what the desired behavior should be.  (e.g. what if I'm redirecting the stdio but still want to break into the debugger, even so?)

I just moved it into the host.  Should resolve the problem.

https://github.com/metaeducation/ren-c/commit/b7e26781e95b6e59a16a2f9e25a5889c92fce4cd
