### ISSUE TITLE
PREP step fails @271c5b5

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#400]
r3-make -qs ../src/tools/make-boot-mod-header.r MODULES="Crypt"
** access error: script not found: %../src/tools/make-boot-mod-header.r

**Comment by giuliolunati** [comment]
Appears first in ef9975e

**Comment by hostilefork** [comment]
There were significant changes in this commit, did you rebuild the makefile e.g. with `make -f makefile.boot`?

**Comment by giuliolunati** [comment]
Oh, you're right! I did `make make` and failed, but `make -f makefile.boot` works.
