### ISSUE TITLE
Failing Mac OS X Build

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#405]
Building for OS X generates an error.

[osx-fail.txt](https://github.com/metaeducation/ren-c/files/834953/osx-fail.txt)

OS X 10.12.3
XCode 8.2.1
Rebol 3 Alpha

**Comment by hostilefork** [comment]
I mentioned this could be related to some of the nuances of OS X linking we've seen in the past, perhaps `-fno-common`?

http://chat.stackoverflow.com/transcript/message/20950811#20950811

http://stackoverflow.com/a/30071522/211160

**Comment by zsx** [comment]
Should be fixed by https://github.com/metaeducation/ren-c/commit/02ec1c0657151904f41cb15547097a9cc3cc63bd

**Comment by hostilefork** [comment]
Great... I notice that there is availability of a MacOS Travis:

https://docs.travis-ci.com/user/osx-ci-environment/

I do not know how easy or hard it is to add a build for that...presumably it could use mostly the same script?

**Comment by zsx** [comment]
>I do not know how easy or hard it is to add a build for that...presumably it could use mostly the same script?

It's not hard, I had it working with CMake when I was working on user natives. Unfortunately, I seem to have deleted the branch. :'(
