### ISSUE TITLE
Failed make -f makefile.boot

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#411]
`make -f makefile.boot OS_ID=0.4.4`
`./r3-make -qs ../src/tools/make-make.r 0.4.4`
`** Script error: join-of has no value`

**Comment by giuliolunati** [comment]
at 0cabc9f9e, on Linux

**Comment by giuliolunati** [comment]
r3-make is https://rebolsource.net/downloads/linux-x86/r3-g25033f8

**Comment by hostilefork** [comment]
I'm not getting this error... this is a problem that did exist in earlier builds, but shouldn't be happening now.  Can you do a bit of investigating into why JOIN-OF wouldn't be found (it's in r2r3-future.r if building with an R3-Alpha, and in Ren-C as a specialization of JOIN.)

**Comment by giuliolunati** [comment]
Do you can provide me your r3-make binary?

Il 13/mar/2017 23:14, "Brian Dickens" <notifications@github.com> ha scritto:

I'm not getting this error... this is a problem that did exist in earlier
builds, but shouldn't be happening now. Can you do a bit of investigating
into why JOIN-OF wouldn't be found (it's in r2r3-future.r if building with
an R3-Alpha, and in Ren-C as a specialization of JOIN.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metaeducation/ren-c/issues/411#issuecomment-286260612>,
or mute the thread

**Comment by hostilefork** [comment]
I'm using the 64-bit build from rebolsource.net, so it shouldn't be different... :-(

**Comment by giuliolunati** [comment]
Well it *is* different -- I tried x86 version, probably older commit than
your ...

Il 13/mar/2017 23:20, "Brian Dickens" <notifications@github.com> ha scritto:

**Comment by hostilefork** [comment]
The Travis builds do:

> wget http://www.rebol.com/r3/downloads/r3-a111-4-2.tar.gz

And the downloads of R3 from rebol.com are all x86.

If you read the build log on Travis, it is working, and then turns around and builds again with the r3-make it made:

https://travis-ci.org/metaeducation/ren-c/jobs/210712619#L295

**Comment by giuliolunati** [comment]
Ok solved -- there was a spurious rebol.r file in make directory :-(
