### ISSUE TITLE
Appending to lib on Windows build does not work

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#412]
The following code causes a crash on the Windows 64-bit CPP debug build:

    >> append lib [f: (:print)]

The same problem does not manifest on the linux build.

Reported by @gchiu

**Comment by zsx** [comment]
Just took a look at this, I believe it was caused by [this line](https://github.com/metaeducation/ren-c/blob/master/src/core/p-console.c#L84), where it initializes a binary from a OS string, which has a width of 2 on windows and violates the invariant "SER_WIDE(VAL_SER(v)) == 1" for a binary.

**Comment by hostilefork** [comment]
@zsx Ah, yup.  Seems it would be nice if Init_Binary checked that up front, wouldn't it?

Can that just be a string instead?
