### ISSUE TITLE
reword fails with edge case

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#415]
>> reword "$a" [a  "foo"] 
    == "foo"

under r3-g25033f8.exe

but now r3-de87088-debug-cpp.exe.  It seems a trailing character is needed.

    >> reword "$a" [a "foo"]
    == "$a"
    >> reword " $a" [a "foo"] 
    == " $a"
    >> reword " $a " [a "foo"]
    == " foo "
    >> reword "$a " [a "foo"] 
    == "foo "

**Comment by hostilefork** [comment]
Fixed, and the next time someone has a REWORD complaint, they should be able to fix it themselves now!

https://github.com/metaeducation/ren-c/commit/ef257519edba92467474fc5a1de017846b713cef
