### ISSUE TITLE
Error printing some errors

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#417]
`x/""`

=>

`IS_END() called on garbage`
`Rebol Internal Error`

**Comment by giuliolunati** [comment]
On Android -- not on Linux

**Comment by giuliolunati** [comment]
Complete message:

IS_END() called on garbage

Rebol Internal Error
If you need to file a bug in the issu. tracker, please give thorough details on how to reproduce the problem:
 
    http://github.com/rebol/rebol-issues/issues
 
Include the following information in the report:
 
C Source File ../src/core/c-error.c, Line 2960

**Comment by giuliolunati** [comment]
First bad commit:4d821d6e205c1c588735be73fff20f8ba30971b4
 
Author: Brian Dicken. <brian@hostilefork.com>

Date:   Wed Mar 8 20:12:06 2017 -0700
 
    Make cell preparation not just debug, simplify value macros

**Comment by hostilefork** [comment]
Yup, this is the same issue as:

https://github.com/metaeducation/ren-c/issues/413

I'm pondering what to do about it.  :-/
