### ISSUE TITLE
Missing rule for DO in PARSE dialect causes panic

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#419]
>> parse [(print now)] [do]
    18-Mar-2017/11:05:03+11:00
    VAL_TYPE() called on END marker
    Pointer found in freed tail capacity of series
    Kind=0
    Containing series for value pointer found, panicking it:
    managed series was likely created during evaluator tick: 83970

Ren-c build:

    **    Version:   2.102.0.3.1                                            **
    **    Platform:  Windows win32-x86                                      **
    **    Build:     17-Mar-2017/23:38:29                                   **

**Comment by hostilefork** [comment]
There's a bit of a technical question about whether it should run the DO and then give you an error, or if the error should be as early as possible.

This puts the error before the DO gets done:

https://github.com/metaeducation/ren-c/commit/1e9621ec71cc755f2bcb45a4bad014b2aa4d7b6f
