### ISSUE TITLE
Crash on naive use of THEN and ELSE

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#420]
This will cause a crash:

    if 1 then [2]

and this

    if 1 else [2]

ren-c build:

    **    Version:   2.102.0.3.1                                            **
    **    Platform:  Windows win32-x86                                      **
    **    Build:     17-Mar-2017/23:38:29                                   **

**Comment by hostilefork** [comment]
With the dawn of pre-lookahead and arbitrary enfix quoting...

https://github.com/metaeducation/ren-c/commit/24064e7b10414de1f19a9881d263f56be3a78a10

Comes a proper error for this:

    > if 1 then [2]
    ** Script error: then can't complete prior expression on left
