### ISSUE TITLE
ls/r and ls/l error

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#428]
Version: 2.102.0.3.40 Platform: Windows win32-x64 Build: 22-Mar-2017/5:49:03 Commit: ed8f62f

>> ls/l
.travis.yml         4250 2-Mar-2017/16:07:12.005+ file
** Script error: printf must return value (use PROC or RETURN: <opt>)
** Where: printf either for-each ls
** Near: printf [indent 16 -8 #" " 24 #" " 6] info ?? if all [r | dir...

>> ls/r
.travis.yml         4250 2-Mar-2017/16:07:12.005+ file
** Script error: printf must return value (use PROC or RETURN: <opt>)
** Where: printf either for-each ls
** Near: printf [indent 16 -8 #" " 24 #" " 6] info ?? if all [r | dir...

**Comment by hostilefork** [comment]
Very minor fix, thrown in with:

https://github.com/metaeducation/ren-c/commit/f66a47c2e98dcc3b46aa08b09ce904b6d20d8738
