### ISSUE TITLE
info? doesn't work on urls

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#430]
>> info? http://www.rebol.com/index.html
** Script error: --anonymous-- must return value (use PROC or RETURN: <opt>)
** Where: --anonymous-- query info?
** Near: ... make port! [
    [self: spec scheme actor awake state da...

info? uses query, but query on a url requires that the url be opened.  Suggest check if the target is a URL and do a HEAD command instead.

**Comment by hostilefork** [comment]
Resolved by https://github.com/metaeducation/ren-c/issues/431
