### ISSUE TITLE
echo fails with an assertion

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#435]
**    Version:   2.102.0.3.40                                           
**    Platform:  Windows win32-x64                                      
**    Build:     24-Mar-2017/19:08:06
system/commit is "0a833354fe57e43b02e2decd8306edf21ee7f60e"

>> echo %foo.txt
Assertion failed!

Program: C:\Users\Graham\rebol3\r3-0a83335-debug.exe
File: ../src/include/reb-device.h, Line 241

Expression: req->device == RDI_FILE

**Comment by hostilefork** [comment]
@zsx I don't really see what's going wrong here.  Is this about the size of the request, with that hook you put in to size them?

My leaning is to work through doing this with HIJACK and have less C code, so it would be a HIJACK of WRITE-STDOUT.  That would rip out all the Echo_XXX stuff.  Unfortunately, I have to work out some kinks with that.

So if you see an easy/short fix to this in the meantime, it might be helpful for Graham.

**Comment by hostilefork** [comment]
Rough draft of userspace ECHO (not working, but just to give the idea)

```
echo: procedure [
    "Copies console output to a file."
    
    target [file! blank!]
        {File to copy to, or BLANK! to cancel an existing redirection.}

    <has>
    old-write-stdout (_)
    saved-target
][
    ; We want to save the target so that it can be used beyond just this call
    ; (e.g. writes that happen after this function call ends still need to
    ; know where to write to).  So put it in a static variable.
    ;
    saved-target: target

    either saved-target [
        ;
        ; Capture the old WRITE-STDOUT, but don't provide a body yet (as we
        ; want to use the old implementation in the replacement, the HIJACK
        ; has to be done in two steps.)
        ;
        old-write-stdout: hijack 'write-stdout _

        ; Okay, now do the real HIJACK, which includes a call to the old write
        ;
        hijack 'write-stdout func [
            return: [<opt>]
            value [string! char! binary!]
            {Text to write, if a STRING! or CHAR! is converted to OS format}
        ][
            old-write-stdout value
                |
            write/append saved-target value
        ]
 
    ][
        if :old-write_stdout [
            ;
            ; !!! "UN-HIJACKING" is not really done properly yet, e.g. this
            ; will hijack the hijacking with its old self.  So instead of
            ; removing a layer, the hijack layer will persist.
            ;
            hijack 'write-stdout :old-write-stdout
        ]
    ]
]
```

**Comment by zsx** [comment]
I'll keep your suggestion in mind, and I just committed an easy fix.

**Comment by hostilefork** [comment]
Thanks...yeah, I got some way into my suggestion and there were bugs; HIJACK is experimental and definitely on the "please do not use it in production" list.  Figured you'd probably have a faster fix.

I've got it in a stash, and I'll keep it on my to-do list, because I like HIJACK and would like to see it firm up.
