### ISSUE TITLE
read dns:// not working on ip addresses

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#446]
**    Version:   2.102.0.3.40                                           **
**    Platform:  Windows win32-x64                                      **
**    Build:     1-Apr-2017/4:37:49                                     **
**    Commit:    fc1a43a169acb5c7b93f886a11453fe7d92f4e67               **

>> read dns://66.249.66.140
== 66.249.66.140

Rebol/view
>> read dns://66.249.66.140
== "crawl-66-249-66-140.googlebot.com"

**Comment by hostilefork** [comment]
Original R3 code was just plain wrong.  Believed fixed.

https://github.com/metaeducation/ren-c/commit/96121b735a0bc93eb0f0721409e3dba846c5eccb
