### ISSUE TITLE
invalid word => in lib context / error in help lib, after correction in pull-request #450

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#452]
```
>> help lib
LIB is an object of value:** Script error: if requires condition argument to not be void
** Where: for-each spec-of any if form-val if spaced if for-each --anonymous-- either collect dump-obj either --anonymous-- either collect unless help
** Near: if any [type: select types param] ?? [append/only spec type]...
```

This seems to be due to lib containing => which is an invalid word.

**Comment by hostilefork** [comment]
It actually was unrelated to the word =>, but a product of how ANY was interacting with a voiding select.

Motivated by this issue, I went ahead and did the behavior change we'd been discussing, which resolved it:

https://github.com/metaeducation/ren-c/commit/33b8f0200b72b966fbcb346a2283a8a4861b5d01
