### ISSUE TITLE
Error when reading https:// ** Crypt error: Unrecognized field in the key object: make typeset! [(pub-key) ...]

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#453]
```
>> read https://matrix.org
** Crypt error: Unrecognized field in the key object: make typeset! [(pub-key) ...]
** Where: dh-compute-key switch client-key-exchange subparse subparse subparse parse do-commands if switch --anonymous-- wake-up either until --anonymous-- wait until sync-op either --anonymous-- read
** Near: dh-compute-key ctx/dh-key ctx/dh-pub ??
```

happens with other https:// sites as well, e.g. https://zerotier.com
but not https://github.com

Website:   http://github.com/metaeducation/ren-c
Version:   2.102.0.4.40
Platform:  Linux libc-x64
Commit:    a388d051e8255f30096d3516075b81039fd3898a

I get the same error on a build from mid of february.

**Comment by hostilefork** [comment]
Fixed in:

https://github.com/zsx/r3/blob/ee00c3dd2295d42e4fec31b389ed841ea21172f0/src/os/host-core.c#L570

Thanks for the report!

**Comment by hostilefork** [comment]
Oops, that's the link to the original code location where the error was happening.

This is the fix:

https://github.com/metaeducation/ren-c/commit/a65de09a0e2e12adcdbb36044d1df6e8e620ff4e
