### ISSUE TITLE
protocol state error in prot-tls

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#455]
** user error: invalid protocol state
** Where: fail either update-proto-state unless parse-messages parse-response while tls-read-data switch --anonymous-- wake-up either until --anonymous-- wait while sync-op either --anonymous-- read do catch either either --anonymous-- do trap either --anonymous--
** Near: ... fail "invalid protocol state" ??

**    Version:   2.102.0.3.40                                           **
**    Platform:  Windows win32-x64                                      **
**    Build:     2-Apr-2017/22:54:25                                    **
**    Commit:    4fcacf2ef156d73a0d44449efef95503507256a6               **

**Comment by hostilefork** [comment]
https://stackoverflow.com/help/mcve

One of my baselines for this, in terms of taking responsibility or not, is if the Atronix build works.

So see what the request you're making is, and if the Atronix build can do it.  One thing you are probably aware of is the need to update the OpenSSL...and StackOverflow recently rolled out a security upgrade of some sort, I heard.  The more sites that do such upgrades, the more pressing it is to upgrade.

**Comment by hostilefork** [comment]
I've spent some time looking into the repro case that Graham has for this.  What it comes down to is a loop which does DELETE requests via WRITE to some HTTPS URLs.  Then, after that loop is finished, it tried to do a READ of a github HTTPS page.

It appeared that the READ was failing...when doing the READ in isolation worked fine.

But in actuality, it was something to do with pending requests in the event queue, that somehow were getting processed as part of that READ.  It was possible to see this by putting a WAIT before the read--and it would be the WAIT that would have a failure.  So it's something about the event loop having stale entries getting processed.

@zsx I'm not sure entirely what to expect here, but how would it be that a WAIT would be dispatching events after a **write** or a **read** of a URL, e.g. **`write https://wherever [DELETE ...]`**?  Shouldn't the event queue be empty after that is done?  Do you know a good way of testing to see why it wouldn't be?

I've asked Graham to see if he can make a simpler repro case, now that we know more about it.

**Comment by gchiu** [comment]
It may be relevant here that in prot-http, user events are created and these be the ones that are not being handled correctly.

**Comment by gchiu** [comment]
Ok, what seems to have been happening is that errors were being generated when the protocol was at the stage of parsing the headers dialect.  At this point the port was opened.  And then it would keep doing this as it was processing hundreds of files. Somehow this queued up events that were not being handled and that affected TLS.  Fixing the header dialect processing has caused the errors to go away.

**Comment by hostilefork** [comment]
This raises the issue of how failures inside the schemes/protocols need to have some kind of trapping or clean up; it seems like maybe the event model should be robust enough to kind of snapshot all the events that happened during a request that errored and be able to get rid of them.

But we kind of know ports are tricky, especially when you get in there writing your own code.  I'm going to consider this particular issue closed for the time being.
