### ISSUE TITLE
Assertion on startup sys-node.h:41: NOD: Assertion `n->header.bits & NODE_FLAG_VALID' failed.

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#458]
~/D/_/S/_/r/make> ./r3
r3: ../src/include/sys-node.h:41: NOD: Assertion `n->header.bits & NODE_FLAG_VALID' failed.
fish: “./r3” terminated by signal SIGABRT (Abort)

built from
0f7e550b3fb7bdbbdbb4b6e2f487d1c68a987b26

on Linux

**Comment by hostilefork** [comment]
Didn't show up for me in the same build config, but I think it's this:

https://github.com/metaeducation/ren-c/commit/7e955648d180f449213aba45aa5ea2a398724db8

See if that helps...

**Comment by IngoHohmann** [comment]
Yes, works again.
