### ISSUE TITLE
Assertion failed in m-pools.c

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#459]
../src/core/m-pools.c:519: Make_Node: assertion "node->header.bits == 0" failed
Aborted
@75fc5077
Looking for simple repro

**Comment by giuliolunati** [comment]
Repro:

 `m: make map! [ ] | repeat x 100 [m/:x: x]`

100: your mileage may vary -- with 10 I got:

    C Source File ../src/core/m-pools.c, Line 1942
    Rebol Internal Error
    If you need to file a bug in the issue tracker, please give thorough
    details on how to reproduce the problem:

    http://github.com/rebol/rebol-issues/issues

    Include the following information in the report:
    
    node does not belong to one of the pool's segments

**Comment by hostilefork** [comment]
Ah, mistake in ordering of flags w.r.t. SERIES_FLAG_POWER_OF_2...!

https://github.com/metaeducation/ren-c/commit/f3a135486fc51731f3d3696ae3f638c4688d6c22
