### ISSUE TITLE
Assertion failed in varargs.c:55 [blocking issue]

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#464]
f: func [:look [<...>]][first look]
    apply 'f [look: make varargs! []]

=>

../src/core/t-varargs.c:55:
Vararg_Op_If_No_Advance:
assertion "NOT_END(v)" failed

b24f1ce

**Comment by hostilefork** [comment]
The dangers of rewriting code.  But the happiness of asserts that point you to exactly what to do to fix it.  :-)

https://github.com/metaeducation/ren-c/commit/cb09b55370c4b1645f3b38c71e359ae5a796fad3

And your case is now a new test.  More tests, please!
