### ISSUE TITLE
dump-obj word is not bound to a context

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#467]
>> a: make object! [ b: 1]
== make object! [
    [self: b]
    [
        b: 1
    ]
]

>> dump a
** Script error: dump-obj word is not bound to a context
** Where: unspaced either dump-val delimit either either print case dump-one either dump
** Near: "make obect! [" | dump-obj ?? val | "]"

Occurs in both linux and windows on https://github.com/metaeducation/ren-c/commit/6cd80f9cf8951b534e86463d91f06a54cf95b407 and may have occurred earlier and may have been caused by https://github.com/metaeducation/ren-c/commit/45fbbdef174a5a79d8d6fc16fc51ee86d725c16d

**Comment by hostilefork** [comment]
@GrahamChiu looked at this, and based on what the error is, I'll self-assign figuring out what to do about it.

**Comment by hostilefork** [comment]
I moved DUMP out of %base, it seems the easiest solution...there's no particularly good reason for it to be in base.

https://github.com/metaeducation/ren-c/commit/080b9c650c0a03799c7c8981287e66ab4c5cec2e
