### ISSUE TITLE
IMPORT could look remotely?

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#476]
@draegtun [said](https://chat.stackoverflow.com/transcript/291?m=36743850#36743850)   : "I wouldn't want an import to look remotely unless I explicitly asked it to and/or configured it to."

**Comment by gchiu** [comment]
My thought is that the priority is for a script to run. If the local module path doesn't have the module I would want it to fetch it from a public vetted library of modules.

**Comment by giuliolunati** [comment]
1) When a module is self-contained all is clear:
`import <foo>` -> search remotely
`import <foo>` -> search locally

2) But what if the user calls `import <foo>` and `foo` module calls `import 'bar`?
if `bar` don't exists locally `foo` cannot run, else if user trusted it. On other hand one don't wants insert an `import <bar>` in `foo`, else it cannot work offline. Nor one wants maintain two versions of same module, local and remote...

**Comment by giuliolunati** [comment]
3. My proposal: `import 'bar` can search remotely only if a flag is on. When `import <foo>` starts that flag is stored and set on (because user trusts `foo` and thus all implied modules), so nested `import 'bar` can search remotely; then when `import <foo>` is done the flag is restored.

**Comment by hostilefork** [comment]
> "I wouldn't want an import to look remotely unless I explicitly asked it to and/or configured it to."
...
> Nor one wants maintain two versions of same module, local and remote...

These are both good points.

The only real experience I have in this kind of "security of code blobs over the net" thing is "sudo apt-get", and with Node.JS and how they go about versioning.  There is probably a lot to learn from the study of what they have gotten right and gotten wrong.  There are likely essays on the web written by people who have made proposals for improvements to NPM, or by those who have explained why they think another system is superior.

R3-Alpha did not really implement SECURE, which is a large piece of this puzzle.  :-(

**Comment by draegtun** [comment]
@giuliolunati - My gut feeling is that there should be just one way to find & load a module by module-name (namespace).  I think this is why having both `'foo` and `<foo>` is introducing problems :(

If we're able to append a remote path (URL!) to `system/options/module-paths` then this would allow `import 'bar` to look remotely if its unable to find it locally.

However by default I don't think it should add/search/allow URL! in `module-paths` without us flicking some switch...  perhaps a Rebol header specification or a command-line switch.  If we're only going to allow renclib (as remote library) in `module-paths` then it could even be something simple like `do <renclib>` to add/allow it.


@hostilefork - When we start thinking (worrying!) about versioning, dependency management & security then it all gets very complicated very quickly :(   

I do have good experience of the Perl CPAN tools & toolchain, so we certainly can learn from this.  Be nice to keep it simple & Rebolish though!

**Comment by giuliolunati** [comment]
@draegtun currently **system/options/module-paths** *accepts* remote directories: try set it to **[https://raw.githubusercontent.com/r3n/renclib/modules]** then **import 'html**

**Comment by giuliolunati** [comment]
@draegtun my POV is:

1) `import 'foo` and `import <foo>` must act similarly, but the 2nd enables remote looking after local one, while the 1st disable it.

2) remote looking may try before direct shortcuts in `rebol/locale/library` then remote directories in `system/optiond/module-paths`

**Comment by draegtun** [comment]
@giuliolunati 

I'd hoped that `module-paths` was implemented to work with remote paths so glad to hear it does!

But I'm not sure on the `import 'foo` and `import <foo>` duality :(    

Here's an idea which may work...  being a `<tag>` then why don't `import <foo>` look through `system/locale/library` for modules TAGGED with <foo> and load all of them?

So for eg. `renclib/usermodules.reb` could look like this..

        [
            [<html> <webserver>] https://raw.githubusercontent.com/r3n/giuliolunati.renclib/master/usr/lib/r3/html.reb

            [<rem> <webserver>] https://raw.githubusercontent.com/r3n/giuliolunati.renclib/master/usr/lib/r3/rem.reb

            [<webserver>] https://raw.githubusercontent.com/r3n/renclib/master/scripts/webserver.reb
        ]

With above `import <webserver>` would load all 3 modules above.  Whereas `import <html>` just loads `html.reb`.

Of course this requires a bit more effort setting up the `usermodules.reb` and the ordering of file maybe important (so for `<webserver>` it would need to load `<html>` & `<rem>` first).

But this looks a possible alternative to me?   What do you think?  And I'll be happy that `import <webserver>` is always remotely.... and if I don't like that I can always change `system/locale/library` to point to a local <tags> file :)

**Comment by giuliolunati** [comment]
Sounds good!

So, to recap:

1) `import 'foo` remains unchamged: search in `system/options/module-path` (also eventually remote folders) and import *first match.*

2) `import <foo>` search in the tagged list `system/locale/library` and import *all matches in order* (also eventually local files)

^---- @GrahamChiu what do you think?

**Comment by giuliolunati** [comment]
Got no more feedback.
So I think better to revert back previous behavior: `import 'foo` and `import <foo>` totally independent. :-/
