### ISSUE TITLE
command line errors are not fatal

### ISSUE THREAD

**Issue by meshpoint** [metaeducation/ren-c#48]
If there is an error in the command line, other options are still honoured. Suppose "test" is a file in the current directory that can possibly be interpreted as a REBOL script. We intend to run "script.r" as follows:

    $ r3 --debug test script.r
    This is the script %script.r
    Arguments: #[none]
    Debug options: [test]

but make a typo:

    $ r3 --dbug test script.r
    REBOL 3.0 A0 15-Aug-2015/9:18:58
    
    Command line usage:
    
    ...
    
    This is the script %test
    Arguments: ["script.r"]
    Debug options: #[none]

Instead of trying to execute %test the interpreter should discard any options and just display usage information.

**Comment by hostilefork** [comment]
It would be good to have an error message along with the usage information.  Perhaps the usage information coming first, and then the error...though I guess a survey of what is common best practice is the way to go.

*(Note: In trying to figure out what to do in terms of institutional knowledge, we haven't yet figured out what to do with all the old [CureCode tickets](http://curecode.org/rebol3/view-tickets.rsp).  A migration is [getting talked about](https://github.com/earl/r3-issues/blob/master/fetch-curecode.r), but when migrated they will probably not come here...but to a new repository e.g. github.com/rebol/rebol-issues.  Not that it's a problem to have some issues here, just mentioning that this is unlikely to be a long term location for general bug reports, design ideas, etc.)*

**Comment by meshpoint** [comment]
Here is a fix: 8ce61ab8c3127124b241a6b87858da256fa2f438.

@hostilefork As this fork aims to be a library, the command line options may be host-specific. So it should be a host responsibility to print command line usage errors. USAGE may output a host-supplied string.

**Comment by earl** [comment]
Fixed in d08fdc78fcc0bf483bd37a4cb1349d93253768dc.

**Comment by hostilefork** [comment]
@meshpoint - I don't know if the topic of what's going on with all this still interests you.  But on the off chance it does, I thought you might like to know that command line processing has been moved into userspace:

https://github.com/metaeducation/ren-c/blob/6d69673177c9cfc73f7e1b630199d86eecd187a0/src/os/host-start.r#L281

While slow and plodding as most Rebol things are...work does continue...including a build farm making executables for OS/X, Windows, and Linux.  Language features still evolving, with variadics and more sophisticated infix.  There's a recent uptick in general activity on the project.
