### ISSUE TITLE
url! and handling of special characters

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#483]
It is impossible to access urls with embedded !

see these access tests
```
curl http://localhost:8080/test:bla!blub
server log: 127.0.0.1 - - [28/Apr/2017:20:57:51 +0200] "GET /test:bla!blub HTTP/1.1" 404 30 - curl/7.53.1

>> read http://localhost:8080/test:bla!blub
server log: 127.0.0.1 - - [28/Apr/2017:20:56:49 +0200] "GET /test:bla HTTP/1.0" 404 30 - REBOL

curl http://localhost:8080/test:bla%21blub
server log: 127.0.0.1 - - [28/Apr/2017:21:16:30 +0200] "GET /test:bla!blub HTTP/1.1" 404 30 - curl/7.53.1

>> read http://localhost:8080/test:bla%21blub
127.0.0.1 - - [28/Apr/2017:21:11:03 +0200] "GET /test:bla HTTP/1.0" 404 30 - REBOL
```
I guess that curl url-encodes the #"!" when reading from the webpage.

Yes I'd rather not need this, but that's how the api is designed.

**Comment by zsx** [comment]
[Here](https://github.com/metaeducation/ren-c/blob/master/src/mezz/sys-ports.r#L80) is parse-url in Ren-C, and [here](http://www.ietf.org/rfc/rfc3986.txt) is the URI RFC. It looks like parse-url doesn't allow #"!" in the path while RFC 3986 does

**Comment by hostilefork** [comment]
It seems URLs need some rethinking in general, but is there an easy one-character patch to resolve @ingo's issue for now?

**Comment by zsx** [comment]
Maybe there is. @IngoHohmann  could you try adding the "!" to the string on [this line](https://github.com/metaeducation/ren-c/blob/master/src/mezz/sys-ports.r#L85) and see if it fixes the issue?

**Comment by hostilefork** [comment]
@IngoHohmann Is this resolved now?

**Comment by zsx** [comment]
I'm closing this because the URL in OP is now parsed correctly.
