### ISSUE TITLE
commit b1df8c079 breaks import 'foo

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#491]
`import 'foo` fails with

** Script error: invalid argument: _
** Where: lib-set apply either set import do catch either either --anonymous-- do trap either --anonymous--
** Near: ...

*Note:* this issue is severe for me.

**Comment by hostilefork** [comment]
https://github.com/metaeducation/ren-c/commit/29f1e3a5f513981bc952dd6a4e3496e0a266a6a4

**Comment by giuliolunati** [comment]
*Optime!*
