### ISSUE TITLE
Control-C at prompt after breaking out of ASK crashes

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#492]
>> ASK "OK?"
OK? <== control-C here
>> C Source File ../src/os/host-main.c, Line 1009 <== Control-C here
Series VARLIST detected.
...and that VARLIST is of an ERROR!...
** PROBE() tick 112873 ../src/core/d-crash.c:126
C Source File ../src/core/c-signal.c, Line 128
Rebol Internal Error

**Comment by hostilefork** [comment]
https://github.com/metaeducation/ren-c/commit/9aaa5394c0bd3262b6010e91bcad42d63786f43b
