### ISSUE TITLE
Parallel builds in Visual Studio based on CMake may not find %tmp-xxx files

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#494]
This has been an existing problem, but something about Visual Studio 2017 makes it worse.

Because the extension targets use %sys-core.h, all the make prep build products have to be ready before a build of those extensions starts.  However, parallelism leads them to go off on their own before the r3-core target is done.  With enough parallel targets, one of them is going to fail due to beating it to the punch.

It used to be that it would just work on the second build, but in Visual Studio 2017 the race condition comes up more often, where it tries to read the file while locked for writing by the make process.

I couldn't figure out how to disable parallel builds, and when I tried to add a dependency for the extensions on the r3-core target it complained about the cyclic dependency.  So it seems perhaps the "prep" step should be its own target, upon which all the others depend?

**Comment by hostilefork** [comment]
One thing that exists is `add_custom_target`:

http://stackoverflow.com/a/15973676/211160

It would not give a lot of hope for a future with incremental builds, but I've been skeptical of how well Rebol's technique of "scan-the-world-and-regenerate-headers" interacts with incrementality.

**Comment by hostilefork** [comment]
I tried:

    add_custom_target(
        prep ALL
        DEPENDS
            ${GENERATED_CORE_HEADER}
            ${GENERATED_CORE_SOURCE}
            ${EXT_OS_OUTPUT}
    )

And then I tried adding prep as a dependency of all targets, e.g.

     add_library(libr3_core_core OBJECT ${BOOT_HEADER} ${CORE_SOURCE} ${GENERATED_CORE_SOURCE} ${CORE_HEADER} ${GENERATED_CORE_HEADER})
     add_dependencies(libr3_core_core prep) // added prep here

Yet still, I wind up with it appearing to start building c source files before the prep has finished, and an error out of things like the `libr3_core_core` target claiming it can't find `tmp-error-funcs.h` (or similar), even though those are encompassed by the DEPENDS of prep.

I've not dealt with custom commands before, but if I'm understanding correctly the OUTPUT list says what the command produces, and anyone who DEPENDS on the items in the output will automatically trigger the custom command.  But I can't seem to get the targets to wait on prep to finish all the way.

It would be nice if we could push further on simplifying all of this.

**Comment by asampal** [comment]
@hostilefork can't the prep phase emit a marker file that subsequent stages can depend on?

**Comment by hostilefork** [comment]
@asampal Well that's what these files are supposed to be, it's supposed to be dependencies from one target which signal the other target to wait until those files are made.

What I'm seeing is that basically every target thinks it needs to run the prep command.  Each extension feels the need to basically run a make prep.  So in the build log I get each target talking over each other.

```
8>------ Build started: Project: r3-png, Configuration: Debug x64 ------
6>... Sys Context
6>... Natives and Bootstrap
6>232 natives
2>a-lib.c
7>Generating src/include/reb-types.h, src/include/tmp-bootdefs.h, src/include/tmp-sysobj.h, src/include/reb-evtypes.h, src/include/tmp-errnums.h, src/include/tmp-error-funcs.h, src/include/tmp-portmodes.h, src/include/tmp-sysctx.h, src/include/tmp-boot.h, src/core/tmp-boot-block.c, src/core/tmp-evaltypes.c, src/core/tmp-maketypes.c, src/core/tmp-comptypes.c
7>--- Make Boot : System Embedded Script ---
7>... Evaluation Maps
7>... Datatype Makers
7>... Datatype Comparison Functions
7>... Datatype Definitions
6>Compressed 192521 to 59210 bytes: 30 percent of original
7>... Boot Definitions
2>b-init.c
6>... Bootstrap Structure and Root Module
7>349 words + actions
7>... System Object
7>... Event Types
8>Generating src/include/reb-types.h, src/include/tmp-bootdefs.h, src/include/tmp-sysobj.h, src/include/reb-evtypes.h, src/include/tmp-errnums.h, src/include/tmp-error-funcs.h, src/include/tmp-portmodes.h, src/include/tmp-sysctx.h, src/include/tmp-boot.h, src/core/tmp-boot-block.c, src/core/tmp-evaltypes.c, src/core/tmp-maketypes.c, src/core/tmp-comptypes.c
7>... Error Structure and Constants
```
They're compiling, making prep, and overwriting files the others expect to find there.

Like I say, the problem's not new, it's just gotten worse.  It used to have some race condition and fail a build every other time, now it's failing every time.

**Comment by hostilefork** [comment]
@zsx I think from looking at this, the answer is that CMake shouldn't be guaranteeing the generation of files, and have the targets demanding them.  Instead, the generation process should always be run up front, but be sensitive to not overwrite files that are exactly the same as the previous generated file.

So basically, don't say files like `tmp-funcs.h` are OUTPUT by a custom command, then demanded by the targets.  Instead just have them as normal dependencies, so that if a change is detected they get rebuilt--as if they were source modified by the user.  Then use the technique in the article I mention above to make sure everyone allows the prep step to finish (no OUTPUTs listed) where it may or may not affect the dependent generated files.

Make sense?

**Comment by zsx** [comment]
@hostilefork what's your cmake version? I'm using 3.7.2, which can generate VS 2017 solution files, and I don't have problems building r3-core. Yes, it's built at the first run with max number of parallel processes to 8.

**Comment by hostilefork** [comment]
@zsx I was using 3.5.2 but upgraded it to 3.72, with no difference.

I am loading the generated Rebol3.sln file, which has 10 projects in it.  It doesn't matter if I choose to Rebuild Solution or just build r3-core, the build still has the problem.  The way I ran CMake was to open the folder from Visual studio and use Generate Cache.

In your build output, how many times do you see a line like `------ Generate tmp-natives.r`?  Is it once or many times?

**Comment by zsx** [comment]
@hostilefork hmm, I just tried to rebuild from scratch, and now it failed, at the first run, but succeeded at the second run.

**Comment by hostilefork** [comment]
I used to have a behavior something like that in VS2015, it used to be hit or miss if it would work or not.  I guess the bottom line is if you see multiple `------ Generate tmp-natives.r` or other indication that the process is running multiple times, the possibility for failures will exist if things run out of order or catch a file in mid-generation so it can't open it.

I'm fairly sure that what we want to do is what I list above.  That is to consider the global prep step to be non-negotiable and happen before everything else, and to imagine the generated files being treated as ordinary source dependencies for the target...noticing if the files changed or not, and having the emitter being sensitive to not changing the timestamps on files that do not actually change.  Otherwise, I don't see any way to get reliable incremental builds.

**Comment by zsx** [comment]
@hostilefork I found that you can set the "number of parallel project builds" to 1 to disable it: Tools>options>Projects and Solutions>Build and Run

Within the project, you can turn on "multi-processor compilation" under Project>Properties>C/C++>General

**Comment by zsx** [comment]
The problem with "parallel project build" seems to be that multiple projects think they need to run "prep" as a dependency, and VS couldn't figure out that they have a common dependency (prep) and let that finish before building these projects in parallel. I don't see in your comment above how this dependency is going to be handled.

**Comment by hostilefork** [comment]
@zsx Hm, weird, I was getting a successful build from making a prep custom target before, but now I'm not... it's doing the same thing, running the prep more than once :-(

Perhaps generating a simple case and demoing it in a StackOverflow question could get someone to chime in on what to do about it.

**Comment by hostilefork** [comment]
I'm doing my first Windows-based rebmake build, getting a MSVC project...looks promising!  It needed a [couple tweaks to the RIGOROUS settings](https://github.com/metaeducation/ren-c/commit/d50e402729737ff887105d8ca1089321438e0211).  And then there's [this small annoyance with "retargeting"](https://github.com/metaeducation/ren-c/issues/597), and some [MSBUILD warnings that can't be disabled (?)](https://github.com/metaeducation/ren-c/issues/598)

But beyond all that, I'm not getting prep running before the extensions.  They all come up with an error like when the parallel build situation was happening:

> Cannot open include file: 'reb-types.h': No such file or directory | Crypt |C:\Projects\ren-c\src\include\sys-core.h | 212

In fact, the last three things to run are "folders", "prep", and "clean"... I'm not sure why it would run clean as the last build step.  :-/

Am I doing something wrong?  I loaded the Solution called "app".

**Comment by zsx** [comment]
Great that it worked for you.

I didn't set 'prep' as a dependency of 'main', because my imagined work flow is like:
1. run prep
2. build main
3. make some changes
//  "prep" might not be required to rerun
4. build main
...

Not fully automatic, but could save some time when developing.

Did you do a "build solution"? I've never tested that, I always built the individual project manually, probably because I knew there would definitely be some problems there and I wanted to pretend that there were not. ;)

This is a big change, and there are quite some rough edges to smooth out, and some of them I might not have time to work on, so I kinda rushed out to just make the essential parts work.
