### ISSUE TITLE
The startup of REPL is slow from Windows Double Click Launch

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#496]
Starting the REPL with the double click is slow. In fact it takes about 5 seconds (A few weeks ago it was immediate) 
ren-c:
Version:   2.102.0.3.40
Platform:  Windows win32-x64
Build:     7-May-2017/9:58:46
Commit:    ba8174e463e88c09e13ef9d196d2387f94a81910

From CLI is:
$ time ren-c --do "print 4 + 5"
9

real    0m0.103s
user    0m0.000s
sys     0m0.031s

**Comment by zsx** [comment]
Just spent some time looking into this, and found the culprit is in the function exists?
[this line](https://github.com/metaeducation/ren-c/blob/master/src/os/host-start.r#L303) took more than 6 seconds on my system.

>> exists? %/user/user
== _
>> dt [exists? %/usr/usr]
== 0:00:06.766202

>> dt [exists? %/c/usr/usr]
== 0:00:00.002349

**Comment by hostilefork** [comment]
Thanks @no-e-in for the report, @zsx for taking care of it...
