### ISSUE TITLE
d0d54: Android build fails with RIGOROUS

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#504]
src/os/posix/host-process.c: In function 'OS_Create_Process':
../src/os/posix/host-process.c:730:35: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                     if (input_len >= input_size) {

**Comment by hostilefork** [comment]
Try `cast(off_t, input_len) >= input_size` ...

**Comment by giuliolunati** [comment]
Fixed that.
Another error:

`src/core/u-compress.c:260:12: error: variable 'buf_size' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
     REBCNT buf_size;
            ^
`

**Comment by hostilefork** [comment]
Grr.  Try moving the declaration of buf_size and its branches (260-306) to before the Make_Binary(buf_size) at 349.

**Comment by giuliolunati** [comment]
One more error (strangely, only in release build):

```
In file included from ../src/include/sys-core.h:616:0,

                 from ../src/core/d-break.c:43:

../src/core/d-break.c: In function 'Do_Breakpoint_Throws':

../src/core/d-break.c:87:20: error: variable 'temp' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]

     DECLARE_LOCAL (temp);

                    ^

../src/include/sys-value.h:1492:20: note: in definition of macro 'DECLARE_LOCAL'

     REBVAL * const name = cast(REBVAL*, &name##_pair) + 1; \

                    ^

```

**Comment by hostilefork** [comment]
Try moving it to line 126, with a comment:

        // Call the host's breakpoint hook.  The DECLARE_LOCAL is here and not
        // outside the loop due to wanting to avoid "longjmp clobbering" warnings
        // (seen in optimized builds on Android).
        //
        DECLARE_LOCAL (temp);
        if (PG_Breakpoint_Quitting_Hook(temp, interrupted)) {
