### ISSUE TITLE
Warning Needed on Unexpected Enfix Completion ("dark corner")

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#510]
In most cases `if...else` is equivalent to `either`, also when return value is used, as in `x: if false [1] else [2] | x` => 2
However this equivalence is misleading in other cases, as `append copy [ ] if false [1] else [2]` => [ ]; and `print if false [1] else [2]` => error

**Comment by hostilefork** [comment]
As mentioned in chat, this is a known issue with how non-tight left hand arguments work.  They complete their left hand side, "as much as possible"

Mechanically I'm not sure what can be done.  It might be argued that people are used to grouping IF and ELSE together so much that it is a bad idea to use the word for something "unusual", and it should be a symbol or something.  But Rebol's simplified notions of precedence have other implications that run against preconceptions.

If you have ideas chime in.  We can try experiments, like being able to check if an expression could ever return void, and if not make it an error to ELSE it.  I'd like to think about these as general mechanisms, like the evaluated bit... just seeing what kinds of things can be designed.

**Comment by hostilefork** [comment]
It's time to do a happy dance... I think I solved this!!!

https://github.com/metaeducation/ren-c/commit/4ee0f2360e88d7fd494c31c460965005d3a290cf

You can do me a favor by trying some tests and tell me if anything you think should work does not, and put them in the THEN and ELSE tests.  :-)  When you're satisfied the dark corners are gone, I'll let you close the issue...

**Comment by giuliolunati** [comment]
Ok for me!

**Comment by hostilefork** [comment]
Wanted to leave a link here for anyone stumbling across it, to the next step of the solution... as it got slightly trickier:

https://github.com/metaeducation/ren-c/commit/5af6d3d9d245d48e0438ea41f6e402a71d78cb01

**Comment by hostilefork** [comment]
At first we didn't have too many left enfix normal operators.  So it made sense to do what made ELSE happiest.  But as we've gotten more and more enfix things (like OR and THEN), it's becoming apparent that there are two competing interests for the behavior...

https://forum.rebol.info/t/enfix-normal-revisited-unlimited-default-one-eval-operator/565

So I am wondering if it's easier to learn this dark corner, and have an operator to work with it?  Reopening the topic.  :-)

**Comment by hostilefork** [comment]
I think we have to have completion be the default.  Here's a bit of why:

https://forum.rebol.info/t/enfix-normal-revisited-unlimited-default-one-eval-operator/565/5

So I have committed it that way.  I guess the answer being that you need to use a GROUP! or use `<-`. 
 :-/

What we'll need are some good errors/warnings to hint you when you are in a situation that is probably not what you meant.  Those warnings will take some time to design, they're non-trivial.

C has developed these over time--early compilers didn't have them.  So I used to put a lot of parentheses in C code--what I might call "over-parenthesization".  Even if I knew the rules, I would want to make it all very clear:

     if ((x == 10) && (y == z)) {...}

Fact is, the rules are such that == has higher precedence than &&, you can write that just fine as:

     if (x == 10 && y == z) {...}
 
But other situations aren't so clear, especially when you are using things like `&`.

Today, compilers have warnings that "suggest parentheses".  I think that's what we need, here, to help people who might get RETURN wrong.  I don't have those safeguards worked out yet, but I feel confident enough that we have to bias toward completion that the change needs to go ahead and be made.

**Comment by hostilefork** [comment]
Trying full completion did not give the benefits that were thought it might.  It introduced other problems, including causing there to appear to be different modes of taking arguments...as if there was a special one for "last argument".

So it lost the good properties of **return if condition [...] else [...]** that the previous approach had, bringing no benefit, and adding new problems.  The "one expression" rule has been restored, but still using new work that made it more complete.

Additionally, declaring a right hand argument tight will make it add an extra deferment step to any enfix which follows it.  This provides an additional axis of flexibility for any function which would rather avoid triggering an enfix operator after it, preferring to let the operator trigger after whoever called it.  This is used by lambda (=>) to allow itself to be an argument to THEN, but not trigger ELSE during its creation, but after the THEN runs:

https://github.com/metaeducation/ren-c/pull/911
