### ISSUE TITLE
BROWSE throws "Access Error" but still works

### ISSUE THREAD

**Issue by draegtun** [metaeducation/ren-c#516]
Example:

    >> browse http://www.rebol.com
    ** Access Error: external process failed: "Operation not permitted"
    ** Where: browse
    ** Near: ... browse http://www.rebol.com ??
    ** File: ../src/core/n-io.c
    ** Line: 639

Despite above error the page is opened correctly in default browser.

* This is on Mac (OS X 10.9.5)
* Get no error on R3-Alpha (r3-g25033f)

**Comment by hostilefork** [comment]
No mac to test on ATM, but believed resolved by this:

https://github.com/metaeducation/ren-c/commit/fa34e01038e94ce31051d2304eb39a7e9f1c68b7

**Comment by draegtun** [comment]
Above commit has fixed the problem... thank you.
