### ISSUE TITLE
SET ignores extraneous words in target block

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#518]
Considering the following case:

    set [a b] [10 20]
    set [a b] [30]

I would expect B to be BLANK (legacy behaviour) or VOID. However, it appears it is simply ignored:

    >> b
    == 20

**Comment by hostilefork** [comment]
It would seem that this is the semantics of the /PAD option.

If /PAD is the default, then the option for not padding needs a name.

**Comment by rgchris** [comment]
I'm not sure what the purpose of the non-padding version is. I'd consider B retaining its value in the above example unexpected behaviour in most circumstances.

**Comment by hostilefork** [comment]
It seemed sensible to make it honor the switch, given its existence.  But I'm fine with making /PAD the default behavior.

Red introduced /SOME for the non-padding version, so perhaps that is useful.

    >> a: 10 b: 20
    >> set/some [a b] [99]
    >> a
    == 99
    >> b
    == 20

**Comment by rgchris** [comment]
I made the point elsewhere that PAD mode should follow whatever behaviour PICK does beyond the the tail, be that VOID or BLANK. /SOME sounds ok.

**Comment by hostilefork** [comment]
/PAD by default, adopt /SOME refinement

https://github.com/metaeducation/ren-c/commit/58d6d5b76265dbd491729ae70b07fede92b26c0a
