### ISSUE TITLE
user.reb no longer loads

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#523]
As of this commit

https://github.com/metaeducation/ren-c/commit/58d6d5b76265dbd491729ae70b07fede92b26c0a

**Comment by gchiu** [comment]
this seems to be part of the problem https://github.com/metaeducation/ren-c/commit/c712df784c8b87cbb746b82476b6d8d06af0f0e4#diff-30b9375992bd641d0630c5d4387b5c3dR299

The `to-dir` function has had this added ` return: [blank! string!]` but the function returns a file!

However, if you comment this out, or, replace with `return: [blank! string! file!]` you get a _managed series was likely created during evaluator tick: 46596_ error.

**Comment by draegtun** [comment]
Yes I can confirm problem....  The above changes stops `system/options/home` being set so startup can't find `%user.reb` (and `%console-skin.reb`).

So problem is not just `to-dir` but also `get-home-path` functions.  

Are you making changes @gchiu ?   Or do you want me to have a look??

**Comment by draegtun** [comment]
@gchiu - Have submitted PR which fixes it for me.  I have noticed an issue with CONSOLE status not being correct (stuck on LOADED) but I'll look into this separately.

So above fix works OK for you on Windows?

**Comment by gchiu** [comment]
Sorry, gone to bed
