### ISSUE TITLE
Different ways of inserting binary values ODBC

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#531]
Firebird inserts binary data as "x'FFFF'", Interbase didn't work (waiting to hear).
Now DB2 also supports "x'FFFF" but to display has to use a Hex() function to retrieve it.

And when inserting into blobs, it needs to be for DB2 "Blob(x'FFFF')"

**Comment by hostilefork** [comment]
If you were getting back strings from the ODBC driver when a Rebol BINARY! was inserted into a SQL BINARY column...this may have been resolved by the changes made for SQLite here:

https://stackoverflow.com/questions/58438456/sqldescribecol-returns-sql-varchar-for-binary-blob-wchar-decimal

But if that didn't do it, it would show up quickly again if you run the [insert and select test](https://github.com/metaeducation/rebol-odbc/blob/master/tests/odbc-test.reb).  If that is the case, please re-file it at the [rebol-odbc GitHub](https://github.com/metaeducation/rebol-odbc/issues)...as we try and limit issues on the Ren-C repository to the core.
