### ISSUE TITLE
BROWSE broken on OS X

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#533]
Build [44c34ae](https://github.com/metaeducation/ren-c/commit/44c34ae) breaks BROWSE on OS X:

```
>> browse http://rebol.info
** Error: Can't detect OS browsers, hijack GET-OS-BROWSERS to override
** Where: get-os-browsers browse
** Near: for-each template get-os-browsers ?? [
    command: replace ...
** File: ../src/core/../extensions/call/mod-call.c
** Line: 569
```

**Comment by hostilefork** [comment]
This should help with that error, but other things are changing as I try to simplify CALL...

https://github.com/metaeducation/ren-c/commit/ff326fdd38adb01f95a06ee1473622254f204504

**Comment by hostilefork** [comment]
Is this fixed now?  I still don't have an OS/X machine...

@zsx?

**Comment by draegtun** [comment]
@hostilefork - Works for me (tested on Mac OSX 10.9.5)
