### ISSUE TITLE
No whitespace means function not detected by prototype scanner

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#535]
A small thing, but:

    //
    //  Foo: C
    //
    void Foo(
        int x,
        int y
    ){
        ...

If you don't put a space between `){` it doesn't get seen by the source scanner.  If you say `) {` it does.

I've gotten in the habit of using `][` in Rebol in these situations, to cut down on "visual gaps", so that has carried over to my tastes in C...

Delegating in case there's some "right" way to muck with the whitespace in the parser spec...

**Comment by codebybrett** [comment]
I've fairly certain that SOME should be ANY within the line [function-proto some white-space](https://github.com/metaeducation/ren-c/blob/master/src/tools/common-parsers.r#L264).

I inadvertently upended my surface pro 4 (what I'd been using as my main machine) off a table and onto a concrete floor, shattering the screen. Makes things a little awkward, esp. touching the glass fragments! So I've been in the process of shifting stuff off it in preparation for it's erasure.  This includes my ren-c build environment which is just a little broken.   I have another machine to play with when my wife is not using it and will aim to look at this later if you haven't tried out the change I suggest above.

**Comment by hostilefork** [comment]
No rush...even if your change doesn't work when I try it tonight!  If you're going to inconvenience yourself with setting things up, you should be doing it on your newer, better computer :)

**Comment by hostilefork** [comment]
Simple though this was to test, I didn't get around to it until right now... 
But it works!

https://github.com/metaeducation/ren-c/commit/4f166163bb1c0d63906192a941ef1acc2ca73edb

**Comment by codebybrett** [comment]
Great!  I do now have a replacement SP4, but as usual, taking a long time to reinstall everything. The worst experience was just trying to install latest w10 update on it even with MS support's help - ridiculous. Haven't got ren-c building on it yet.
