### ISSUE TITLE
Bad binary generated sometimes (pre-rebmake)

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-c#565]
I get a bad binary about 50% of the time on [my pre-rebmake serial branch](https://github.com/kealist/ren-c/tree/SerialFix2).  Building on Windows with MinGW

    fail() before object table initialized, code = 4004
    C Source File ../src/core/c-error.c, Line 867
    Kind=34
    No containing series for value...panicking to make stack dump:
    managed series was likely created during evaluator tick: 0

See image below:

![Bad Build](http://i.imgur.com/rqaBxDo.png)

**Comment by hostilefork** [comment]
For better or worse, we are committed to rebmake (or its Rebol-based-successor) at this point.  So there isn't much in the way of resources for looking into what was going on before it.

But if you are having build problems under rebmake, then do report them...
