### ISSUE TITLE
Crash on writing random data to a https address

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#573]
>> write https://myflick.flickelectric.co.nz/dashboard/day/2017-07-13 compose [
[   GET [Authorization: (join-of "Bearer " "abcd")]
[   ]
Assertion failed!

Program: C:\Users\Graham\rebol3\r3.exe
File: ../src/include/sys-series.h, Line 642

Expression: ANY_SERIES(v)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by gchiu** [comment]
Similar to this one

>> read https://myflick.flickelectric.co.nz/users/sign_in
Assertion failed!

Program: C:\Users\Graham\rebol3\r3.exe
File: ../src/include/sys-series.h, Line 642

Expression: ANY_SERIES(v)

Red does this on the same page

>> probe read https://myflick.flickelectric.co.nz/users/sign_in
{<!DOCTYPE html>^/<html>^/<head>^/  <meta charset="utf-8">^/  <meta name="description" content="" />^/  <meta name="viewport" content="width=device-width">^/^/  <title>The page you were looking for doesn't exist (404)</title>^/^/

**Comment by hostilefork** [comment]
Resolved in https://github.com/metaeducation/ren-c/commit/c7cf1b177fb9efeb0d3d9a4d6c877be0265a9921
