### ISSUE TITLE
troubles building with cmake

### ISSUE THREAD

**Issue by darrencruse** [metaeducation/ren-c#585]
was attempting to build following the instructions here:
https://github.com/metaeducation/ren-c/wiki/Building-Ren-C-with-CMake

first I tried on my Mac.
First I was getting errors about the external libffi stuff but I think I figured out you need to git clone the repo with "--recursive" and got past that.

but then there were errors because the CMakeLists.txt file refers to these files that aren't in the repo anywhere:

        ${OS_DIR}/generic/host-locale.c
        ${OS_DIR}/generic/iso-639.c
        ${OS_DIR}/generic/iso-3166.c

I decided to switch gears and see if I had better luck on my ubuntu linux box.

At first I got an error there something about "string does not support the command CONCAT" or something but that was resolved after pulling a newer cmake 3.x version than the default cmake version 2.8.

Next I hit the same error referencing those missing files I listed above.

Just for grins I commented the lines referencing those files out but it still won't build the final r3-core output file.

I should have said I'm very new to cmake btw possibly I'm doing something dumb here.

e.g. I wasn't sure exactly what options if any I needed to pass to cmake i.e. where the docs say:

   cmake [options] /path-to-ren-c/make

so I was literally just doing:

  cd make/build
  cmake ..

**Comment by hostilefork** [comment]
A recent major change in the build process has shifted to an "all-Rebol" solution:

https://github.com/metaeducation/ren-c/commit/726f4ab2dee3086ce40c001adf9f128cbc43be36

Basically, the build configuration is all in Rebol formatted files... the only tool you technically need to use to drive the build is Rebol (it can call the compilers using CALL to do a full build)... it can [generate the Visual Studio project files](https://github.com/metaeducation/ren-c/blob/master/src/tools/rebmake.r#L1815), or an nmake file, or a gnumake file, etc. etc.

It's a giant change that @zsx has been undertaking.  And interestingly enough, if it works, then it shouldn't be too hard with a TCC-enabled Rebol to make it bootstrap itself completely.

But the README has not been updated to reflect the new information, nor has the CMakeLists.txt been deleted yet.  Plan is to get rid of the makefile.boot altogether, and kick off the process from Rebol.

I'm not sure what @zsx would suggest as the best way to get a build on a mac right now is...

**Comment by hostilefork** [comment]
Note: for how Travis currently builds on Mac, here's the C++ build log (preferred build if you are developing, extra static checks during compilation):

https://travis-ci.org/metaeducation/ren-c/jobs/256453959

and here's the C build log:

https://travis-ci.org/metaeducation/ren-c/jobs/256453960

The travis YAML driving that is here:

https://github.com/metaeducation/ren-c/blob/master/.travis.yml

**Comment by darrencruse** [comment]
Interesting you mention @xsx - I didn't say above but the reason I was attempting to build ren-c (core) was that I hoped to apply what I learned to building the ren-c-view branch I'd stumbled on via google at:

    https://github.com/zsx/r3/tree/ren-c-view

But I notice the ren-c-view branch hasn't been touched in 7 months...

Any idea how much the new "all-rebol" approach or the Travis Mac build approach will/won't apply to this other branch?

**Comment by zsx** [comment]
@darrencruse that branch will not build with the new **rebmake**, I'll probably touch that branch again once I get view on Ren-C build.

To build the core on MacOS, I think you only need to:
```
#cd make
#./r3-osx-x64-368bd5a-debug ../src/tools/make-make.r OS_ID=0.2.40 REBOL_TOOL=./r3-osx-x64-368bd5a-debug
```

**Comment by darrencruse** [comment]
Thanks @zsx fwiw the reason for my interest in your ren-c-view branch was I'd gotten interested in seeing if I could help contribute to getting the gui view stuff working in the browser atop the emscripten build of ren-c core.

I was esp. excited when I noticed your use of nanovg and learned that nanovg is already very html5 canvas like, so I thought the conversion from your nanovg code to html5 canvas might not be too hard.

I even noticed that the guys behind the Oryol C++ 3D library had gotten nanovg working directly under emscripten in the browser (though unfortunately they pulled it cause they said it was continuously using about 10% cpu owing to excessive draw calls being made).

(if you're interested you can see similar gui-widget-atop-webgl-stuff the Oryol guys have running in the browser e.g. here http://floooh.github.io/oryol-samples/index.html)

The honest truth is I have more recent experience working with the javascript stuff it's been years since I've dealt with C/C++ and makefiles and so forth (though I don't mind I'm rusty!).

**Comment by hostilefork** [comment]
> The honest truth is I have more recent experience working with the javascript stuff it's been years since I've dealt with C/C++ and makefiles and so forth (not that I mind it's just that I'm rusty!).

The honest truth on my side is, if you have the JavaScript experience we probably need you most there.  If we could get in the browser with something interesting that would be a tremendous win... there are many applications, what about a PARSE-based variant of "regexr"?

http://regexr.com/

And we've done all the darn work to make sure we aren't breaking C standard rules so we *can* do emscripten.  Might as well use it.

I feel like getting you a good `rebol.js` sounds like the main priority.  @giuliolunati has been the point man on that, but he's away for the moment...

---

Note: I wrote [this thing](http://blackhighlighter.hostilefork.com/) and for me it was [a nightmare](https://github.com/hostilefork/blackhighlighter/blob/master/jquery-blackhighlighter/jquery-blackhighlighter.js) *(comments welcome)*.

**Comment by hostilefork** [comment]
Closing this, as the only still-applicable part here is an overall known issue of "make new build system smoother".

See the updated [README.md](https://github.com/metaeducation/ren-c/blob/master/README.md)

See also 2018 roadmap/updates post:

https://forum.rebol.info/t/ren-c-2018-roadmap-and-retrospective/443
