### ISSUE TITLE
FIND BLOCK! BLOCK! breaks when the VALUE block exceeds the length of the SERIES.

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#589]
In the case where the first value match is made at the end of the SERIES block and subsequent values remain in the VALUE block:

```
>> find [this that] [that this]
VAL_TYPE() called on END marker
C Source File ../src/core/f-series.c, Line 183
Pointer found in freed tail capacity of series
Kind=0
Containing series for value pointer found, panicking it:
managed series was likely created during evaluator tick: 125705
series guard didn't trigger ASAN/Valgrind trap
:
either not a REBSER, or you're not running ASAN/Valgrind
```

**Comment by hostilefork** [comment]
Tx... fixed here:

https://github.com/metaeducation/ren-c/commit/cf11be9dfed92c2c1fd59c47be60dc7a25ad99c2

Ah, @zsx, you remember these?  You were probably annoyed at first when VAL_TYPE() started crashing on end markers, but I trust you see the wisdom nowadays.  :-)
