### ISSUE TITLE
Collect doesn't have RETURN: enabled for string!

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#593]
COLLECT doesn't currently accept string! as an OUTPUT target:

```
>> collect/into [keep "Foo"] make string! 0
** Script Error: collect doesn't have RETURN: enabled for string!
** Where: collect
** Near: collect/into [keep "Foo"] bar ??
** File: ../src/core/c-function.c
** Line: 1833
```

**Comment by hostilefork** [comment]
Weird, it really should be ANY-SERIES!.  Don't know why I marked it BLOCK!.

Should be fixed here:

https://github.com/metaeducation/ren-c/commit/81e113bfd3131eb9c8faf8a8f99cdf0bc42eef66#diff-0bb759bd4eb23342c518343702fea275L499
