### ISSUE TITLE
Visual Studio project generated with Rebmake needs "retarget solution"

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#597]
I can generate project files, but when I try to build them I get.

> MSB8036 - The Windows SDK version 10.0.10586.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".	folders	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141\Toolset.targets 36

I do retarget solution and it says:

> Retargeting End: 18 completed, 0 failed, 0 skipped

Then this message goes away.  Is this a known issue?  (I'm just using the plain Visual Studio 2017 install; I didn't do anything unusual.)

**Comment by zsx** [comment]
I hardcoded the SDK version on my system there. :)

Need to figure out a way to query the version, and/or allow it to be configured.

**Comment by hostilefork** [comment]
I don't know if it's foolproof, but on my machine looking at the filesystem, there's directories named like:

     C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\
     C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\
     C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\

I just did an absolute fresh install of VS2017 (no special options ticked, just VC for C++ app development) and got those 3 with the install.

What we might try is looking in that directory and default to the largest number, and fall back to whatever the largest version # currently for a fresh install is (at the moment, that's 16299)
