### ISSUE TITLE
MSBUILD: "Intermediate Directory contains files Shared from Another Project"

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#598]
I don't know if these warnings are avoidable or not, but I'm getting them.  It says here that [MSBUILD warnings can't be disabled](https://stackoverflow.com/a/1023891/211160)

> Warning MSB8028 The intermediate directory (x64\Debug\) contains files shared from another project (check.vcxproj, folders.vcxproj, prep.vcxproj, top.vcxproj).  This can lead to incorrect clean and rebuild behavior.	**clean** C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets

> Warning MSB8028 The intermediate directory (x64\Debug\) contains files shared from another project (folders.vcxproj, prep.vcxproj, top.vcxproj).  This can lead to incorrect clean and rebuild behavior. **check**	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets

> Warning MSB8028 The intermediate directory (x64\Debug\) contains files shared from another project (folders.vcxproj, top.vcxproj).  This can lead to incorrect clean and rebuild behavior. **prep** C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets

> Warning MSB8028 The intermediate directory (x64\Debug\) contains files shared from another project (top.vcxproj).  This can lead to incorrect clean and rebuild behavior. **folders** C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets	387

**Comment by zsx** [comment]
I noticed these too, but haven't looked into them yet.
