### ISSUE TITLE
script error on help maybe

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#610]
```
>> print system/commit
583d6fbb88a57e2bd7ad8c4eab5dc13dded9ecab

>> help maybe
USAGE:
     MAYBE test value 
** Script Error: cannot use copy on logic! value
** Where: copy if for-each inherit-frame all any construct dig-function-meta-fields help
** Near: child/(param): copy parent/(param) ??
** File: ../src/core/t-logic.c
** Line: 264

```
This is a linux 32 bit build.

**Comment by hostilefork** [comment]
This is related to:

https://github.com/metaeducation/ren-c/issues/393

The frame you get with MAKE FRAME! of a specialization has fields that should not be visible when enumerating the specialization.  It should appear to be empty.

**Comment by hostilefork** [comment]
Resolved by solving the general problem, which addresses a lot of other related problems...!

https://github.com/metaeducation/ren-c/commit/9b50f350fdace1556597ed3699b942626c917fd0

Thanks for supplying the motivation to get around to solving it.  :-)
