### ISSUE TITLE
Anonymous word triggers context error within modules

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#627]
Running the following code triggers an error:

```
>> do {Rebol [Type: module Name: none] foo: make object! [bar: func ['val][val]] foo/bar baz}
Module: Untitled Version: Date:
** Script Error: baz word is not bound to a context
** Where: do module catch either either _ do
** Near: object! [bar: func ['val] [val]] foo/bar ?? baz
** File: ../src/include/sys-bind.h
** Line: 346
``` 

As the word is passed to a function expecting a literal value it shouldn't be resolved or evaluated.

**Comment by hostilefork** [comment]
This is a bug in infix checking on soft quotes.  Unbound things should not trigger failures when lookahead finds them as unbound for infix tests.

*(e.g. `foo/bar` is a function call that soft quotes forward.  if `baz` was an enfixed operation that hard quoted its left hand argument, then it would take priority and be able to backwards hard quote `foo/bar`.  Consider for instance **help/doc default**, where default hard quotes left.)*

The infix checking would gracefully tolerate for this for bound words that were not set, but did not gracefully handle unbound ones.  baz has no binding in this module...which according to #626 is a bug.

But this specific issue should be resolved by:

https://github.com/metaeducation/ren-c/commit/4291cd31a901aaa7db768e2ff636e2b04874dae8
