### ISSUE TITLE
Travis build don't works for Android >= 6.0

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#630]
Just switched from Android 5 to 7, and android-arm travis builds no more work:

`CANNOT LINK  EXECUTABLE ... cannot find verneed/verdef`.

**Comment by giuliolunati** [comment]
Fact is, current build use android-elf-cleaner to avoid annoying warnings in Android 5.x.
But then executable no more run for Android >= 6.0.
My proposal is to avoid android-elf-cleaner in Travis. Final users with Android 5.x can clean executable themselves.

**Comment by hostilefork** [comment]
@giuliolunati if you know what to do, then by all means, do it!  I'm afraid I have no idea, I'll take your word...

**Comment by gchiu** [comment]
https://github.com/giuliolunati/android-elf-cleaner so that they run under < Android 7

**Comment by giuliolunati** [comment]
Let see if [this](https://github.com/metaeducation/ren-c/commit/564aac07ee51ec1ee1fd5115cf0bbe3c21b4fb5d) works...

**Comment by giuliolunati** [comment]
Ok. it works.
