### ISSUE TITLE
HELP on DATATYPE! or STRING! crashes interpreter

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#650]
Running help on DATATYPE! (list all 'global' words associated to a value of that type) or STRING! (search for 'global' words containing that string) crashes the interpreter and returns code 1.

```
>> help map!
Protected cell passed to writing routine
C Source File ../src/include/sys-value.h, Line 1535
At evaluator tick: 168457
Kind=43
Containing series for value pointer found, panicking it:
unmanaged series was likely created during evaluator tick: 168457
series guard didn't trigger ASAN/Valgrind trap
:
either not a REBSER, or you're not running ASAN/Valgrind
```

**Comment by hostilefork** [comment]
Twiddly implementation issue *(in "inheritance"/"construction" code that needs a lot of review and thinking about)*...but this should resolve the particular problem.

https://github.com/metaeducation/ren-c/commit/2fe480058b9d36744d53b73be7e4a500d37aa559
