### ISSUE TITLE
Problem with CONSOLE_READCONSOLE_CONTROL in old mingw

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#669]
In the older versions of Mingw, in the wincon.h file, CONSOLE_READCONSOLE_CONTROL is not present.
My solution: copy wincon.h, winapifamily.h, _mingw_unicode.h from a newer version of MinGW-W64

**Comment by hostilefork** [comment]
Sigh, well, thanks for looking into it.  Could you perhaps find a link to good canon versions of these on the web and give precise instructions of what directory to put them in?

**Comment by no-e-in** [comment]
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/d47421eab0299215a33c7d24252b66fff3579b8a/tree/mingw-w64-headers/include/wincon.h

and

i686-w64-mingw32\include

**Comment by hostilefork** [comment]
Thank you @no-e-in!

@codebybrett is this good enough to get you building?  I'll keep this open as a reminder to find a way to downgrade the build if the feature is not available, but I'm packing/moving right now...

**Comment by codebybrett** [comment]
Thanks for looking into it.

I copied the file to C:\MinGW\mingw32\include but same error.
I then re-removed it and went to copy it to C:\MinGW\include but it was there!
So maybe my MinGW is not setup correctly. I noted some google group message from 2008 with a similar issue saying there was a problem in MinGW that was going to be resolved - so it probably should have been resolved by now.

I recall having to set my path as per the MinGW page but I also had to include msys. I do it in a .cmd file:

    SET PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin

I don't want to waste my or anyone else's time on a broken toolset installation.  I'm happy to uninstall this and install something that works without too much tweeking - if there's a suggestion.

I'm going to be moving location this evening - not sure of connections and time available at next location.

**Comment by hostilefork** [comment]
@codebybrett Try commenting it out.  It's should still run, it's just trying to get some extended windows features on the console... you'll lose some aspects of cancellation, that's all.

    /*
    CONSOLE_READCONSOLE_CONTROL ctl;
    ctl.nLength = sizeof(CONSOLE_READCONSOLE_CONTROL);
    ctl.nInitialChars = 0; // when hit, empty buffer...no CR LF
    ctl.dwCtrlWakeupMask = (1 << 4); // ^D (^C is implicit)
    ctl.dwControlKeyState = 0; // no alt+shift modifiers (beyond ctrl)
    */

Then pass NULL in for the console control instead of &ctl:

    DWORD total;
    REBOOL ok = ReadConsoleW(Std_Inp, Std_Buf, BUF_SIZE - 1, &total, NULL);
    if (NOT(ok))
        rebFail_OS (GetLastError());

This is an approximation of what I would like to do more dynamically, and if that works for you, I will, at earliest opportunity, come up with some build-environment-detecting version of that...which I could probably do if I weren't packing bags as we speak.

**Comment by codebybrett** [comment]
I didn't see an error, but it just finished with a "Running... ..\src\extensions\debugger\ext-debugger.c" and I didn't see a new .exe. 

Next chance, I'll clear out ren-c on my disk and pull it down again, pull the updates and retry. If that doesn't work I'll erase the toolset and reinstall.

"We sure are mobile units..." - absolutely, I have to check the calendar to determine country!

**Comment by codebybrett** [comment]
Ok, so sitting in Marco Polo airport, I scorched my ren-c local copy. Pulled it from my repo, pulled latest updates - no go. Then re-applied your workaround as above and I now successfully have a r3.exe.  Tried with group at head of path and that works. Yay!

For the sake of completeness, unapplied your workaround and copied wincon.h as suggested by no-e-in and tried again but that didn't work.

**Comment by hostilefork** [comment]
>  Tried with group at head of path and that works. 

Heh, these minor things, I spend a few hours on and get working... even if we've talked about them forever!  I have some problems that interest me more than others, I guess.  Graham wants me to be more practical, maybe I should churn through the easy stuff...but I always want to work on the hard stuff.

> For the sake of completeness, unapplied your workaround and copied wincon.h as suggested by no-e-in and tried again but that didn't work.

Grumble.  There's certainly quite the platform and variable zoo going on here, so with limited resources I say "if you guys are happy I'm happy."  But I'll leave this open and look into it when time permits, for a better solution.

**Comment by codebybrett** [comment]
Just to document what I have, Mingw is still working for me (as of commit ce0a7751b7c77d810a93bfbaabed841b06f169ef) on Windows 10.

I apply the workaround described above - passing NULL for ctl and commenting it's definition in %ren-c/src/os/windows/dev-stdio.c

I have a command file to build (deleting the objs is probably not necessary now):

    SET OLDPATH=%PATH%
    SET PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
    cd ren-c/make
    del objs /s /q
    del r3.exe

    REM CONFIG should be in %make/ folder or relative to it...
    r3-make.exe ../src/tools/make-make.r CONFIG=../../0.myconfig.r DEBUG=asserts OPTIMIZE=2

    SET PATH=%OLDPATH%

    copy r3.exe ..\..\renc.exe

My config file 0.myconfig.r is:

    REBOL []

    os-id: 0.3.1
    rebol-tool: %r3-make.exe
    toolset: [
        gcc %mingw32-gcc
        ld %mingw32-gcc; linking is done via calling gcc, not ld
        strip %strip
    ]
    with-ffi: no

Occasionally I cross my fingers, but only one pair.

**Comment by hostilefork** [comment]
Workaround is in this commit:

https://github.com/metaeducation/ren-c/commit/27ffc8cdc0a04027d548363bb5252e2c7a522ae7
