### ISSUE TITLE
RANDOM crashes on blocks of a certain size

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#671]
Using RANDOM on a block will crash the interpreter if a block is of a certain size:

    >> random [1 2 3 4 5 6 7 8 9 10 11 12]
    Assertion failed: (out != v), function Blit_Cell, file ../src/include/sys-value.h, line 1683.
    Abort trap: 6

Seems to occur when the block length is 12 or more (except 14).

**Comment by DanDLee** [comment]
This crash happens randomly on blocks of all sizes.

I've created a pull request to fix the problem: [#672](https://github.com/metaeducation/ren-c/pull/672)
