### ISSUE TITLE
Crash during recursive modification of block with PARSE

### ISSUE THREAD

**Issue by JacobGood1** [metaeducation/ren-c#674]
Here is the code:

    rebol []

    old-parse: :parse

    simple: [mark: 'ahead (insert next change mark to set-word! 'mark to get-word! 'mark)]

    parse: func [code rules] [
        replace-ahead: [some [into replace-ahead | simple | skip]]
        new-rules: copy/deep rules
        old-parse new-rules replace-ahead
        ;old-parse code new-rules
    ]

    probe parse [1 2 3] [ahead [quote 1] (probe "here")]

Here is the error message:

SER_AT_RAW asked 32 on width=1
C Source File ../src/include/sys-series.h, Line 286
At evaluator tick: 169676
managed series was likely created during evaluator tick: 169618
C Source File ../src/core/m-series.c, Line 522
At evaluator tick: 169676
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:

series guard didn't trigger ASAN/Valgrind trap
either not a REBSER, or you're not running ASAN/Valgrind

**Comment by hostilefork** [comment]
You have a mechanical problem here in the sense that you're digging into GROUP!s and PATH!s and STRING!s when you probably only meant to dig into BLOCK!s.

What you actually meant to do was add an AND BLOCK! before moving ahead with the INTO:

     replace-ahead: [some [and block! into replace-ahead | simple | skip]]

If that helps.  Still looking into why it's crashing instead of just failing...

**Comment by hostilefork** [comment]
Problem was just not stopping INTO while parsing a string (e.g. trying to parse INTO a character...)  Needed to be an error message instead of a crash:

https://github.com/metaeducation/ren-c/commit/e68a17d0184bec9707126da8bcd028f470860715

Includes addition of AHEAD.
