### ISSUE TITLE
MinGW32 build fails

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-c#698]
Trying to build again with MinGW32, but failing differently now.

    >r3-make make.r CONFIG=configs/myconfig.r DEBUG=asserts

Error: 

```
C:\Users\kealist\Documents\git\ren-cdir\ren-c\make>r3
C Source File ..\src\core\c-error.c, Line 290
At evaluator tick: 38249
Series VARLIST detected.
...and that VARLIST is of an ERROR!...
** PROBE() tick 38249 ..\src\core\d-crash.c:165
make error! [
    [ code type id message near where file line arg1 arg2 arg3]
    [
        code: 3006
        type: Script
        id: expect-arg
        message: [:arg1 "does not allow" :arg2 "for its" :arg3 "argument"]
        near: [... host-prot: default _ ~~
            boot-print: procedure [
                "Prints during boot when not quiet."
                data
                /eval
            ] ...
        ]
        where: []
        file: host-start.r
        line: 34
        arg1: default
        arg2: blank!
        arg3: branch
    ]
]

managed series was likely created during evaluator tick: 38249
C Source File ..\src\core\m-series.c, Line 522
At evaluator tick: 38249
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:


series guard didn't trigger ASAN/Valgrind trap
either not a REBSER, or you're not running ASAN/Valgrind
```

Config script:

```
REBOL []

os-id: 0.3.1
rebol-tool: %r3-make.exe
toolset: [
    gcc %mingw32-gcc
    ld %mingw32-gcc; linking is done via calling gcc, not ld
    strip %strip
]
with-ffi: no
pre-vista: yes
```

**Comment by hostilefork** [comment]
@giuliolunati is making it so that the generated files from the prep process (headers, .inc files, etc.) are all going into a separate directory tree (currently %make/prep), instead of the historical intermixing with source that we're used to.

But you've probably got residual files hanging around in the source directories which are out-prioritizing these files in new locations in some contexts.

If you feel like making a fresh enlistment you can do that, which may be easiest.  But if not you can look around to get rid of all the tmp-xxx.* files anywhere in the source tree, as well as the following from %src/include:

%host-lib.h
%host-table.inc
%reb-evtypes.h
%reb-lib.h
%reb-types.h

That should likely take care of it.

**Comment by kealist** [comment]
I wiped out the repo and started with a fresh clone.  Now every step of prep fails, 

```
Running: /C/Users/kealist/Documents/git/ren-cdir/ren-c/make/r3-make.exe -qs make-natives.r
The system cannot find the path specified.
```

**Comment by kealist** [comment]
I should say, `/c/users/...` isn't a valid Windows path.  Seems that could be the issue

**Comment by hostilefork** [comment]
When you see a Rebol-formatted FILE! like `%/C/Users/...` the concept in the system is that these are translated at the last minute somewhere into STRING! via the TO-LOCAL-FILE function.  (Its complement is TO-REBOL-FILE which turns STRING!s that are in the local filesystem format into FILE! again).  These have been renamed FILE-TO-LOCAL and LOCAL-TO-FILE to take the language name out of the operation, and given slightly different options.

Internally to the system, when it has a FILE! it should always be converting it before trying to use it on the filesystem.  So CALL or other functions when they get FILE! do this translation internally.

Can you get the precise parameterization to (what I assume is) an invocation of CALL to see exactly what its being given that is failing?

**Comment by hostilefork** [comment]
Adding @giuliolunati, and cc'ing @codebybrett just because he's successfully built with MinGW, and might have insights...

**Comment by codebybrett** [comment]
Just pulled latest changes (65baec270b3004583e7d41607af84047a80c9afb) - build for me worked.

My config looks the same as @kealist 

My line is:

    r3-make.exe make.r CONFIG=../../0.myconfig.r DEBUG=asserts OPTIMIZE=2

I'm using the r3-make.exe that comes with the repo.

**Comment by kealist** [comment]
`%rebmake.r` line 1566:

result of `probe cmd`:

```
{/C/Users/kealist/Documents/git/ren-cdir/ren-c/make/r3-make.exe -qs make-headers.r}
Running: /C/Users/kealist/Documents/git/ren-cdir/ren-c/make/r3-make.exe -qs make-headers.r
```

**Comment by kealist** [comment]
@codebybrett Try with a fresh clone

**Comment by giuliolunati** [comment]
@kealist Please, could you share the content of config file? And which commit you are on?

**Comment by kealist** [comment]
@giuliolunati The config file is in the first post, and I made a fresh clone last night, so it was the latest commit as of 10 hours ago

**Comment by giuliolunati** [comment]
Please try some experiments with the `rebol-tool:` option in your config file: delete it, or change it to `%./r3-make.exe` or to full path.

**Comment by hostilefork** [comment]
> result of probe cmd:
>
> {/C/Users/kealist/Documents/git/ren-cdir/ren-c/make/r3-make.exe -qs make-headers.r}
> Running: /C/Users/kealist/Documents/git/ren-cdir/ren-c/make/r3-make.exe -qs make-headers.r

That seems wrong...once the `%` drops off a FILE! and you're just working with strings, there's no way for Rebol to know to do the translation to a local path.  If it was going to build a string out of commands like that, it would need to do FILE-TO-LOCAL on it manually.

**Comment by hostilefork** [comment]
@giuliolunati I think the problem is your recent change:

https://github.com/metaeducation/ren-c/commit/e658b8e118a1f7b5d9856dfd0e29e6f9866fcab7

When you FORM system/options/boot to get that default, you are just converting to a string with no logic to translate the FILE! into a local path.  That should probably be FILE-TO-LOCAL and not FORM.

@kealist can you try that?

**Comment by codebybrett** [comment]
1. Made fresh clone as at 4c3ddd81a7c897cd3b1e51435c5c0e117cf4bdba to folder:

    C:\Projects\Public\ren-c-direct

2. Kept same config:

    REBOL []

    os-id: 0.3.1
    rebol-tool: %r3-make.exe
    toolset: [
        gcc %mingw32-gcc
        ld %mingw32-gcc; linking is done via calling gcc, not ld
        strip %strip
    ]
    with-ffi: no
    pre-vista: yes

3. Ran my normal command file commands:

    SET OLDPATH=%PATH%
    SET PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
    cd ren-c-direct/make
    del objs /s /q
    del r3.exe

    REM CONFIG should be in %make/ folder or relative to it...
    r3-make.exe make.r CONFIG=../../0.myconfig.r DEBUG=asserts OPTIMIZE=2

    SET PATH=%OLDPATH%

4. Checked my path to see if anything is being included that shouldn't be. Don't think so.

And... it built without problems.

Perhaps the installation of Mingw32 has issues.  Problem with that is, I can say exactly what I did when I did my install of Mingw32.

**Comment by hostilefork** [comment]
@codebybrett I think it works because REBOL-TOOL in your config is a FILE!, and so the proper translation must get done downstream somewhere.

@giuliolunati Might the code be supposed to read something along the lines of:

    name: {REBOL_TOOL}
    value: really file! any [
        user-config/rebol-tool
        system/options/boot
        to file! unspaced [{./r3-make} rebmake/target-platform/exe-suffix]
    ]

**Comment by codebybrett** [comment]
My REBOL-TOOL looks to be the same as kealist's

Here's an extract with probe cmd on rebmake.r line 1566.

        "r3-make.exe -qs make-natives.r"
    Running: r3-make.exe -qs make-natives.r
    ------ Generate tmp-natives.r
    219 natives

    ------ Generate tmp-actions.r
    "r3-make.exe -qs make-headers.r"
    Running: r3-make.exe -qs make-headers.r

**Comment by giuliolunati** [comment]
Thank you @hostilefork, [et's try](https://github.com/metaeducation/ren-c/commit/6e155adc5c06c9b56e94414fb8b59e9da533e99b)

**Comment by codebybrett** [comment]
@kealist 

Can you start r3-make.exe and show:

    >> system/version
    == 2.102.0.3.40

    >> system/build
    == 15-Jun-2017/17:54:47

    >> system/options/boot
    == %/C/Projects/Public/ren-c-direct/make/r3-make.exe

Thanks.

**Comment by kealist** [comment]
@codebybrett I have the same results with the exception of filepath matching mine.   

I tried with a fresh clone on my other computer and it worked fine, so I'm not sure why this one is different.  Maybe going through ConsoleZ is the cause?   Could be a different version of mingw.   I have just `git fetch` / `git pull` and it appears to be working now on this computer.   Thanks for the fix @giuliolunati

**Comment by giuliolunati** [comment]
Oh, well... @hostilefork found the bug.
