### ISSUE TITLE
Visual Studio projects getting written into %make/make causes problems

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#701]
When trying to run the command line:

> r3-make make.r config: configs\vs2017-x64.r debug: symbols rigorous: yes standard: c++17 optimize: 0

I get the message that it `cannot open: %make/top.vcxproj`.  Looking at the [line which does the write](https://github.com/metaeducation/ren-c/blob/af3902da0edcc8e395ecd0a429e87798f563659a/make/rebmake.r#L2189), I poked in a mold of `file-to-local` on outfile and saw it's trying to write to `"C:\Projects\ren-c\make\make\top.vcxproj"`.

If it's the case that generated projects should be in the make\make directory, then the directory should be created for you.  But once you do, trying to open them and build has a couple of problems.  First of all, r3-make.exe isn't in %make/ so it doesn't find it.  But then, building the `prep` project, it doesn't find the %make-xxx.r files.

As a momentary workaround: I can just `mkdir make` in the %make directory, and then `move make\*` to put all the .vcxproj's and the .sln into the %make directory (which is how it was before).

**Comment by giuliolunati** [comment]
@hostilefork a path was wrong -- vould you try if it's fixed?
