### ISSUE TITLE
Make Specifications for Extensions should be part of extension

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#705]
The way that Rebmake currently breaks down is that there is a somewhat "generalized" tool in %rebmake.r.  Then %make.r (formerly %make-make.r) is a kind of "parameterization" of Rebmake, specifically designed to build Rebol, using %rebmake.r...but as a sort of more a library than any kind of standalone tool (like GNU make or CMake).

Whether or not Rebmake could be generalized to a tool another project might use, I do not know.  It certainly isn't our current primary goal to create a general make system.  But it doesn't hurt to have the separation of "build environment abstraction" from "source file relationships to be built, that apply across environments".

We're in an ongoing process of splitting out a "core" interpreter from "extensions".  The extensions occupy their own subdirectories in %src/extensions/.  Each extension potentially has its own needs, such as what include or library directories it might want...which C source files contain its implementation, what warnings to disable or other special compiler switches...and which Rebol files it wants to embed.

The model is currently that an "extension" can consist of any number of "modules".  Both modules and extensions are specified in %make.r.  For instance, here is the [ODBC module spec](https://github.com/metaeducation/ren-c/blob/master/make/make.r#L470), and here is the [ODBC extension spec](https://github.com/metaeducation/ren-c/blob/0bfe6eeaced1c948101f06c7b10fa13d3c6703ff/make/make.r#L613)

I think it's clear these specifications belong somehow in the extension directory.  I'm not sure if they should be in files of their own, or if perhaps they might be in the header of a Rebol module whose body could well contain a bunch of implementation code for the extension.

*(Early on when there was no Rebol file, I experimented with using the C parser to slipstream the module info into the Rebol-styled header at the top of the C file's comment block.  I don't think that's good for most settings...even if you have some kind of per-file thing like what warnings to disable, because you might not want to edit the file if it's 3rd party source.  But it might be appropriate for *some* kind of settings if you're sure it's source for an extension.)*

One thing I'd like to inquire about is if we might simplify the model to where the unit of currency in extensions is a single module.  I know it might be desirable to "bundle" some extensions together into the same DLL, but perhaps that could be a higher level grouping.  So you might say:

    extensions: [
        * %https [ // package all components needed for HTTPS to https.dll
            Crypt [...options...]
            TLS [...options...]
            HTTP [...options...]
       ]
       + ODBC // build ODBC into the executable 
     ]

I think that would help, and then it might be the case that the "module" which represents the main entry point of the extension could have in its header things like the lists of C files it depends on, and on which platforms, etc.

But that is a theory, and maybe not the best idea.  Things like Node and other packaging systems expect you to lay out the package description in its own independent file.  It's *probably* better to follow that convention.  At least it's probably a better place to start.

So...

* I suggest backing off the "extension" vs. "module" level of hierarchy, and having a single file that sort of unifies the settings from both of those...with the intent that any further grouping is done by people in their config.
* This single file should be in the extension directory and "discoverable" by %make.r, as opposed to needing to be mentioned explicitly in it.  So it should have a standard naming convention.

**Comment by zsx** [comment]
I think it's a good idea to make building spec part of the extension. But I'm not sure if we should let users randomly bundle extensions into one DLL, that seems to complicate things a lot.

**Comment by zsx** [comment]
Building spec is now moved to the extension directory by 3a31e3c3003270ffaa3e7065cf4c927d93bd48b6

**Comment by hostilefork** [comment]
Looks to be on the right track--since that's the title of this issue, I think we can close it!

As for "multi-module extensions", I'm open to seeing good examples, but as I say I sort of wonder if the additional level of hierarchy that separates "extension" from "module" is unnecessary.
