### ISSUE TITLE
Error on help ensure*

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#725]
```
>> help ensure*
USAGE:
     ENSURE* test value 
** Script Error: cannot use copy on logic! value
** Where: copy if for-each inherit-frame all any construct dig-function-meta-fields help _
** Near: [child/(param): copy parent/(param) ~~]
** File: tmp-boot.r
** Line: 136
```

The error happens in dig-function-meta-fields (src/mezz/base-funcs.r).

And that's where I got lost.

**Comment by IngoHohmann** [comment]
ensure* is a specialization of ensure, which is a specialization of either-test. 
dig-function-meta-fields chokes on the /only refinement. This refinement is set to false in ensure, then to true in ensure*.
If ensure* is implemented as a specialization of either-test, there is no problem.

**Comment by hostilefork** [comment]
The COPY should not be necessary, and as with most of that (old!) code, there's better ways of doing just about everything it does.

But another issue is that `ENSURE*` doesn't make any sense as a concept.  The /ONLY for EITHER-TEST instructs it to return voids "as-is" when the branch is run.  But all ENSURE's branch ever does is fail.  If voids are legal in the test they will be returned anyway, e.g. *(`ensure :void? ()`)*.

So you were right to ask for HELP on it.  Both issues resolved here:

https://github.com/metaeducation/ren-c/commit/bb28ebd17011db11c09529784a13545dbc0e4f2f

Thanks for looking at it.  Hopefully you're finding this all interesting...!
