### ISSUE TITLE
Call is not handling arguments on macOS

### ISSUE THREAD

**Issue by Oldes** [metaeducation/ren-c#734]
Call without args is ok:
```
>> call/wait "clang"    
clang: error: no input files
```
but when arguments are used, they seems to be part of the command, which is not found then:
```
>> call/wait "clang -v"
** Error: No such file or directory
** Where: call _
** Near: [call/wait "clang -v" ~~]
** Line: 1
```

R3 has the same problem, Red is fine.

**Comment by hostilefork** [comment]
Currently you have to use /SHELL to get the string parsed by the shell into the file vs arguments.

Here is an old discussion on the topic:

https://github.com/rebol/rebol-issues/issues/2225

At the time I suggested what seems sensible (to me), which was that a FILE! argument be interpreted as a file, and a STRING! argument imply you want shell processing.

I think people agreed, it's just no one has worked on it.

**Comment by Oldes** [comment]
Ah... so it is old issue.. will read the issue and think about it.

**Comment by hostilefork** [comment]
Closing as duplicate...
