### ISSUE TITLE
Problems with 'help'

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#739]
From **help**:
> To view words and values of a context or object: 
>>help lib    - the runtime library
>>help self   - your user context
>>help system - the system object
>>help system/options - special settings

but **help self**, **help lib**, **help system** return:

> ** Error: PRINT called on non-literal block without /EVAL switch
> ** Where: fail else print unless help _
> ** Near: [fail {PRINT called on non-literal block without /EVAL switc...
> ** File: tmp-boot.r
> ** Line: 111

**Comment by IngoHohmann** [comment]
see pull request #740
