### ISSUE TITLE
forall unitialized-word [] closes the interpreter

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#744]
`````
>> forall word []
~/D/_/S/_/r/make (master) [255]> 
`````

No assert, no crash, just closes.

**Comment by hostilefork** [comment]
Hmmm.  Debug build should have said something.  Was it a release build?  :-/

It was a problem with a request to mold a void in an error message.  Ren-C considers voids to be un-mold-able, as they aren't "values".

Should be addressed here:

https://github.com/metaeducation/ren-c/commit/1e06e26f2095c9a32ff759e3af71b67a27c6a862#diff-42835b96e95eff10cd1eb7f7bda8f288R724

BTW, I think FOR-NEXT is a much better name for this (specialization of FOR-SKIP with skip of 1, FOR-BACK also exists).
