### ISSUE TITLE
RENAME crashes REN-C on Windows 7

### ISSUE THREAD

**Issue by iArnold** [metaeducation/ren-c#745]
r3-1e06e26-debug-cpp.exe crashes when trying to rename a file on Win7 system.

I have a file %test1.txt in the directory that I want to rename to %test3.sql

    >> rename %test1.txt %test3.sql
    SER_AT_RAW asked 1 on width=2
    C Source File ../src/include/sys-series.h, Line 308
    At evaluator tick: 191401
    unmanaged serieswas likely created during evaluator tick: 191401
    C Source File ../src/core/m-series.c, Line 530
    At evaluator tick: 191401
    Rebol Internal Error
    If you need to file a bug in the issue tracker, please give thorough
    details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

    Include the following information in the report:

    Executable not built with DEBUG_SERIES_ORIGINS, no more info

**Comment by iArnold** [comment]
Could it because it needs a permission? When I perform this action in R2 core there is a popup asking to Allow the action.

**Comment by hostilefork** [comment]
Just an assertion doing its job.  This should help:

https://github.com/metaeducation/ren-c/commit/b15f13447294945de311ebc0616afbd88377c100
