### ISSUE TITLE
Test Format Change - tests as GROUP!, BLOCK! for related tests

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#750]
The R3-Alpha test suite used BLOCK! for tests, e.g.

    [1 + 1 = 2]
    [2 + 2 = 4]

These tests were then commented using normal comments.  An attempted Ren-C extension (convention) to the idea of the "test dialect" would use ISSUE! to number the test, but inside of the block...which would generally be harmless (assuming it wasn't picked up by left infix):

    [
        #2342
        1 + 1 = 2
    ]

A better idea would likely be to make the tests use BLOCK!s as a grouping tool of related tests, and GROUP! to specify the individual tests.

    [
       #2345 {Some test description, title?}
       (1 + 1 = 2)
       (2 + 2 = 4)
    ]

Another goal for a test enhancement would be to make it so that within a BLOCK!'d group of tests, system state was preserved...that they would all run bound into the same new context.  This means that earlier GROUP!s containing test code could set up variables that would be used in subsequent tests.  But each BLOCK! would be considered independent.

**Comment by hostilefork** [comment]
@codebybrett, I wanted to go ahead and get your tests added and try and get these date things resolved:

https://github.com/codebybrett/reb/blob/master/test/dates.test.reb

They rely on this principle of the multiple test group, which I think is a good idea.  So that's what got me to thinking about the format modification to support it.

**Comment by codebybrett** [comment]
Looks like a plan.

Steps as I see them:

* First just convert tests for each file listed in %core-tests.r from BLOCK! to GROUP! and update the existing two parsers with no semantic changes and see how that goes.
* Leave the simple conversion function in the test-parsing.r file as a convenience for developers to convert their own code bases.
* Update the parsers to support BLOCK! as grouping mechanism.
* Modify test execution to support private state in BLOCK!'d group of tests.

Have you done anything yet, or would you like me to start?

**Comment by codebybrett** [comment]
I have gone ahead with [the first two steps ](https://github.com/codebybrett/ren-c/commit/8bf2781165411bd70c7020ab3f9c8873dfdf6c2c) - except I do the conversion in-memory as the tests are run. All tests pass.

I thought it would be interesting to load the log file and compose it.  But,  that raises an assertion.

**Comment by hostilefork** [comment]
You guessed correctly that I had not started, so good work!  :-)

> Somewhat off-topic for this issue: I thought it would be interesting to load the log file and compose it.

Sounds on-topic and like a good test to be running.  It wasn't too far from working, but exposed an over-reaching assert and a bug, both fixed here:

https://github.com/metaeducation/ren-c/commit/3aee9f9dca1fc0035c5c3768c44ea4d9cb4fd4dd

> Modify test execution to support private state in BLOCK!'d group of tests.

The private state issue is one of those "big picture, do we even know how to do this in Rebol" things.  One idea would be to make them run as the body of a MODULE, and piggy back on "however that works" *(hand-wave)*.  But then the tests wouldn't be very helpful at giving you the basic first steps in finding bugs that would help you debug code implementing modules, which can be annoying if trying to use the tests to vet major changes e.g. UTF-8 Everywhere.

I guess the idea thus being that there might be simpler and more complex test running modes, so you'd be able to ask for isolation or not?

We can let this bit go for now, I guess the point just being that a BLOCK! seemed like maybe it would be a good unit for isolating state.  If you need isolation-within-isolation, you could presumably do that too:

    [
       (x: 10)
       [(not set? 'y | 20 = x + y: 10)]
       [(not set? 'y | 30 = x + y: 20)]
    ]

> Steps as I see them:

If it's not too much trouble to find the tests that start with ISSUE! where it means to be a bug number and get that out of the test and into a grouping block that would be nice.  Right now they're mixed up with tests that legitimately begin with ISSUE! :-/  One way to maybe find them would be to DO/NEXT a test starting with ISSUE!, and if you get that same ISSUE! back after the DO and it only moved one unit, then it means it's inert and is almost certainly added as one of these indicators...

**Comment by hostilefork** [comment]
Actual tangent: which is that I was thinking about generative tests...where you want the log to contain a long list of the tests it ran, but you want to write the code that makes them.

So instead of writing **(1 < 10) (2 < 10) (3 < 10) ... (9 < 10)** you could specify a test generator that would do that, submitting its tests.

There are probably a few ways to approach this.  One could be to say that it's at the file level, and so files are either *lists of literal tests* or a **script that generates the list**.  This could mean a difference in the dialect between:

    %hijack.test.reb
    do %hijack-test-generator.reb

Maybe a keyword like DO is the best way to say it, but I don't know.  In any case, it would be nice because some of these test files are awfully manual.

**Comment by hostilefork** [comment]
One slightly lame aspect of this change is that it causes more indentation than one would like if one uses a regimented style:

    [
        #2086
        (
            bind next block: [a a] use [a] ['a]
            same? 'a first block
        )
    ]

So this suggests maybe being a bit more flexible in style, e.g.

    [#2086 (
        bind next block: [a a] use [a] ['a]
        same? 'a first block
    )]

**Comment by codebybrett** [comment]
I think you're second option is probably best out of those examples.  Probably even if there's titles and comments - something close to that. I assume the full version will be rare. E.g:

    [ {Title...}
    #2086 ; Notes about this...
    (
        bind next block: [a a] use [a] ['a]
        same? 'a first block
    )]

I've added flag as tag! to my changes.

I extracted comments with a #"#" in them. There's roughly just over 200 bug numbers in comments, most without notes, some with the note before, some after. Like:

    bug#1756
    bug#19 - but duplicate specializations currently not legal in Ren-C
    This is because of the COMPLEMENT problem: bug#1085.
    -- #1760 --
    bug#892, bug#216

One or few of these:

    -- CC#2101, #1434

Maybe four of these:

    RAMBO #3518

To convert comments that have bug#9999 and a note after it to an issue #9999 with a comment should be straightforward, the rest I could probably just log.  I'm presuming you're going to want to encode these as actual issues.

I Haven't looked at the ones encoded as an actual ISSUE! type yet.

Should Rebolbot be the owner of the bulk change?  If so, I'll see if I can PR parser changes first using in-memory conversion (but showing up in the log like my first commit did) and then separately the bulk changes.

**Comment by hostilefork** [comment]
> Should Rebolbot be the owner of the bulk change?

It doesn't really matter.  Though it would be nice to know that RebolBot was still around and could have commits attributed to it if desired.

But I was motivated to start attacking and doing triage on tests, so if you could wait until I've committed that to run the process that would be ideal.  I hope to be done soon...well, I very much hope so, but it involves fixing bugs and writing things up all over the place.  :-/

**Comment by codebybrett** [comment]
Will wait until you're ready.

I have some [draft tests](https://github.com/codebybrett/temp.201803-test-format/tree/master/tests) to peruse.

Tests like those for Decompress needed some extra newlines:

    ; functions/string/decompress.r
    [#1679 ; "Native GZIP compress/decompress suport"
        ("foo" == to string! decompress/gzip compress/gzip "foo")
    ]
    [#1679 
        ("foo" == to string! decompress/gzip #{1F8B0800EF46BE4C00034BCBCF07002165738C03000000})
    ]
    [#3 
        (error? try [decompress #{AAAAAAAAAAAAAAAAAAAA}])
    ]

**Comment by hostilefork** [comment]
Draft tests look great.

I've got all the tests I was messing with triaged and committed now, so there's no more %pending-tests.r or %r2-tests.r.

So ready to run...

**Comment by codebybrett** [comment]
Cool. I'm still ironing out a few things and have yet to think about how to verify that I haven't dropped or invalidated any tests inadvertently.

**Comment by codebybrett** [comment]
I'm stuck on a parsing bug and wonder whether you'd be willing to bring a fresh pair of eyes to the problem.

It's WIP code, I'm trying to get the parser for the grouped tests working. The problem is when I run the code to collect the tests from %core-tests.r.  It parses the first test file %parse-tests.r, fails on return from that.

To me, it looks like the parsing position is in %parse-tests.r instead of being in %core-tests.r but if that is true I don't know why - maybe I'm too close to the problem.

My branch: https://github.com/codebybrett/ren-c/tree/convert-tests

From the tests folder:

    do %test-parsing.r
    collect-tests test-sources: copy [] %core-tests.r

I probe positions PP1 and PP2, in between is the tokens parsed from the parse-tests.r file.  Shouldn't PP1 and PP2 show the same thing?

**Comment by hostilefork** [comment]
> Shouldn't PP1 and PP2 show the same thing?

Since nothing setting the parse position between them, then yes they should...*if they were a matched pair*.  But if you're dealing with recursions and an unmatched pair, no...you might see a PP1 from an outer recursion, then another PP1 before you've seen a PP2 yet...

> To me, it looks like the parsing position is in %parse-tests.r instead of being in %core-tests.r 

It seems to me that your parsing rule is based on `value`, which comes from manual transcoding of a `position` in a series.  position is not always in sync with the parse position, it will only be in sync whenever you reposition the parse via **:position** or capture where it is with **position:**.  So if you depend on external variables like that, parse isn't going to update them for you...they're going to get updated whenever code changes them.

Since your value is coming from this kind of "outsider" transcode, it isn't keeping up with the abovementioned recursions.  Instead of picking up at the offset you wanted into %core-tests.r, you are getting that offset into %parse-tests.r... about 950 characters in.  :-/  Just enough to skip the header comment in %core-tests.r, but land you in the middle-of-a-test in %parse-tests.r.

At least, I think that's what's going on?

**Comment by codebybrett** [comment]
Thank you for looking into it.

> Instead of picking up at the offset you wanted into %core-tests.r, you are getting that offset into %parse-tests.r... about 950 characters in

Ahh, hm.  Yes does look like a bug it. It seems to remember the index but not the underlying series and yet though the variable should be local to the procedure.

I've attempted to narrow it down with a little script. Not sure if it's the same problem or not, but I've raised an issue:  https://github.com/metaeducation/ren-c/issues/764

**Comment by codebybrett** [comment]
Getting into bed is good for bug fixing... I think I know what the problem is - quite likely my bad.  Will check it in daytime.

**Comment by codebybrett** [comment]
My bug confirmed. I normally try to make transactional changes to code, but bunched too many things together and forgot that I'd introduced a buffer.  The buffer was being shared and not copied. If I'd only LOCK'ed it, I wouldn't have wasted so much time.

**Comment by hostilefork** [comment]
> If I'd only LOCKed it

That's a good data point (and I actually, same night as you said "going to bed might help..." stayed up hours doing stuff I undid the next morning.

I resurrected Draem and posted to blog.hostilefork.com with r3-legacy revived.  I think it's better to auto lock keys in map appends, all things being equal.  Agree?

**Comment by codebybrett** [comment]
> I think it's better to auto lock keys in map appends, all things being equal. Agree?

Haven't looked at maps until this question.  At the user language level it seems limiting that keys must be immutable. Peering past the abstraction obviously hashing is non-trivial (though rdbms manage to have updateable indexes).   But if this abstraction requires immutable keys then auto locking them on append to the map seems reasonable. Comes down to when does the system get noisy when you do something wrong.  I don't have the experience to say.

**Comment by codebybrett** [comment]
PR: https://github.com/metaeducation/ren-c/pull/766
