### ISSUE TITLE
Series leak detected on Prep_Bin_Str()

### ISSUE THREAD

**Issue by meshpoint** [metaeducation/ren-c#76]
When a conversion is needed, Prep_Bin_Str() creates a temporary series, which in some cases considered leaked. Examples:

    decloak #{00} "^(100)"
    encloak #{00} "^(100)"
    compress "^(100)"
    construct "a: {^(100)}"
    debase remove "^(100)1234"
    make block! "{^(100)}"

**Comment by hostilefork** [comment]
Thanks for the report.  These are some pretty squirrelly routines...for the "sake of efficiency" returning a result in a global buffer "BUF_MOLD" sometimes, and sometimes not.  So a series you got from a previous call could change out from under you on the next call.  :-/

I'll have to look at the callsites and see what a reasonable response is.  I'm tempted to have it never return a shared buffer...guess I'll have to see what the impact of that would be.

**Comment by hostilefork** [comment]
689d2fc fixes the above cases.  The UTF-8 from any-string variant always allocates an new/unmanaged series, while the Prep_Bin_Str oddity is renamed to Temp_Bin_Str_Managed to indicate whatever you get back is managed already. 

I think I've inched it a bit closer toward comprehensibility *(and less need for "WARNING!" comments at callsites, which I never like, for many reasons.  Including: "what if someone calls it and forgets to put the comment?")*  But feel free to improve further...
