### ISSUE TITLE
Multi-line BINARY! literals not tolerated in multi-line console input

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#775]
An unpaired `{`, `[`, and `(` give back specific errors which are recognized by the console, as being errors which adding more lines of input may be able to resolve.  Hence multi-line input is continued.

Failure to be able to completely load a multi-line BINARY! gives a different kind of error:

    ** Syntax Error: invalid "binary" -- "#{"

This needs to be added into the "mismatched pairings" category of errors, so that the console can accept more input (as well as alter the prompt to note that it is a binary literal that needs to be completed next).

**Comment by Oldes** [comment]
Hm... I was just giving a try to the recent Ren-C and hit this issue immediately. Looks like you already know about it ;-)

**Comment by hostilefork** [comment]
Resolved here, was actually pretty trivial when I got around to looking at it:

https://github.com/metaeducation/ren-c/commit/1212792b4998fedcfd38c538f1133dfa8c09278c
