### ISSUE TITLE
FOR enters infinite loop when (end < start)

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#777]
Just pulled and built up to commit https://github.com/metaeducation/ren-c/commit/a5e950b6321757020d0268c8ad951a0935dca39c and discovered that an infinite loop is entered with this:

    for i 1 0 1 [dump i]

A test for the expected behaviour could be:

    (
        num: 0
        for i 1 0 1 [
            num: num + 1
            break
        ]
        num = 0
    )

**Comment by hostilefork** [comment]
Whoops.  Here's a believed fix, feel free (as always) to write more tests.  :-)

https://github.com/metaeducation/ren-c/commit/9774d51299ab8167f56fd452766d5b1d23459849

Also, if you've got anything blocking you in general for something you would use on a regular basis (ODBC, etc.) let me know.  Trying to unblock things like Graham's drone project, just getting more usage and feedback would be helpful.
