### ISSUE TITLE
DELETE causes internal error

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#789]
On windows 10, as at commit https://github.com/metaeducation/ren-c/commit/e7c77338b157e5de665b0903afa9348d3cff948e

    delete %tf.txt

causes

    >> delete %tf.txt
    Make_Series()x1 without Free_Series or MANAGE_SERIES
    C Source File ..\src\include/sys-do.h, Line 275, Pointer 0542C9D0
    At evaluator tick: 281598
    unmanaged series was likely created during evaluator tick: 281595
    C Source File ..\src\core\m-series.c, Line 492, Pointer 0064B320
    At evaluator tick: 281598
    Rebol Internal Error
    If you need to file a bug in the issue tracker, please give thorough
    details on how to reproduce the problem:

        https://github.com/metaeducation/ren-c/issues

    Include the following information in the report:

    Executable not built with DEBUG_SERIES_ORIGINS, no more info

**Comment by hostilefork** [comment]
That was [one small line of problem](https://github.com/metaeducation/ren-c/commit/20f64be4519e9e6a852329088ec115546abba828#diff-1a39df1d780002dae68d3c3a35ecc4beR555) which I just tacked into a commit which was seemingly ready to commit...but forgot that it hadn't passed Travis, and then there were FFI and user native TCC issues and bugs to hunt for... enough I had to cook up a whole new debugging tool to find the problem.

So lesson learned.  Anyway, these shouldn't be seen as intrinsic bad stability problems... the API could GC these things (and will in release mode).  It's just that the core is trying to be sensitive to not accumulating junk; easier to relax a strict rule later.
