### ISSUE TITLE
a read on a malformed http server response creates an error

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#805]
The Rebol2 tiny webserver seen here http://www.rebol.net/cookbook/recipes/0057.html and in the library produces malformed responses which kill the client.  However, the rebol2 and cURL clients can read the responses fine.

The issue is that the tiny webserver uses "^/" instead of "^M^/" and the prot-http looks for "^M^/" which it can't find.

So we get this type of error

<pre>
>> page: read http://localhost:8000/index.html
ⓘ   Note: use WHY for error information
** Access Error: protocol error: "Server closed connection"
** Where: fail switch take* any unless awake switch switch take* any unless _ wake-up either while-not _ wait while-not sync-op else _ read _
** Near: [... _
    fail error ~~]
** File: tmp-host-start.inc
** Line: 1207
</pre>

**Comment by hostilefork** [comment]
> However, the rebol2 and cURL clients can read the responses fine.

I suggest in these matters to not sweep them under the rug.  If there's a documented format, and people are breaking it, then erroring is good.  One should have to configure to run in a permissive mode to allow it.

But an error that doesn't say what went wrong is bad.  There needs to be some way to enable permissive options for bad servers, and give messages.  The message should direct people to how--if they must--they can configure to tolerate the condition.

**Comment by gchiu** [comment]
Maybe something like this might work

instead of

<pre>
if all [
		not headers
		d1: find conn/data crlfbin
		d2: find/tail d1 crlf2bin
	]
</pre>

try this

<pre>
if all [
		not headers
		any [
			all [
				d1: find conn/data crlfbin
				d2: find/tail d1 crlf2bin
			]

			all [
				d1: find conn/data #{0A}
				d2: find/tail d1 #{0A0A}
			]
		]
	]		
</pre>

**Comment by gchiu** [comment]
That was committed and solves the issue.
