### ISSUE TITLE
Error "Cell address 006901F4 not aligned to 8 bytes"

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#809]
Windows 7 x64 and mingw for x86 with config.r:

```
os-id: 0.3.1
toolset: [
    gcc %gcc
    ld %gcc; linking is done via calling gcc, not ld
    strip %strip
]
```

$ r3.exe

> Cell address 006901F4 not aligned to 8 bytes
> C Source File ..\src\core\b-init.c, Line 753, Pointer 006901F4
> At evaluator tick: 0
> Kind=51
> No containing series for value...panicking to make stack dump:

**Comment by no-e-in** [comment]
It is old version (contained in MLton-20100608-1.exe) that, up to 3-4 months ago, compiled both Ren-C and R3:
> $ gcc --v
> Using built-in specs.
> Target: i686-w64-mingw32
> Configured with: ../../../build/gcc/gcc/configure --target=i686-w64-mingw32 --pr
> efix=/g/buildbot/vista64-mingw32/mingw-x86-x86/build/build/root --with-sysroot=/
> g/buildbot/vista64-mingw32/mingw-x86-x86/build/build/root --enable-languages=all
> ,obj-c++ --enable-fully-dynamic-string --disable-multilib
> Thread model: win32
> gcc version 4.4.3 20091023 (prerelease) (GCC)

If it's too old version, I'll close the issue.

**Comment by hostilefork** [comment]
As far as I can tell, this is a compiler bug--it's doing something flat-out wrong.

Somehow it's not aligning doubles to 64-bit boundaries, even when you use `-malign-double`.  [It is supposed to](https://stackoverflow.com/a/11110283/211160):

> "Windows uses 64-bit alignment of double values even in 32-bit mode"

I tried creating a smaller example that would reproduce the effect, but it didn't.  It would be a bit of an endeavor to pare away bits of Rebol to find exactly what about the situation makes this happen.

What I've done for the moment is disable the check on GCC on Windows for versions of GCC less than 5:

https://github.com/metaeducation/ren-c/commit/d40702b422ae077cb358351b1bc4b1fa9adfbeb0

R3-Alpha wasn't remotely alignment-sensitive, so it's certainly no worse.  I doubt there will be any consequences you'd notice on an x86...if it seems to work for you, I'll consider it closed.

**Comment by no-e-in** [comment]
> $ r3
> Rebol 3 (Ren-C branch) [version: 2.102.0.3.1 build: 4-Jun-2018/20:25:05]

Thank you.
 Hostilefork, I'm sorry I wasted your time with an old version of the gcc.

**Comment by hostilefork** [comment]
> Hostilefork, I'm sorry I wasted your time with an old version of the gcc.

Not a problem; it's actually good to keep things building with old versions.  I like to think of it as a "time-traveling artifact", that could have been written back in 1989, but just wasn't.  Part of the whole "Amish Programming" idea.  :-)
