### ISSUE TITLE
Read behavior change with ^M characters

### ISSUE THREAD

**Issue by johnk-** [metaeducation/ren-c#819]
Using a recent ren-c build ^M characters are not converted when reading text from a file.

ren-c build 15-May-2018

    >> to-string read %file.txt
    == {show run^M
    ...

Older builds including rebol3 and rebol2 automatically translate line endings.

ren-c build 10-Aug-2017

    >> to-string read %file.txt
    == {show run
    ...

**Comment by hostilefork** [comment]
The thread covering this issue is here:

  https://forum.rebol.info/t/fight-for-the-future-how-deline-will-save-us-from-cr-lf/1264
