### ISSUE TITLE
exists? %/ returns null

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#833]
Should be **dir**

Note: **load %/** works as expected

**Comment by hostilefork** [comment]
As it's from R3-Alpha, opened an issue there:

https://github.com/rebol/rebol-issues/issues/2316

But tried to address it in this commit:

https://github.com/metaeducation/ren-c/commit/00a4cabff9b042cf498d008f56e3d01e83347deb

Let me know if it doesn't work...!

**Comment by giuliolunati** [comment]
It works, thanks!
