### ISSUE TITLE
Serial on Windows currently not working

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-c#84]
I believe as of commit 734f1ceb8a091cde7255777ef6b563daa7aa5ad0 serial code is not functioning due to the path being concatenated with both single byte characters as well as wide characters.  Before this difference between the OSes was handled using a macro `TO_OS_STR` which would use `mbstowcs` for Windows and `strncpy` for other OSes.

I'm not really sure the best method for resolving this, but I see at least a couple options.
1.  Create a similar macro to before with a better name `OS_STRCONVERT` ?  This would ideally fix the other place `TO_OS_STR` had been used.  Is there a problem with it?
2. As @hostilefork [suggested](http://chat.stackoverflow.com/transcript/message/25491303#25491303), a solution involving  using "`Value_To_OS_Path` first, then copy the data from that, then `Free_Series` on the series `Value_To_OS_Path` "
3.  Modify [/src/os/windows/dev-serial.c](https://github.com/metaeducation/ren-c/blob/master/src/os/windows/dev-serial.c#L129) to use single byte characters for this.   Is it possible for a serial path to contain non-native characters?   `serial://com1/38400`

**Comment by hostilefork** [comment]
My slight preference for fixing the cases with #2 comes from having wanted this interface "quarantined" so the fewer of these functions, the better.  But I don't have a big problem with #1, and it's what I would have almost certainly have done if I had realized the difference.

**Comment by kealist** [comment]
There seems to be another issue that causes `Set_Serial_Settings` in `/src/os/windows/dev-serial.c` to fail.  Trying to track it down, but haven't had success isolating it yet.

**Comment by kealist** [comment]
Here is some test code from @zsx just as a reference:

	gs: open serial://ttyUSB0/57600
	written: false
	gs/awake: func [evt][
		 switch evt/type [
			  read [
					print to-string evt/port/data
					read evt/port
					return true
			  ]
			  wrote [
					 written: true
					 return true
			  ]
		 ]
		 false
	]
	write gs "m"
	while [not written][
		wait [gs 1]
	]
	read gs
	wait [gs 1]

**Comment by hostilefork** [comment]
I have a goal to clear out the issues to zero... I'm willing to take inefficient solutions if they work!

It would also be nice if there could be a wiki page on how someone might use the serial code, to confirm.  And even answers to some of those basics like "can it work with USB", anything to clarify the limits and what works.  There's some notes here a page Brett has up:

http://www.codeconscious.com/rebol/rebol-net.html#SerialPorts

If Atronix uses the serial stuff with their devices, maybe Shixin could help with verification.  Anyway, let me know if there's anything I can do to help close the issue...!

**Comment by kealist** [comment]
There is a fix already. I just hadn't had a chance to test it on linux yet.  I will get to that in a day or two.  I ended up needing to reinstall OS again.

[https://github.com/kealist/ren-c/commit/6e4c7671d2d8be3ebf8bcdae0127565db6e017b7](https://github.com/kealist/ren-c/commit/6e4c7671d2d8be3ebf8bcdae0127565db6e017b7)

**Comment by kealist** [comment]
Seems to generally be resolved.  I'm closing this and may open other issues that are different as I can isolate them.
