### ISSUE TITLE
Bug accessing decimal content in vector

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#842]
Let `v: make vector! [decimal! 32 [1.0]]`, then `print v` => `1.0`, ok.
But `print v/1` => `3.03865e-319`

Happens on Android and Linux.

Probably an [endianness issue](https://stackoverflow.com/questions/15390007/array-communication-convert-c-doubles-to-chars-then-java-bytes-to-doubles?rq=1)

**Comment by hostilefork** [comment]
> Probably an endianness issue

Yup.  Looks like the vector code used ["type punning" via a union](https://en.wikipedia.org/wiki/Type_punning) as a way of putting various types of floats and integers into a uint64_t.  It's risky, illegal in C++, and there's no reason to do it here.  There's already an abstraction in the system that can hold "either an integer or a decimal".  It's called a REBVAL (!)

(There might have at one time been some idea that "initializing a whole value" would be inefficient to pass around somehow.  I don't know.  But most of the time it's reading the information into a value anyway.)

Went through and changed it, resolving this bug...as it always reads and writes the data type for the vector through the same pointer type:

https://github.com/metaeducation/ren-c/commit/86cc82000dc6a80ba0ac1fa3b3fc7f08d7630493

Also added some overflow checking while I was at it:

    >> v: make vector! [integer! 8 [1 127 128 2]]
    ** Error: 128 out of range for 8-bit signed VECTOR! type

Hopefully it's becoming more comprehensible (!).  Ultimately I do want to see this moved into user defined types, using the API, etc.  Look how it delivers the out of range error...

https://github.com/metaeducation/ren-c/blob/master/src/core/t-vector.c#L225

**Comment by giuliolunati** [comment]
Ok, well done!
