### ISSUE TITLE
Bug in dehex

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#856]
`dehex "%2b%2b" -> "+^@"` while "++" was expected.
The same with many other `%xx%xx` sequences.

**Comment by hostilefork** [comment]
Fixed, I think...

https://github.com/metaeducation/ren-c/commit/bc9bdff99cb6e171d3d7bea2c9ba49d921465fc1

A bunch of this is different in UTF-8 Everywhere.  Which will be committed, someday!

**Comment by giuliolunati** [comment]
Ok, thx!
