### ISSUE TITLE
call is failing 

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#857]
**    Version:   2.102.0.3.40                                           **
**    Platform:  Windows win32-x64                                      **
**    Build:     2-Oct-2018/16:21:34                                    **
**    Commit:    b5ea39ec50aac6c5176905c474d58ecc52589eaf

> call "pdftk" 

and I get a stopped working error.

PDFtk is here but it is happening with other calls as well

https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/

**Comment by hostilefork** [comment]
Fairly simple bug, affecting uses of CALL which did not also use /SHELL:

https://github.com/metaeducation/ren-c/commit/814c2187ef1343098b79df2b504c887b7aeed4ae
