### ISSUE TITLE
GET of zero-length PATH! (e.g. GET '/) does not work

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#864]
`x: 1 x: me / 2` => *Error: Cannot dispatch empty path*

**Comment by hostilefork** [comment]
> x: 1 x: me / 2 => Error: Cannot dispatch empty path

Here's a patch for that particular issue:

https://github.com/metaeducation/ren-c/commit/e20c4fec1d39156c2283fdaefc55bb56df81d52f

As a more general question, GET of a PATH! is expected to work in general.  It may be that the GET of a PATH! mechanic needs to come back with an ACTION! that does whatever a 0-length PATH! enfixedly does.

Thanks for the report, I'll keep this open and think about the bigger issue...

**Comment by hostilefork** [comment]
Ok, actually, I believe this solves the issue more elegantly:

https://github.com/metaeducation/ren-c/commit/468b888551d389858f3d688a65263fd4380626b1
