### ISSUE TITLE
broken IMPORT

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#891]
IMPORT is broken in 8259fe9;
worked in 6b587a4;
can't test in between

**Comment by hostilefork** [comment]
Be sure to submit a test case and the error message you are receiving.  Even if I can produce an error by messing around with IMPORT, it doesn't guarantee that would fix your error (!)

The following from the tests seems to work:

    (
        var: 1
        a-module: module [
            exports: [var]
        ][
            var: 2
        ]
        import a-module
        1 == var
    )

But I did find a potential problem here:

https://github.com/metaeducation/ren-c/commit/27505c7fd59be53bd385e1da17498912274d52ba

If that doesn't resolve it, let me know a test case or error message...

---

P.S. be sure to check out COLLECT-LINES and COLLECT-TEXT, now committed, they are very useful:

https://forum.rebol.info/t/collect-lines-an-adaptation-story/945

    >> collect-text [keep ["a" "b"] print "Hi!" keep if false ["c"] keep "d" keep ["e" "f"]]
    Hi!
    == "ab d ef"

    >> collect-lines [keep ["a" "b"] print "Hi" keep if false ["c"] keep "d" keep ["e" "f"]]
    Hi!
    == [
        "a b"
        "d"
        "e f"
    ]

This makes it easier to structure many things vs. using one giant SPACED or UNSPACED statement...

**Comment by giuliolunati** [comment]
Ok man, you fixed it!
+1
