### ISSUE TITLE
Unable to BIND a DOES value

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#894]
Manually binding an ACTION! created with DOES appears not to have any effect:

Example:

    profile: make object! [first: last: _ name: bind does [spaced [first last]] 'name]
    chris: make profile [first: "Chris" last: "RG"]
    chris/name ; //null

Commit: dcda199
Platform: 2.40

**Comment by hostilefork** [comment]
This doesn't reproduce for me :-/ ... here's what I get:

```
>> profile: make object! [first: last: _ name: bind does [spaced [first last]] 'name]
== make object! [
    [first last name]
    [
        first: _
        last: _
        name: make action! [[] [...]]
    ]
]

>> chris: make profile [first: "Chris" last: "RG"]
== make object! [
    [first last name]
    [
        first: "Chris"
        last: "RG"
        name: make action! [[] [...]]
    ]
]

>> chris/name
== "Chris RG"
```

Is there something perhaps in your setup that could be complicating the repro case?  If you start a session from scratch and paste the code, do you see something different?

**Comment by rgchris** [comment]
Yes—it does work for me in a new session. I'll need to look again to see if I can reproduce the other behaviour, but I guess it's fine.
