### ISSUE TITLE
Can't load %rebol.reb at startup

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#900]
If there's a %rebol.reb file (also if an empty one) in the same directory of the r3 executable then startup fails.
Appeared between a35b066 and 5c4dfd4.

Note: I really need a %rebol.reb to initialize system/options/module-paths

**Comment by giuliolunati** [comment]
Ok, sorry:


Script: Version: Date:
Startup encountered an error!
** Error found in rebol.reb script
!! use --verbose for more detail
PANIC ACTION! called (explicitly or by rebPanic() API)
C Source File (anonymous), Line 0, Pointer 0xb6441898
At evaluator tick: 175869
Series VARLIST detected.
...and that VARLIST is of an ERROR!...
**PROBE(Context Varlist, 0xb6441898): tick 175892 ../src/core/d-crash.c:170
make error! [
    [type id message near where file line arg1 arg2 arg3]
    [
        type: Script
        id: expect-arg
        message: [:arg1 "does not allow" :arg2 "for its" :arg3 "argument"]
        near: [... [
            print either o/verbose ...
        ]
            return [quit/with 1] ~~]
        where: [die _ then then _ entrap]
        file: tmp-host-start.inc
        line: 3571
        arg1: return
        arg2: block!
        arg3: state
    ]
]
C Source File ../src/core/m-series.c, Line 486, Pointer 0xb6f8f498
At evaluator tick: 175892
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:


Executable not built with DEBUG_SERIES_ORIGINS, no more info

**Comment by giuliolunati** [comment]
Sorry...

%rebol.reb is an empty file

The message is:


Checking for rebol.reb file in /data/data/com.googlecode.android_scripting/files/usr/bin/
Script: Version: Date:
Startup encountered an error!
** Error found in rebol.reb script
** Access Error: value is CONST (see MUTABLE): []
** Where: append trap then _ entrap
** Near: [...
    append o/loaded o/bin/rebol.reb ~~
    loud-print [...
** File: tmp-host-start.inc
** Line: 3571
PANIC ACTION! called (explicitly or by rebPanic() API)
C Source File (anonymous), Line 0, Pointer 0xb6441f50
At evaluator tick: 175890
Series VARLIST detected.
...and that VARLIST is of an ERROR!...
**PROBE(Context Varlist, 0xb6441f50): tick 175913 ../src/core/d-crash.c:170
make error! [
    [type id message near where file line arg1 arg2 arg3]
    [
        type: Script
        id: expect-arg
        message: [:arg1 "does not allow" :arg2 "for its" :arg3 "argument"]
        near: [... [
            print either o/verbose ...
        ]
            return [quit/with 1] ~~]
        where: [die _ then then _ entrap]
        file: tmp-host-start.inc
        line: 3571
        arg1: return
        arg2: block!
        arg3: state
    ]
]
C Source File ../src/core/m-series.c, Line 486, Pointer 0xb6f8b498
At evaluator tick: 175913
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:


Executable not built with DEBUG_SERIES_ORIGINS, no more info

**Comment by hostilefork** [comment]
Hopefully this takes care of it, at least the empty file case...!

https://github.com/metaeducation/ren-c/commit/2cf8b2dc75185444e761001d33dfb0eb81ea8d76

**Comment by giuliolunati** [comment]
Well done!
