### ISSUE TITLE
set non-existent word in object => segfault

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#907]
o: make object! [ ] o/i: 1

=> segmentation fault (also in debug build)

**Comment by giuliolunati** [comment]
The bug appears between a6e0c7c and bb988fd

**Comment by hostilefork** [comment]
Fixed here to raise an error, though it changes the GET-PATH! behavior so that it raises an error as well:

https://github.com/metaeducation/ren-c/commit/ec308ee6dc1800aaaa4c923d3e173c58d241c3a0

That is likely the safer policy than returning null on **obj/spelled-wrnog**
