### ISSUE TITLE
"help #issue" ** Script Error: free? requires value argument to not be null

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#921]
````
>> help #abc
Opening web browser...
ⓘ   Note: use WHY for error information
** Script Error: free? requires value argument to not be null
** Where: _ eval either collect if help console
** Near: [...
    if free? :value ~~ [
        keep "that has been FR...
** File: tmp-boot.r
** Line: 6664
````

Linux 64, from built from commit: fd316534af84b56059e89999a6b4fe489523b69c

**Comment by hostilefork** [comment]
Just a missing RETURN.  Fixed, and as a bonus, I added in PRINT NEWLINE as legal:

https://github.com/metaeducation/ren-c/commit/2054d94f6f414b57a52c8760562bc741d359e4e1

I'm not sure what the plan for HELP on an ISSUE! was, but your suggestion that these be used as a kind of "hashtag" in function specs is an interesting one.

I've invited you to join this GitHub group as a member, did you get the invitation?
