### ISSUE TITLE
WISH:  blanks in VARS arg for FOR-EACH and MAP-EACH

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#926]
Consider **map-each [dummy a b] [1 2 3 4 5 6] [a + b]** => **[5 11]**. I'd like to avoid the dummy word, writing **map-each [_ a b] [1 2 3 4 5 6] [a + b]**

**Comment by hostilefork** [comment]
I was going to move this to the Post-Beta/One milestone.  But then I thought more about it, and decided we should probably go ahead and have the feature, as it's kind of an important thinking point for the design of what an object *is*.

So your wish is granted!  :-)

https://github.com/metaeducation/ren-c/commit/c821d7cf406925cafec021471f831e1155775bfd
