### ISSUE TITLE
Bug in --

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#927]
`-- a quit` =>
** Script Error: while-not word is not bound to a context

`-- a` works well

**Comment by hostilefork** [comment]
`while-not [...]` now works fine as `while [not ...]`, so while-not is dead (I thought I'd deleted all of them, missed one somehow...!)

**Comment by giuliolunati** [comment]
Probably [fixed](https://github.com/metaeducation/ren-c/commit/b5656dbd5f17c797ad272db4ef92193fc3eb86f6)
