### ISSUE TITLE
TO-DATE X fails if X is DATE! 

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#928]
`to-date 1/1/2019` 
 ** Script Error: cannot use copy on date! value

**Comment by hostilefork** [comment]
Part of starting to rethink TO... it becomes a COPY.  Fixed for DATE + TIME here:

https://github.com/metaeducation/ren-c/commit/7f3f6b2f3e1746b61213de75f14437c68eeac6d3

If you have a list of thoughts on TO please add them to the forum!!

https://forum.rebol.info/t/justifiable-asymmetry-to-on-block/751/3?u=hostilefork
