### ISSUE TITLE
Large >32kb HTTP POST issue

### ISSUE THREAD

**Issue by johnk-** [metaeducation/ren-c#93]
Reproduce a failure on a large post to the github API (ref https://gist.github.com/jonmagic/5282384165e0f86ef105).
This may be an issue with the beta version of this API and not a Ren/C problem.

Error message as follows:
```
make error! [
    code: 516
    type: 'Access
    id: 'read-error
    arg1: tcp://api.github.com:443
    arg2: 104
    arg3: none
    near: [port]
    where: [read either switch function! wake-up if either while function! wait port? unless while sync-op either write write trap either try error? if do either either either function!]
]
```

Code to reproduce.
```rebol
rebol []
auth-token: "<insert auth token here>"
issue-api-url: https://api.github.com/repos/johnk-/impexptest/import/issues
if error? err: try [
    write issue-api-url compose/deep [
        POST [
            Accept: "application/vnd.github.golden-comet-preview"
            Authorization: (join "token " auth-token)
        ]
        (rejoin [
            "{" {"issue": } "{"
            {"title": "Imported from some other system",}
            {"body": "..."}
            "},"
            {"comments": [}
            "{"
                {"body": "} 
                collect [ loop 4000 [ keep "Padding it" ] ]
                {"}
            "}"
            "]"
            "}"
        ])
    ]
] [
    print mold err
]
```

**Comment by hostilefork** [comment]
> This may be an issue with the beta version of this API and not a Ren/C problem.

Is there by chance a quick way to test if that is the case, e.g. the request through curl or similar?

**Comment by earl** [comment]
Sending pretty much the same request to http://httpbin.org/post doesn't fail with above error. I take that as an indication that this is an issue specific to Github's API endpoint. Is, per any chance, the comment body >64k? Github's docs state:

> The body may be at most 65535 characters long.

**Comment by johnk-** [comment]
The issue I was trying to upload was http://curecode.org/rebol3/ticket.rsp?id=1993 so my test program does not exactly replicate the problem. I agree that this looks like an API issue, not a Rebol issue. For this single CC issue we may need to truncate some of the text and add it back in manually. I checked the sizes of the other tickets and this is the largest by far (~56KB in comparison to the next largest ~32KB which upload correctly).
