### ISSUE TITLE
KEEP in PARSE don't work with ANY, SOME, TO, THRU

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#937]
Similar to #935.
Easy workaround: enclose rule in block

**Comment by hostilefork** [comment]
Please give examples of what's not working, as simple examples seem to work.

 ‌   >> ‌parse "aaa" [collect x [keep some "a"]]
‌    == ""
‌
 ‌   >> ‌x
‌    == ["aaa"]
‌
 ‌   >> ‌parse "aab" [collect x [keep to "b"]]
 ‌   == "b"
‌
 ‌   >> ‌x
‌    == ["aa"]

**Comment by giuliolunati** [comment]
Sorry, my fault. Used old binary :-(
