### ISSUE TITLE
PARSE succeeds changing series mid-parse

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#938]
Using a Parse rule that changes to a new series returns as a success:

```
>> parse "a" [(foo: "Other Series") :foo]
== "a"

>> parse "a" ["a" (foo: "Other Series") :foo]
== "a"
```

**Comment by hostilefork** [comment]
Resolved with this commit, which adds MARK and SEEK:

https://github.com/metaeducation/ren-c/commit/15ee1bf5944aaf64befe5d30aea8a4e2d38ee36c

There's going to be additional good reasons not to allow series switching.
