### ISSUE TITLE
CALL/INPUT crashes the interpreter

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#940]
Using the /INPUT refinement with CALL crashes the interpreter:

```
>> call/input "foo" "Foo"
Segmentation fault: 11
$ 
```

```
>> call/shell/input "foo" "Foo"
Segmentation fault: 11
$ 
```

**Comment by hostilefork** [comment]
Believed fixed in:

https://github.com/metaeducation/ren-c/commit/3e5c1acc76cb650540739c0bab59966bf783d800

CALL could use tests, but we don't have good cross platform ways of testing it.  draegtun made some things where it would assume it could run Rebol from the boot path, and that would be available regardless of platform...then made scripts to call that would test whatever the thing to test was.

Feel free to look into that.  :-)

https://github.com/metaeducation/ren-c/tree/master/tests/call

**Comment by rgchris** [comment]
Has the return value for CALL changed? Doesn't appear to return the shell exit code.

**Comment by rgchris** [comment]
Is still broken for BINARY! input:

```
>> call/input "foo" #{DECAFBAD}
Segmentation fault: 11
```

**Comment by hostilefork** [comment]
> Has the return value for CALL changed? Doesn't appear to return the shell exit code.

Shixin made it return the process ID if you didn't explicitly ask for a /WAIT.  That didn't seem to make a lot of sense to me; I lean to thinking synchronous defaults are better.  (If we went the JavaScript route you would have to do everything with an AWAIT, and it's kind of laughable how broken that is even if you think you're willing to use it.)

As you have a vested interest, I think articulating what you think the story should be would be good.  Though what a "call port" might look like should be discussed...how you might look at a conversation with a process as being like a conversation with a server, and use the same kind of code to work with it.

> Is still broken for BINARY! input

It's a big undertaking to add tests of untested features and expecting them to work on all platforms.  Which is a reason why features should come with tests in the first place.  :-/  Windows had quite a number of problems--I mentioned in chat that it had never been tested on unicode code paths, and with the UTF-8 everywhere transition now *every* code path is unicode-aware/concerned.

But just for you, I took a day and hammered on the whole thing significantly.  It should be easier to work on now and deal with issues and improvements.

The tests I added show some of the power of enclosing/specializing.  The ECHOER specializes CALL with a command, and then the encloser changes it to return whatever you said the output was:

    (did echoer: enclose specialize 'call/shell/wait/input/output [
        command: spaced [
          file-to-local system/options/boot
          {--suppress "*"} {-qs} {--do} {"write-stdout input quit"}
        ]
    ] function [f [frame!]] [
        out: f/out
        do f
        return out
    ])

    ("Foo" = echoer "Foo" "")
    ("Rҽʋσʅυƚισɳ" = echoer "Rҽʋσʅυƚισɳ" "")
    ("One^/Two" = echoer "One^/Two" "")

    (#{466F6F} = echoer #{466F6F} #{})
    ("Foo" = echoer #{466F6F} "")
    (#{466F6F} = echoer "Foo" #{})

> *Since you can see that testing can be fun, perhaps you would like to write more of them.  :-)  I would also like to see a test format extension so that the test can be a test generator.  Something like:*
>
>     #generator (collect [
>          for-each x [1 2 3] [
>              keep/only compose [(x) = (x)]
>          ]
>     ])
>
> *...this would allow it to feed back in such a way that the test report could still show you which specific test failed, with the source of that test in the log.)*

**Comment by hostilefork** [comment]
A rebol-issues issue about CALL from back when, worth looking at and forming an opinion on:

https://github.com/rebol/rebol-issues/issues/2225

**Comment by rgchris** [comment]
> Shixin made it return the process ID if you didn't explicitly ask for a /WAIT. That didn't seem to make a lot of sense to me; I lean to thinking synchronous defaults are better. (If we went the JavaScript route you would have to do everything with an AWAIT, and it's kind of laughable how broken that is even if you think you're willing to use it.)

I guess that makes sense. I don't use CALL without WAIT thus didn't recognise that behaviour.

> As you have a vested interest, I think articulating what you think the story should be would be good. Though what a "call port" might look like should be discussed...how you might look at a conversation with a process as being like a conversation with a server, and use the same kind of code to work with it.

I'd very much be interested in this as a long-term goal. I don't know enough about managing/communicating with processes to understand the mechanics of that and how much it'd rely on the 'server' process.

At this point, I care more about synchronous leverage of system resources—whether that's using **curl** to prototype HTTP exchanges or ImageMagick to do some elemental image processing (in Rebol 2, I have an embryonic dialect for scripted image processing using CALL as the interface).

> But just for you, I took a day and hammered on the whole thing significantly. It should be easier to work on now and deal with issues and improvements.

I do, as ever, greatly appreciate it :D  CALL isn't exactly a *pure* component of the exercise, but does permit a degree of pragmatism.

>```
> ("Foo" = echoer "Foo" "")
> ("Rҽʋσʅυƚισɳ" = echoer "Rҽʋσʅυƚισɳ" "")
> ("One^/Two" = echoer "One^/Two" "")
> 
> (#{466F6F} = echoer #{466F6F} #{})
> ("Foo" = echoer #{466F6F} "")
> (#{466F6F} = echoer "Foo" #{})
> ```

Only one I would add—and may be problematic as INPUT only returns TEXT!—is:

```
(#{DECAFBAD} = echoer #{DECAFBAD} #{})
```

**Comment by rgchris** [comment]
```rebol
echoer: enclose specialize 'call/shell/wait/input/output [
    command: spaced [
        file-to-local system/options/boot
        {--suppress "*"} {--do} {"write-stdout read system/ports/input"}
    ]
] function [frame [frame!]] [
    out: frame/out
    do frame
    return out
]

probe ("Foo" = echoer "Foo" "")
probe ("Rҽʋσʅυƚισɳ" = echoer "Rҽʋσʅυƚισɳ" "")
probe ("One^/Two" = echoer "One^/Two" "")

probe (#{466F6F} = echoer #{466F6F} #{})
probe ("Foo" = echoer #{466F6F} "")
probe (#{466F6F} = echoer "Foo" #{})
probe (#{DECAFBAD} = echoer #{DECAFBAD} #{})
probe (error? trap [#{DECAFBAD} = echoer #{DECAFBAD} ""])
```

**Comment by hostilefork** [comment]
> CALL isn't exactly a pure component of the exercise, but does permit a degree of pragmatism.

You're not wrong.  All the technical leaps of the evaluator are wasted if it doesn't demonstrate virtuosity in these areas.

So I decided to take another day out of my life *(again, I hope we are experiencing mutual respect on that :-P)* to totally kill it, [using your backtracking COLLECT design, no less](https://github.com/metaeducation/ren-c/commit/97b6ed79869650e4843adc24ef04700cd6955cb4#diff-7cdd06b7da56f33d3e8bf14bb8ec2f49R60).

Closing this issue, please raise any new ones (+ patches) if you find any fault with the solution.
