### ISSUE TITLE
Should round change the datatype?

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#956]
>> round/to $1.129 .01
== 1.13

changes money! to decimal!

**Comment by hostilefork** [comment]
This is in R3-Alpha and appears to be intentional.

https://github.com/rebol/rebol-issues/issues/1470

If you use $.01 it works.

    >> round/to $1.129 $.01
    == $1.13

As with many things about these data types, I don't really know if that seems right or not.

**Comment by Oldes** [comment]
I would say that it's a bug and should be fixed. And there is more issues with `round`, like:
```
>> round/even/to 2.55% 0.1
== 000%
```
(don't know if it has own issue)

**Comment by Oldes** [comment]
On the other side, the original code is quite clear, that the behaviour is intentional:
https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/t-money.c#L176-L188

**Comment by hostilefork** [comment]
Matters of this type have come up before (e.g. "why is $10 / $2 = $5... shouldn't it just be 5?").  Reasoning for the behavior is generally based on precision.

If you were going to round a money to a decimal, you would have to first convert the decimal to a money and then round using that.  That conversion is lossy, meaning you may not be rounding to what you thought.  So by making it match the type of the rounding, the user of the round is informed whether they matched the precision of their original value type.

While this is a "rational" line of perspective when viewed in a certain light, I think that the behaviors of MONEY! are generally "weird".  [It's a bunch of original code](https://github.com/rebol/rebol/blob/master/src/core/f-deci.c) with no maintainer.  Most people seem fine with Excel using IEEE double precision for calculation, and that's built into C:

https://en.wikipedia.org/wiki/Numeric_precision_in_Microsoft_Excel

So for a codebase which is supposed to focus on minimalism, the "doing better financial calculations than Excel" is a very weird pitch.  I think people would be more uncomfortable that it's using completely original math code--not vetted by any third party--than worrying they might be off by a penny when rounding hundreds of billions of dollars.

Hence these issues in the name of "consistent rounding" may not be as sensible as dropping the deci type altogether.
