### ISSUE TITLE
Need to remove bootstrap binaries from %make/

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#969]
When Shixin introduced rebmake, it was no longer possible to bootstrap with the R3-Alpha executables off of rebolsource or rebol.com.  Ren-C had reached a point where it was overall more stable than R3-Alpha, so that wasn't a huge issue.  *(It has not been a problem, and we're long past the point of considering backward compatibility of the make process running in R3-Alpha.)*  But it raised the question of where Travis (or your average user who is building) would be getting a Ren-C executable from.

For expedience, he just picked a few builds that Travis would use and put them in the %make directory.  I was skeptical of this, but it did have some advantages.

But we need to move away from this, and get bootstrap executables hosted in a known location (e.g. we have S3 and have been using it successfully for a while).  I had been dragging my feet on worrying about it, but [the recent request to add a build for OpenBSD](https://github.com/metaeducation/ren-c/pull/968) provoking the issue.  I'd rather we adjust the build process to get the builds from another location and take the existing ones out than keep adding.

**How can we make it as easy as possible for users to build when their `git clone` did not give them an executable?**

@giuliolunati has set it up so that "out of source" builds are possible, you can use *any* directory to build in.

I feel like putting a `makefile` and `make.bat` in the *root directory* of the repository--that don't actually build anything but give people instructive messages of exactly what to download and type--would probably make sense.  Then we can also put the make.r there, but have it default to putting its build products into a `build/` subdirectory...which is empty (or missing) by default, and would be `.gitignore`'d.

It would be suggested that the user put r3-make in the build directory (or somewhere else on their path).

So this would likely mean moving the `make/tools` directory to the root `tools`, and `make/configs` to the root `configs`.  It may be that the `.gitignore` could default to ignoring `config.r` in the root directory, and the first time you build if it doesn't find a config.r and you don't specify one, it copies/generates a default config.r for you in that location.

It could be that once you have the necessary files, the `make.bat` or `makefile` just run `make.r config: config.r`.  So you could if you wanted type `make` from the root directory, but it would build in the build directory (which is where any generated makefile would live)

Anyone have any thoughts?  @gchiu - this would mean needing some version stamps that would not be deleted automatically, your "stable build".  It would likely be the most sensible choice for the "stable build" would be the same one being used for bootstrap.

**Comment by gchiu** [comment]
Can't we host the boot strap binaries on GitHub?

**Comment by hostilefork** [comment]
Don't everyone jump in to work on the build system at once!  :-P

Hate to spoil anyone's fun who wanted to do it, but I've taken a first step in this plan

https://github.com/metaeducation/ren-c/commit/20d0b2de004d152cca68acd07428f8c01ba12098

%make.r still assumes you want to build in the directory your shell is in at the time you run it.  *BUT* if you're in the same directory as %make.r, it will default to the `%build/` directory.  That directory is ignored in the `.gitignore`, and contains no committed files.

As this is moving in small steps, the prebuilt executables are still in the repository...but they are just moved to the top-level %prebuilt/ directory.  %configs/ and %tools/ are top-level now as well.

I still like the idea of having a stub `makefile` and `make.bat` that do intelligent things...for some definition of intelligent.  Seems there's no reason a Linux machine couldn't use `curl` to get a bootstrap binary--for instance.  But I really don't want the binaries in the repo.

> Can't we host the boot strap binaries on GitHub?

It's a possibility.  We just need to make some sort of decision about where, and what the reasons to pick one place vs. another are.

**Comment by dram** [comment]
How about using pre-generated makefile and prep/ files instead of binaries, for following benefits:

1. Text files are more portable than binaries, e.g. both x86 and x86-64 Linux (even other POSIX systems) can be supported by single set of makefile and prep/ files.
2. It will be easier to port to new platforms based on existing text files for others.
3. Source files can be more easily version controlled.

**Comment by hostilefork** [comment]
> How about using pre-generated makefile and prep/ files instead of binaries

R3-Alpha was [distributed with a makefile](https://github.com/rebol/rebol/blob/master/make/makefile) that had been generated by the `make-make.r` process.  You'd have to overwrite it if you wanted to change the settings (or edit it manually, knowing it wouldn't be kept).  You still had to run `make prep`, though, so you needed an executable.

The fact that [we can now run Rebol online](http://hostilefork.com/media/shared/replpad-js/) suggests you could ask it to generate a zip file with the make and prep information you wanted.  That could be an interesting idea...simpler than having a full compiler online.

Maybe we should think about that.  A `make makefile / make prep` service that runs in the browser and gives you a zipfile.

**Comment by dram** [comment]
What I mean is that we can go for two steps to compile Ren-C when no executable is available:

1. Compile `r3-boot` from pre-generated makefile and prep/ files.
2. Build `r3` using `r3-boot`.

The sole purpose of `r3-boot` is for bootstrapping, so makefile and prep/ files used to build it need not to be updated frequently.

**Comment by hostilefork** [comment]
> The sole purpose of r3-boot is for bootstrapping, so makefile and prep/ files used to build it need not to be updated frequently.

Hm, I see.  Interesting point.

Well whatever this stuff is...I feel like derived data shouldn't be in the repository...but fetched from elsewhere.  Whether it's an EXE or whether it's instructions for building an EXE.

One problem with my proposal about running online that I didn't think about is that it has to scan a lot of files.  That would be a lot of fetch() calls.  :-/  It also isn't particularly fast...I think we need to scrap the C parser and automatic-#ifdef detector and just go to something much simpler like what R3-Alpha was using (except still having the native specs in the C code).

Please feel free to help and chime in [on the forum](https://forum.rebol.info/) about whatever it is you may be interested in w.r.t. the project...

**Comment by zsx** [comment]
There are differences in the generated /prep files for different platforms.
I don't think you can use files generated for one platform with another one.

Another point about all of this is testing, so we want to test as much as
possible, generating prep files is part of that: we need to make sure that
prep files are properly generated for a correct interpreter.

**Comment by dram** [comment]
> Well whatever this stuff is...I feel like derived data shouldn't be in the repository...but fetched from elsewhere. Whether it's an EXE or whether it's instructions for building an EXE.

Some self-hosting languages with C target use separate repo to store that kind of data. e.g.

- https://github.com/nim-lang/csources
- https://github.com/Mercury-Language/mercury-srcdist

> Please feel free to help and chime in [on the forum](https://forum.rebol.info/) about whatever it is you may be interested in w.r.t. the project...

Sure. Will do when I have any concrete ideas.

**Comment by dram** [comment]
> There are differences in the generated /prep files for different platforms. I don't think you can use files generated for one platform with another one. Another point about all of this is testing, so we want to test as much as possible, generating prep files is part of that: we need to make sure that prep files are properly generated for a correct interpreter.

With regard to those two points, I think we can separate building process of Ren-C into 3 stages, i.e.

1. build `r3-boot` from prebuild source bundle (mantained in separate repo, with pre-generated makefile and prep/ files, makefiles are platform specific, prep/ files can be separated into two parts: common and platform specific)
2. Use `r3-boot` to generate new makefile and prep/ files (maybe with custom configs), and build `r3`.
3. Use `r3` to regenerate makefiles and prep/ files, and check that results are identical to output of stage 2.

**Comment by hostilefork** [comment]
The answer we are going with for the moment is to host files on s3, and make it easier with %make.sh and %make.bat files:

https://github.com/metaeducation/ren-c/pull/995

I think this is probably best for now.  Though @dram, welcome and thanks for the suggestions.  Please feel free to join us on the forum or in chat:

https://rebolforum.com/

https://chat.stackoverflow.com/rooms/291/rebol
