### ISSUE TITLE
READ fails on some URLs

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#972]
`read http://metaeducation.s3.amazonaws.com/travis-builds/load-r3.js`

fails with

** Access Error: protocol error: "Server closed connection"
** Where: fail switch awake either switch switch _ wake-up if while _ wait while sync-op else _ read do catch if _ do console

https://... works fine

0.13.2 build, appears between  6727232 (good) and 64c1276 (bad)

**Comment by hostilefork** [comment]
I got an assert, but you would not have if you were running a release build...

But if it's the same problem, this may fix it:

https://github.com/metaeducation/ren-c/commit/e11d10875e7b9fd7181e7676ee1bc032d1eb0e42

**Comment by giuliolunati** [comment]
Ok, works!
