### ISSUE TITLE
print [()] hard crashes 

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#974]
** Version:2.102.0.3.40**
** Platform:Windows win32-x64**
** Build:27-Mar-2019/1:02:16+0:00**
** Commit:e11d10875e7b9fd7181e7676ee1bc032d1eb0e42**
*
print [()]

causes a hard crash

See also https://github.com/hostilefork/replpad-js/issues/36

**Comment by hostilefork** [comment]
Thanks...fixed!

https://github.com/metaeducation/ren-c/commit/ca2d337d1c5956ec6ef8a70baeac87fd0746cc5d
