### ISSUE TITLE
tests/run-recover.r crash after a complet run

### ISSUE THREAD

**Issue by lkppo** [metaeducation/ren-c#975]
At least one leaked series at shutdown...
C Source File ..\src\core\m-pools.c, Line 329, Pointer 00000000077B9658
At evaluator tick: 166528484
unmanaged series was likely created during evaluator tick: 12358076
C Source File ..\src\core\m-series.c, Line 485, Pointer 0000000000770318
At evaluator tick: 166528484
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:

Executable not built with DEBUG_SERIES_ORIGINS, no more info

**Comment by hostilefork** [comment]
I'm not getting that problem with the current build.   *(Be sure to give the platform and commit you are using in your reports.  I think there's some way GitHub can have a template for bug reports, I should find that and make one...)*

However... we do have a problem that's showed up on bootstrap builds on Travis.  I pushed a fix for Giulio that seemed to work (and bootstrapped on my machine, with address sanitizer) then it's panic'ing on an address sanitizer build there.

I may not have time this weekend to do anything about it.  But any reproducible cases are helpful.

**Comment by hostilefork** [comment]
The issues that were causing problems on the bootstrap build were fixed this weekend, and I don't see any signs of this issue.

Please reopen if you reproduce it (with more version information) and I will be sure I am running that version on that architecture...
