### ISSUE TITLE
Pull requests look like they fail due to AWS upload error

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#977]
A Travis build running as a pull request doesn't have the credentialing to do uploads (it shouldn't!)  

But since we have an upload step running on the build, it gives the appearance of a failed build in the PR when it actually succeeded.  See:

https://travis-ci.org/metaeducation/ren-c/builds/516026916

Presumably there is some way to tell on Travis whether it is a PR or a push to master, and only run the aws commands if it's a master push (on the main branch, only, probably?)

**Comment by giuliolunati** [comment]
We should move the uploads to the deploy step, using `provider: script`

**Comment by hostilefork** [comment]
> We should move the uploads to the deploy step, using provider: script

Heads up for @BrianOtto that [this is what's happening](https://travis-ci.org/metaeducation/ren-c/builds/521603523?utm_source=github_status&utm_medium=notification)...

@giuliolunati, you want to do this?

**Comment by giuliolunati** [comment]
Let mebtry to fix it...

**Comment by giuliolunati** [comment]
I think that's fixed, please retry a PR. But some builds are failing due to an aws error :-/

**Comment by hostilefork** [comment]
It looks like maybe some of those older mac images don't have pip3, so AWS enviroment variable isn't getting set and it just runs `s3`:

https://travis-ci.org/metaeducation/ren-c/jobs/521695875#L169

The way Travis works with errors is it only counts the whole "step" (starting with `-` or `- |`) as having an error if the last thing has a return result that's bad.  Since the AWS installation step ends with echoing that succeeds, that glosses over the installation error.

To solve this we could perhaps have an environment variable that said whether `PIP=pip` or `PIP=pip3`.  But if you looked at those error messages that installing with plain pip got, it looks like newer versions of aws only use pip3...so we are getting old versions of `aws` if we use pip.  :-(

So this adds to the problem I noticed on the Linux deploys where they didn't have Python3.  I think what we should do is make sure every build in the matrix has pip3 and get AWS.  And make sure that if there's an AWS install error it registers in the right place so we aren't confused.  (Maybe even set AWS to `aws-install-failed-see-above` instead of leaving it blank?)

I don't know if this helps on getting Python3 configured...:

https://pythonhosted.org/CodeChat/.travis.yml.html

**Comment by hostilefork** [comment]
Thanks for fixing it!

https://travis-ci.org/metaeducation/ren-c/builds/523177721

Like I say...someday we might find that the version of `aws` that gets installed if we don't use pip3 is not going to be able to do something we need.  But hopefully by the time that day comes, we'll have some more people to look at it who will handle it for us!

**Comment by giuliolunati** [comment]
Optime!
