### ISSUE TITLE
dependency between sym-* and quoted

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#981]
sym-* and quoted do not play well together:

    >> ''@[]
    == []

    >> @[]
    == @[]

    >> @''[]
    == []

    >> ''[]
    == '[]

**Comment by hostilefork** [comment]
Glad you're looking at it (though I kind of wanted to defer worrying too much about it until there was time to do a more serious rethinking of how the scanner works on the commonalities of GET-XXX! and SYM-XXX!)

This should be an error; it's legal to quote SYM-XXXs, but not to SYM-a-quoted-thing:

    >> @''[]
    == []

**Comment by hostilefork** [comment]
The scanner has gone through some refactoring that should have improved this.  While the scanner could use a full state-machine-based rewrite, it should cover most cases reasonably now...so please report any problems found.
