### ISSUE TITLE
Failed Travis upload does not stop version stamp upload

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#988]
The Travis uploads are done in a loop:

https://github.com/metaeducation/ren-c/blob/de28ec6e6ea3c417bc686f8440ba8f1776d7c467/.travis.yml#L1054

However this loop doesn't do any checking of the `aws` return code to see if it failed.  As a result, a single transient upload failure doesn't stop the uploading of `last-deploy.short-hash`.

*(I've seen a transient failure on "An error occurred (RequestTimeTooSkewed) when calling the PutObject operation: The difference between the request time and the current time is too large.")*

I believe it needs some way of testing to make sure all the `aws` commands in the loop succeeded, and only write the short-hash if it did, and then make the overall error code result for the build step match the total success (including the short-hash upload)

**Comment by giuliolunati** [comment]
Ok, ASAP

**Comment by giuliolunati** [comment]
@HostileFork we have a big issue with aws deploy: all Python2 based build silently fail the deploy step. The aws command print a warning: */home/travis/.local/lib/python2.7/site-packages/urllib3/util/ssl_.py:357: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings* but doesn't fail. So Travis tell us the build is successful, but nothing is uploaded

**Comment by hostilefork** [comment]
> all Python2 based build silently fail the deploy step

Oh.  :-/

Well, I guess this means we have to look into the python3 sooner rather than later.  :-/

It doesn't sound like on Linux it is that hard:

https://askubuntu.com/questions/350751/install-and-run-python-3-at-the-same-time-than-python-2

On Mac maybe this bundle can be used?

https://docs.aws.amazon.com/cli/latest/userguide/install-bundle.html

**Comment by hostilefork** [comment]
As far as I can tell everything is working (!!)  If there's anything that's questionable going on that might be a problem in the future, please make a note on this issue so we don't lose track of it.  But other than that I'm just going to close it.

Thanks for taking care of it!
