### ISSUE TITLE
Terminal echo(ing) stops after executing R3

### ISSUE THREAD

**Issue by draegtun** [metaeducation/ren-c#994]
Running R3 (script, console or --do) will stop terminal echo(ing).  Problem seen on Linux & MacOS.

    $ ./r3 --do "1 + 1"
    $   ... now all input won't be echoed back ...
    $   ... until you enter:    stty sane

I've noticed this on Linux binaries going back to circa commit 19c69f7 

Compiling latest code reproduce bug unless `debug: asserts` added to build:

    # produces ./r3 with echo problem
    ../prebuilt/r3-linux-x64-8994d23 --suppress "*" ../make.r config: ../configs/default-config.r

    # this one is fine!
    ../prebuilt/r3-linux-x64-8994d23 --suppress "*" ../make.r config: ../configs/default-config.r debug: asserts

**Comment by giuliolunati** [comment]
The bug is between 4be9c85 (good) and 58bfe79 (bad)

**Comment by hostilefork** [comment]
Sorry that took so long to fix, I've been on the road...!

https://github.com/metaeducation/ren-c/commit/0994d333b02dfe4b2ca6f220e8b8c71bf39588cc
