### ISSUE TITLE
enhance repo description?

### ISSUE THREAD

**Issue by hyao** [metaeducation/ren-c#998]
Maybe we should add "and also a Rebol 3 interpreter" to the repo description? 

I am new to rebol and have spent quite some time trying to find a r3 implementation. 

Thanks,

**Comment by giuliolunati** [comment]
Welcome @hyao! Did you visit [the chat](https://chat.stackoverflow.com/rooms/291/rebol)?

**Comment by hyao** [comment]
no

**Comment by giuliolunati** [comment]
Please do! (Do you need 20 points on stackoverflow to chat)
Also you could visit [the forum](https://forum.rebol.info/) :-)

**Comment by gchiu** [comment]
Ok, mentioned Rebol 3
